"""Export a RetroReport to Markdown and self-contained HTML.

Mirrors the standup exporter (standup/export.py): readable artifacts written
under ``~/.scrum-agent/exports/retro/<project>/`` so a retro's outcome persists
as a shareable document, not just in the logs. The TUI **Export** button writes
the current board on demand.

Every card ``text`` / ``author`` is attacker-influenced (any LAN participant
added it), so the HTML escapes every field with ``html.escape`` — the same
defense the standup exporter uses. The HTML uses the shared design system
(``html_theme``) so retro pages look consistent with the rest of the app.

# See docs: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import logging
import re
from collections.abc import Sequence
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import RetroReport
from yeaboi.html_theme import escape as _e
from yeaboi.retro.board import CARRIED_STATUS_LABELS, RETRO_GRID_LABELS, RETRO_GRIDS

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "retro"


def _title(report: RetroReport) -> str:
    sprint = f" — {report.sprint_name}" if report.sprint_name else ""
    return f"Sprint Retro{sprint}"


def _reactions_str(card) -> str:
    """Render a card's reaction counts as ``👍 3 ❤️ 1`` (empty if none)."""
    return "  ".join(f"{emoji} {count}" for emoji, count in card.reactions if count)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_retro_markdown(report: RetroReport) -> str:
    """Return the retro as a Markdown document."""
    by_grid = report.by_grid()
    lines: list[str] = [
        f"# {_title(report)}",
        "",
        f"**Date:** {report.date}  ",
        f"**Participants:** {', '.join(report.participants) if report.participants else '—'}",
        "",
    ]
    from yeaboi.markdown_convert import md_table_cell as _cell

    for grid in RETRO_GRIDS:
        cards = by_grid.get(grid, [])
        lines.append(f"## {RETRO_GRID_LABELS[grid]}")
        lines.append("")
        if not cards:
            lines += ["_No cards._", ""]
            continue
        if grid == "action_items":
            # Action items are to-dos — checkboxes become native task lists
            # on Notion (to_do) and Confluence (<ac:task-list>).
            for c in cards:
                tag = " _(AI)_" if c.origin == "ai" else (f" — _{c.author}_" if c.author else "")
                lines.append(f"- [ ] {c.text}{tag}")
        else:
            # Card grids read best as a table (author + reactions alongside).
            lines += ["| Card | By | Reactions |", "|------|----|-----------|"]
            for c in cards:
                by = "_(AI)_" if c.origin == "ai" else (_cell(c.author) if c.author else "—")
                rx = _reactions_str(c) or "—"
                lines.append(f"| {_cell(c.text)} | {by} | {rx} |")
        lines.append("")

    # Last sprint's action items + the progress the team recorded this retro.
    if report.carried_action_items:
        lines += ["## Last sprint's action items — progress", ""]
        for c in report.carried_action_items:
            status = CARRIED_STATUS_LABELS.get(c.status or "pending", c.status or "Pending")
            lines.append(f"- **[{status}]** {_cell(c.text)}")
        lines.append("")

    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines += ["---", "", f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {ts}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


# Fixed semantic hues for the four retro columns (board order, not count order).
_GRID_VARS = {"went_well": "--ok", "didnt_go_well": "--warn", "action_items": "--accent", "demos": "--info"}


def _column_bar(by_grid: dict) -> str:
    """Cards-per-column segmented bar + counted legend, in board order, or ""."""
    from yeaboi.html_theme import legend, segment_bar

    counts = [(grid, len(by_grid.get(grid, []))) for grid in RETRO_GRIDS]
    if sum(n for _, n in counts) <= 0:
        return ""
    present = [(grid, n) for grid, n in counts if n > 0]
    bar = segment_bar([(n, _GRID_VARS[grid]) for grid, n in present], title="Cards per column")
    key = legend([(f"{RETRO_GRID_LABELS[grid]} {n}", _GRID_VARS[grid]) for grid, n in present])
    return f"<div style='margin-bottom:.6rem'>{bar}{key}</div>"


def _volume_sparkline(report: RetroReport, history) -> str:
    """Card-volume trend across this session's past retros, or ""."""
    from yeaboi.html_theme import history_series, sparkline_card

    points = history_series(
        history,
        date_key="retro_date",
        value_key="card_count",
        cutoff_date=report.date,
        current=(report.date, len(report.cards)),
    )
    return sparkline_card(
        points,
        title="Card volume trend",
        svg_title=f"Card volume — last {len(points)} retros",
    )


def build_retro_html(report: RetroReport, *, history: Sequence[dict] = ()) -> str:
    """Return the retro as a self-contained HTML document (shared design system).

    ``history`` is optional ``RetroStore.get_history`` rows (newest-first); with
    two or more retros it powers the card-volume trend sparkline.
    """
    from yeaboi.html_theme import avatar, chip, html_page

    by_grid = report.by_grid()
    if report.participants:
        participants = "".join(
            f"<span style='display:inline-flex;align-items:center;gap:.35rem;margin-right:.8rem'>"
            f"{avatar(name)}{_e(name)}</span>"
            for name in report.participants
        )
    else:
        participants = "&mdash;"
    parts: list[str] = [
        f"<p style='display:flex;flex-wrap:wrap;align-items:center;gap:.3rem'>"
        f"<strong>Participants:</strong> {participants}</p>",
        _column_bar(by_grid),
        _volume_sparkline(report, history),
    ]

    # Responsive grid of the retro columns — only columns WITH cards get a
    # card; empty ones collapse to footnote lines so the busy columns widen.
    footnotes: list[str] = []
    sections: list[str] = []
    for grid in RETRO_GRIDS:
        cards = by_grid.get(grid, [])
        if not cards:
            footnotes.append(f"<p class='card-footnote'>{_e(RETRO_GRID_LABELS[grid])} — no cards.</p>")
            continue
        rows = [
            f"<div class='card'><h3>{_e(RETRO_GRID_LABELS[grid])}</h3>",
            "<ul style='margin:0;padding-left:1.1rem'>",
        ]
        for c in cards:
            if c.origin == "ai":
                tag = " <em style='color:var(--text-muted)'>(AI)</em>"
            elif c.author:
                tag = (
                    f" <em style='color:var(--text-muted);display:inline-flex;align-items:center;gap:.3rem'>"
                    f"— {avatar(c.author)}{_e(c.author)}</em>"
                )
            else:
                tag = ""
            rx = _reactions_str(c)
            # Reaction emojis are from a fixed set, but chip() escapes defensively anyway.
            rx_html = f" {chip(rx)}" if rx else ""
            rows.append(f"<li>{_e(c.text)}{tag}{rx_html}</li>")
        rows.append("</ul></div>")
        sections.append("".join(rows))
    if sections:
        parts.append(f"<div class='analysis-grid member-grid'>{''.join(sections)}</div>")
    parts.extend(footnotes)

    # Last sprint's action items + their recorded progress.
    if report.carried_action_items:
        parts.append("<h2>Last sprint&rsquo;s action items &mdash; progress</h2>")
        parts.append("<ul style='margin:0;padding-left:1.1rem'>")
        for c in report.carried_action_items:
            status = CARRIED_STATUS_LABELS.get(c.status or "pending", c.status or "Pending")
            parts.append(f"<li><strong style='color:var(--text-muted)'>[{_e(status)}]</strong> {_e(c.text)}</li>")
        parts.append("</ul>")

    return html_page(
        title=f"{_title(report)} — {report.date}",
        heading=_title(report),
        subtitle=report.date,
        body="".join(parts),
        footer_note=f"Generated by yeaboi.ai • {datetime.now().strftime('%Y-%m-%d')}",
    )


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------


def export_retro(report: RetroReport, *, project_name: str = "", history: Sequence[dict] = ()) -> dict[str, Path]:
    """Write the retro as Markdown + HTML under the retro export dir.

    Returns ``{"markdown": Path, "html": Path}``. One file per day (dated
    filename) — a re-run the same day overwrites so the latest wins.
    ``history`` (RetroStore.get_history rows) feeds the HTML trend chart.
    """
    from yeaboi.paths import get_retro_export_dir

    key = _slug(project_name or report.project_name or report.session_id)
    out_dir = get_retro_export_dir(key)
    stem = f"retro-{report.date or 'latest'}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(build_retro_markdown(report), encoding="utf-8")
    html_path.write_text(build_retro_html(report, history=history), encoding="utf-8")
    logger.info("Retro exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
