"""Export a RetroReport to Markdown and self-contained HTML.

Mirrors the standup exporter (standup/export.py): readable artifacts written
under ``~/.scrum-agent/exports/retro/<project>/`` so a retro's outcome persists
as a shareable document, not just in the logs. The TUI **Export** button writes
the current board on demand.

Every card ``text`` / ``author`` is attacker-influenced (any LAN participant
added it). The Markdown builder still escapes by hand; the HTML carries the
board as a JSON payload that ``frontend/src/export`` draws, where a text child
cannot become markup however it is spelled.

The bundle also owns the columns' *appearance*: their labels come from
``types/enums.ts`` (codegen'd from ``retro/board.py``) and their colours from
``retro/gridTone.ts`` — the same typed map the live board reads, so a column is
the same colour in the meeting and in the file.

# See docs: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import json
import logging
import re
from collections.abc import Sequence
from dataclasses import asdict
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import RetroReport
from yeaboi.artifacts.render import annotations_markdown, edit_map, row_anchor, with_annotations
from yeaboi.retro.board import CARRIED_STATUS_LABELS, RETRO_GRID_LABELS, RETRO_GRIDS

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "retro"


def _title(report: RetroReport) -> str:
    sprint = f" — {report.sprint_name}" if report.sprint_name else ""
    return f"Sprint Retro{sprint}"


def _stem(report: RetroReport) -> str:
    """The filename stem both artifacts share.

    Shared so the HTML's ``<noscript>`` note can name the Markdown file written
    beside it; guessing that name twice is how the note ends up pointing at a
    file nobody wrote.
    """
    return f"retro-{report.date or 'latest'}"


def _reactions_str(card) -> str:
    """Render a card's reaction counts as ``👍 3 ❤️ 1`` (empty if none)."""
    return "  ".join(f"{emoji} {count}" for emoji, count in card.reactions if count)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_retro_markdown(report: RetroReport, *, generated_ts: str = "") -> str:
    """Return the retro as a Markdown document.

    ``generated_ts`` pins the footer timestamp; empty means "now". The seam
    hoists it into :func:`build_retro_export_inputs` so the sidecar and the
    reference implementation render the same bytes from the same document.
    """
    by_grid = report.by_grid()
    lines: list[str] = [
        f"# {_title(report)}",
        "",
        f"**Date:** {report.date}  ",
        f"**Participants:** {', '.join(report.participants) if report.participants else '—'}",
        "",
    ]
    from yeaboi.markdown_convert import md_table_cell as _cell

    for grid in RETRO_GRIDS:
        cards = by_grid.get(grid, [])
        lines.append(f"## {RETRO_GRID_LABELS[grid]}")
        lines.append("")
        if not cards:
            lines += ["_No cards._", ""]
            continue
        if grid == "action_items":
            # Action items are to-dos — checkboxes become native task lists
            # on Notion (to_do) and Confluence (<ac:task-list>).
            for c in cards:
                tag = " _(AI)_" if c.origin == "ai" else (f" — _{c.author}_" if c.author else "")
                lines.append(f"- [ ] {c.text}{tag}")
        else:
            # Card grids read best as a table (author + reactions alongside).
            lines += ["| Card | By | Reactions |", "|------|----|-----------|"]
            for c in cards:
                by = "_(AI)_" if c.origin == "ai" else (_cell(c.author) if c.author else "—")
                rx = _reactions_str(c) or "—"
                lines.append(f"| {_cell(c.text)} | {by} | {rx} |")
        lines.append("")

    # Last sprint's action items + the progress the team recorded this retro.
    if report.carried_action_items:
        lines += ["## Last sprint's action items — progress", ""]
        for c in report.carried_action_items:
            status = CARRIED_STATUS_LABELS.get(c.status or "pending", c.status or "Pending")
            lines.append(f"- **[{status}]** {_cell(c.text)}")
        lines.append("")

    ts = generated_ts or datetime.now().strftime("%Y-%m-%d %H:%M")
    lines += annotations_markdown(report.annotations)
    lines += ["---", "", f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {ts}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def _card_payload(card, *, editable: bool = False, list_field: str = "cards") -> dict:
    """One card as data: its text, who wrote it, and what the room did to it."""
    out: dict = {"text": card.text, "reactions": [[emoji, count] for emoji, count in card.reactions if count]}
    if editable and card.id:
        # Addressed by id, not by text — the text is the editable field, and a
        # key that moves when you edit it is not a key.
        anchor = row_anchor(list_field, "id", card.id)
        out["anchor"] = anchor
        out["edit"] = edit_map(anchor, card, ("text",))
    # A card the AI facilitator wrote is attributed as such, never to a person —
    # `origin` is the fact, and `author` on those rows is the literal "AI".
    if card.origin == "ai":
        out["ai"] = True
    elif card.author:
        out["author"] = card.author
    return out


def retro_export_args(
    report: RetroReport, *, history: Sequence[dict] = (), editable: bool = False, generated_date: str = ""
) -> dict[str, object]:
    """Return the chrome + payload keyword arguments for one retro document.

    See :func:`yeaboi.standup.export.standup_export_args` for why this is split
    out: an editable shared document rebuilds the payload without a page.
    ``generated_date`` pins the footer date (empty means "now") — the seam's
    only nondeterminism, hoisted by :func:`build_retro_export_inputs`.
    """
    from yeaboi.html_theme import trend

    by_grid = report.by_grid()
    # Every column, including the empty ones, in board order. Whether an empty
    # column gets a card or a footnote is a layout question, and layout is the
    # bundle's; sending only the filled ones would decide it here.
    columns = [
        {"grid": grid, "cards": [_card_payload(c, editable=editable) for c in by_grid.get(grid, [])]}
        for grid in RETRO_GRIDS
    ]

    args = dict(
        mode="retro",
        title=_title(report),
        wordmark="retro",
        facts=[
            ("DATE", report.date or ""),
            ("CARDS", str(len(report.cards))),
            ("PARTICIPANTS", str(len(report.participants))),
        ],
        report={
            "kind": "retro",
            "columns": columns,
            "participants": list(report.participants),
            "carried": [
                {
                    "status": c.status or "pending",
                    "text": c.text,
                    **(_card_payload(c, editable=True, list_field="carried_action_items") if editable else {}),
                }
                for c in report.carried_action_items
            ],
            "trend": trend(
                history,
                date_key="retro_date",
                value_key="card_count",
                title="Card volume trend",
                label="Card volume",
                cutoff_date=report.date,
                current=(report.date, len(report.cards)),
            ),
        },
        footer=f"Generated by yeaboi.ai • {generated_date or datetime.now().strftime('%Y-%m-%d')}",
    )
    return with_annotations(args, report)


def build_retro_html(report: RetroReport, *, history: Sequence[dict] = (), document_title: str = "") -> str:
    """Return the retro as a self-contained HTML document.

    ``history`` is optional ``RetroStore.get_history`` rows (newest-first); with
    two or more retros it powers the card-volume trend sparkline.
    """
    from yeaboi.html_theme import export_page

    doc = _export_doc(report, history=history)
    return export_page(
        **doc["args"],  # type: ignore[arg-type]
        markdown_name=f"{_stem(report)}.md",
        document_title=document_title,
    )


# ---------------------------------------------------------------------------
# The build-export seam — retro.build_export
# ---------------------------------------------------------------------------


def build_retro_export_inputs(report: RetroReport, *, history: Sequence[dict] = (), editable: bool = False) -> dict:
    """Freeze one retro document into the ``retro.build_export`` wire params.

    A single ``datetime.now()`` capture hoists the seam's only nondeterminism
    into the params, and the json round-trip freezes the report into the same
    plain-JSON shape a stored one takes — so the sidecar and the reference
    implementation see byte-identical inputs.
    """
    now = datetime.now()
    return json.loads(
        json.dumps(
            {
                "report": asdict(report),
                "history": list(history),
                "editable": bool(editable),
                "generated_ts": now.strftime("%Y-%m-%d %H:%M"),
                "generated_date": now.strftime("%Y-%m-%d"),
            }
        )
    )


def build_retro_export(inputs: dict) -> dict:
    """Python reference implementation of ``retro.build_export``.

    Rebuilds the report through the store deserializer — the same round-trip a
    stored report takes — then renders with the wire-pinned timestamps. Key
    order is contractual: ``args`` is json.dumps-ed into the page boot payload.
    """
    from yeaboi.gocore.client import CONTRACT_VERSION
    from yeaboi.retro.store import report_from_dict

    report = report_from_dict(inputs["report"])
    return {
        "contract_version": CONTRACT_VERSION,
        "markdown": build_retro_markdown(report, generated_ts=inputs["generated_ts"]),
        "args": retro_export_args(
            report,
            history=inputs["history"],
            editable=inputs["editable"],
            generated_date=inputs["generated_date"],
        ),
    }


# The exact top-level keyword set the callers splat into
# ``export_page(**args, markdown_name=...)``, which is keyword-only and rejects
# unknown names. Pinned here because a within-v1 binary skew that grows, drops,
# or renames a key would otherwise TypeError out of the export *after* the .md
# was written, instead of falling back to Python (the ``go_score_docs``
# key-set idiom; annotations ride inside ``report``, never at this level).
_RETRO_ARG_KEYS = frozenset({"mode", "title", "wordmark", "facts", "report", "footer"})


def _valid_retro_export(result: object, inputs: dict) -> bool:
    """Structural checks on a sidecar result — any failure means malformed → Python."""
    if not isinstance(result, dict):
        return False
    if not (isinstance(result.get("markdown"), str) and result["markdown"]):
        return False
    args = result.get("args")
    if not isinstance(args, dict) or set(args) != _RETRO_ARG_KEYS:
        return False
    report = args.get("report")
    if not isinstance(report, dict) or report.get("kind") != "retro":
        return False
    # Column and carried counts are structural facts the inputs already fix; a
    # result that disagrees would render a different board, not a slower one.
    columns = report.get("columns")
    if not isinstance(columns, list) or len(columns) != len(RETRO_GRIDS):
        return False
    carried = report.get("carried")
    return isinstance(carried, list) and len(carried) == len(inputs["report"].get("carried_action_items") or ())


def go_build_retro_export(inputs: dict) -> dict | None:
    """``retro.build_export`` served by the sidecar, or None → Python computes."""
    client = _client()
    if client is None:
        return None
    from yeaboi.gocore import CoreError

    try:
        result = client.request("retro.build_export", inputs)
    except CoreError as exc:
        logger.warning("gocore: retro.build_export failed (%s) — falling back to Python", exc)
        return None
    if not _valid_retro_export(result, inputs):
        logger.warning("gocore: retro.build_export result malformed — falling back to Python")
        return None
    logger.info("gocore: retro.build_export served by the sidecar")
    return result


def _client():
    """The discovered sidecar client, or None; never raises (an export must not sink)."""
    try:
        from yeaboi import gocore

        return gocore.get_client()
    except Exception as exc:  # noqa: BLE001 — dispatch must never sink an export
        logger.warning("gocore: client unavailable (%s: %s) — using the Python path", type(exc).__name__, exc)
        return None


def _export_doc(report: RetroReport, *, history: Sequence[dict] = (), editable: bool = False) -> dict:
    """One retro document — markdown + export args — sidecar-served when available."""
    inputs = build_retro_export_inputs(report, history=history, editable=editable)
    return go_build_retro_export(inputs) or build_retro_export(inputs)


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------


def export_retro(report: RetroReport, *, project_name: str = "", history: Sequence[dict] = ()) -> dict[str, Path]:
    """Write the retro as Markdown + HTML under the retro export dir.

    Returns ``{"markdown": Path, "html": Path}``. One file per day (dated
    filename) — a re-run the same day overwrites so the latest wins.
    ``history`` (RetroStore.get_history rows) feeds the HTML trend chart.
    """
    from yeaboi.html_theme import export_page
    from yeaboi.paths import get_retro_export_dir

    key = _slug(project_name or report.project_name or report.session_id)
    out_dir = get_retro_export_dir(key)
    stem = _stem(report)
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    # One seam call renders both artifacts — the markdown and the HTML's args
    # come from the same dispatch, so the two files can never disagree about
    # which side (sidecar or Python) built them.
    doc = _export_doc(report, history=history)
    md_path.write_text(doc["markdown"], encoding="utf-8")
    html_path.write_text(export_page(**doc["args"], markdown_name=f"{stem}.md"), encoding="utf-8")
    logger.info("Retro exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
