"""Export a RetroReport to Markdown and self-contained HTML.

Mirrors the standup exporter (standup/export.py): readable artifacts written
under ``~/.scrum-agent/exports/retro/<project>/`` so a retro's outcome persists
as a shareable document, not just in the logs. The TUI **Export** button writes
the current board on demand.

Every card ``text`` / ``author`` is attacker-influenced (any LAN participant
added it). The Markdown builder still escapes by hand; the HTML carries the
board as a JSON payload that ``frontend/src/export`` draws, where a text child
cannot become markup however it is spelled.

The bundle also owns the columns' *appearance*: their labels come from
``types/enums.ts`` (codegen'd from ``retro/board.py``) and their colours from
``retro/gridTone.ts`` — the same typed map the live board reads, so a column is
the same colour in the meeting and in the file.

# See docs: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import logging
import re
from collections.abc import Sequence
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import RetroReport
from yeaboi.retro.board import CARRIED_STATUS_LABELS, RETRO_GRID_LABELS, RETRO_GRIDS

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "retro"


def _title(report: RetroReport) -> str:
    sprint = f" — {report.sprint_name}" if report.sprint_name else ""
    return f"Sprint Retro{sprint}"


def _stem(report: RetroReport) -> str:
    """The filename stem both artifacts share.

    Shared so the HTML's ``<noscript>`` note can name the Markdown file written
    beside it; guessing that name twice is how the note ends up pointing at a
    file nobody wrote.
    """
    return f"retro-{report.date or 'latest'}"


def _reactions_str(card) -> str:
    """Render a card's reaction counts as ``👍 3 ❤️ 1`` (empty if none)."""
    return "  ".join(f"{emoji} {count}" for emoji, count in card.reactions if count)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_retro_markdown(report: RetroReport) -> str:
    """Return the retro as a Markdown document."""
    by_grid = report.by_grid()
    lines: list[str] = [
        f"# {_title(report)}",
        "",
        f"**Date:** {report.date}  ",
        f"**Participants:** {', '.join(report.participants) if report.participants else '—'}",
        "",
    ]
    from yeaboi.markdown_convert import md_table_cell as _cell

    for grid in RETRO_GRIDS:
        cards = by_grid.get(grid, [])
        lines.append(f"## {RETRO_GRID_LABELS[grid]}")
        lines.append("")
        if not cards:
            lines += ["_No cards._", ""]
            continue
        if grid == "action_items":
            # Action items are to-dos — checkboxes become native task lists
            # on Notion (to_do) and Confluence (<ac:task-list>).
            for c in cards:
                tag = " _(AI)_" if c.origin == "ai" else (f" — _{c.author}_" if c.author else "")
                lines.append(f"- [ ] {c.text}{tag}")
        else:
            # Card grids read best as a table (author + reactions alongside).
            lines += ["| Card | By | Reactions |", "|------|----|-----------|"]
            for c in cards:
                by = "_(AI)_" if c.origin == "ai" else (_cell(c.author) if c.author else "—")
                rx = _reactions_str(c) or "—"
                lines.append(f"| {_cell(c.text)} | {by} | {rx} |")
        lines.append("")

    # Last sprint's action items + the progress the team recorded this retro.
    if report.carried_action_items:
        lines += ["## Last sprint's action items — progress", ""]
        for c in report.carried_action_items:
            status = CARRIED_STATUS_LABELS.get(c.status or "pending", c.status or "Pending")
            lines.append(f"- **[{status}]** {_cell(c.text)}")
        lines.append("")

    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines += ["---", "", f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {ts}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def _card_payload(card) -> dict:
    """One card as data: its text, who wrote it, and what the room did to it."""
    out: dict = {"text": card.text, "reactions": [[emoji, count] for emoji, count in card.reactions if count]}
    # A card the AI facilitator wrote is attributed as such, never to a person —
    # `origin` is the fact, and `author` on those rows is the literal "AI".
    if card.origin == "ai":
        out["ai"] = True
    elif card.author:
        out["author"] = card.author
    return out


def retro_export_args(report: RetroReport, *, history: Sequence[dict] = ()) -> dict[str, object]:
    """Return the chrome + payload keyword arguments for one retro document.

    See :func:`yeaboi.standup.export.standup_export_args` for why this is split
    out: an editable shared document rebuilds the payload without a page.
    """
    from yeaboi.html_theme import trend

    by_grid = report.by_grid()
    # Every column, including the empty ones, in board order. Whether an empty
    # column gets a card or a footnote is a layout question, and layout is the
    # bundle's; sending only the filled ones would decide it here.
    columns = [{"grid": grid, "cards": [_card_payload(c) for c in by_grid.get(grid, [])]} for grid in RETRO_GRIDS]

    return dict(
        mode="retro",
        title=_title(report),
        wordmark="retro",
        facts=[
            ("DATE", report.date or ""),
            ("CARDS", str(len(report.cards))),
            ("PARTICIPANTS", str(len(report.participants))),
        ],
        report={
            "kind": "retro",
            "columns": columns,
            "participants": list(report.participants),
            "carried": [{"status": c.status or "pending", "text": c.text} for c in report.carried_action_items],
            "trend": trend(
                history,
                date_key="retro_date",
                value_key="card_count",
                title="Card volume trend",
                label="Card volume",
                cutoff_date=report.date,
                current=(report.date, len(report.cards)),
            ),
        },
        footer=f"Generated by yeaboi.ai • {datetime.now().strftime('%Y-%m-%d')}",
    )


def build_retro_html(report: RetroReport, *, history: Sequence[dict] = (), document_title: str = "") -> str:
    """Return the retro as a self-contained HTML document.

    ``history`` is optional ``RetroStore.get_history`` rows (newest-first); with
    two or more retros it powers the card-volume trend sparkline.
    """
    from yeaboi.html_theme import export_page

    return export_page(
        **retro_export_args(report, history=history),  # type: ignore[arg-type]
        markdown_name=f"{_stem(report)}.md",
        document_title=document_title,
    )


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------


def export_retro(report: RetroReport, *, project_name: str = "", history: Sequence[dict] = ()) -> dict[str, Path]:
    """Write the retro as Markdown + HTML under the retro export dir.

    Returns ``{"markdown": Path, "html": Path}``. One file per day (dated
    filename) — a re-run the same day overwrites so the latest wins.
    ``history`` (RetroStore.get_history rows) feeds the HTML trend chart.
    """
    from yeaboi.paths import get_retro_export_dir

    key = _slug(project_name or report.project_name or report.session_id)
    out_dir = get_retro_export_dir(key)
    stem = _stem(report)
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(build_retro_markdown(report), encoding="utf-8")
    html_path.write_text(build_retro_html(report, history=history), encoding="utf-8")
    logger.info("Retro exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
