// Table-driven tests for the Python-semantics primitives. Every expected
// value below was generated by running the expression through CPython 3.14
// (round(), f"{x:.0f}", repr(), json.dumps(), str.lower(), str.strip(),
// pathlib) - the tables encode Python's answers, not this package's.
// The source is deliberately ASCII-only: non-ASCII runes appear as \u
// escapes so the byte-level expectations are visible in review.
package pysem

import (
	"encoding/json"
	"math"
	"strings"
	"testing"
)

func jn(s string) json.Number { return json.Number(s) }

func TestRoundNHalfEven(t *testing.T) {
	cases := []struct {
		x    float64
		n    int
		want float64
	}{
		{0.5, 0, 0.0},
		{1.5, 0, 2.0},
		{2.5, 0, 2.0},
		{-2.5, 0, -2.0},
		{2.675, 2, 2.67}, // 2.675 is 2.6749999... in binary; NOT 2.68
		{0.125, 2, 0.12}, // exact tie -> even
		{0.135, 2, 0.14}, // 0.135 is 0.135000...5 in binary
		{1.0055, 3, 1.006},
		{2.0, 0, 2.0},
		{96.55, 1, 96.5}, // 96.549999... in binary; NOT 96.6
		{1e15 + 0.5, 0, 1e15},
	}
	for _, c := range cases {
		if got := RoundN(c.x, c.n); got != c.want {
			t.Errorf("RoundN(%v, %d) = %v, want %v", c.x, c.n, got, c.want)
		}
	}
	if got := RoundN(-0.5, 0); got != 0 || !math.Signbit(got) {
		t.Errorf("RoundN(-0.5, 0) = %v, want -0.0", got)
	}
	if got := RoundN(math.NaN(), 2); !math.IsNaN(got) {
		t.Errorf("RoundN(NaN, 2) = %v, want NaN", got)
	}
}

func TestFormat0fHalfEven(t *testing.T) {
	cases := []struct {
		x    float64
		want string
	}{
		{0.5, "0"},
		{1.5, "2"},
		{2.5, "2"},
		{-2.5, "-2"},
		{99.5, "100"}, // 99.5 is exact; ties to even (100)
		{100.5, "100"},
		{1e15 + 0.5, "1000000000000000"},
	}
	for _, c := range cases {
		if got := Format0f(c.x); got != c.want {
			t.Errorf("Format0f(%v) = %q, want %q", c.x, got, c.want)
		}
	}
}

func TestReprStr(t *testing.T) {
	cases := []struct{ in, want string }{
		{"hello", "'hello'"},
		{"it's", "\"it's\""},                   // single quote, no double -> double-quoted
		{"say \"hi\"", "'say \"hi\"'"},         // double quote -> single-quoted, unescaped
		{"both ' and \"", "'both \\' and \"'"}, // both -> single-quoted, ' escaped
		{"tab\there", "'tab\\there'"},
		{"café", "'café'"},                         // printable non-ASCII stays literal
		{"emoji \U0001f600", "'emoji \U0001f600'"}, // So category is printable
		{"\x00\x1f", "'\\x00\\x1f'"},
		{"del\x7f", "'del\\x7f'"},
		{"nbsp end", "'nbsp\\xa0end'"}, // Zs other than space is not printable
		{"line\nbreak", "'line\\nbreak'"},
		{"back\\slash", "'back\\\\slash'"},
	}
	for _, c := range cases {
		if got := ReprStr(c.in); got != c.want {
			t.Errorf("ReprStr(%q) = %s, want %s", c.in, got, c.want)
		}
	}
}

func TestReprAny(t *testing.T) {
	cases := []struct {
		in   any
		want string
	}{
		{"x", "'x'"},
		{true, "True"},
		{false, "False"},
		{nil, "None"},
		{jn("3"), "3"},
		{jn("2.5"), "2.5"},
	}
	for _, c := range cases {
		if got := ReprAny(c.in); got != c.want {
			t.Errorf("ReprAny(%v) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestWriteJSONStringEnsureASCII(t *testing.T) {
	cases := []struct{ in, want string }{
		{"café", "\"caf\\u00e9\""},
		{"中文", "\"\\u4e2d\\u6587\""},
		{"emoji \U0001f600", "\"emoji \\ud83d\\ude00\""}, // astral -> surrogate pair
		{"quote\"back\\slash", "\"quote\\\"back\\\\slash\""},
		{"ctrl\x1f", "\"ctrl\\u001f\""},
		{"tab\tnl\ncr\r", "\"tab\\tnl\\ncr\\r\""},
	}
	for _, c := range cases {
		var b strings.Builder
		WriteJSONString(&b, c.in)
		if got := b.String(); got != c.want {
			t.Errorf("WriteJSONString(%q) = %s, want %s", c.in, got, c.want)
		}
	}
}

func TestJSONDumpsMatchesPythonDefaults(t *testing.T) {
	inner := []any{jn("1.5"), "x", nil, true}
	obj := EmptyObj()
	obj.Set("b", jn("1"))
	obj.Set("a", inner)
	if got, want := JSONDumps(obj), "{\"b\": 1, \"a\": [1.5, \"x\", null, true]}"; got != want {
		t.Errorf("JSONDumps = %s, want %s", got, want)
	}
	nums := EmptyObj()
	nums.Set("n", jn("1e20"))
	nums.Set("m", jn("0.1"))
	nums.Set("k", jn("3.0"))
	if got, want := JSONDumps(nums), "{\"n\": 1e+20, \"m\": 0.1, \"k\": 3.0}"; got != want {
		t.Errorf("JSONDumps floats = %s, want %s", got, want)
	}
}

func TestDecodeOrderedPreservesDocumentOrder(t *testing.T) {
	doc := "{\"z\": 1, \"a\": {\"k2\": null, \"k1\": []}, \"m\": \"s\"}"
	v, err := DecodeOrdered([]byte(doc))
	if err != nil {
		t.Fatal(err)
	}
	obj, ok := v.(*Obj)
	if !ok {
		t.Fatalf("DecodeOrdered returned %T, want *Obj", v)
	}
	if got := strings.Join(obj.Keys(), ","); got != "z,a,m" {
		t.Errorf("top-level key order = %s, want z,a,m", got)
	}
	nested := obj.Get("a").(*Obj)
	if got := strings.Join(nested.Keys(), ","); got != "k2,k1" {
		t.Errorf("nested key order = %s, want k2,k1", got)
	}
	// Round trip through the Python-shaped writer must be byte-identical.
	if got := JSONDumps(obj); got != doc {
		t.Errorf("round trip = %s, want %s", got, doc)
	}
}

func TestObjDuplicateKeyKeepsFirstPositionLastValue(t *testing.T) {
	o := EmptyObj()
	o.Set("a", jn("1"))
	o.Set("b", jn("2"))
	o.Set("a", jn("3"))
	if got := strings.Join(o.Keys(), ","); got != "a,b" {
		t.Errorf("key order = %s, want a,b", got)
	}
	if got := Str(o.Get("a")); got != "3" {
		t.Errorf("a = %s, want 3", got)
	}
}

func TestLowerTurkishDottedI(t *testing.T) {
	// U+0130 full-lowercases to "i" + U+0307 combining dot above.
	if got, want := Lower("İstanbul"), "i̇stanbul"; got != want {
		t.Errorf("Lower(U+0130stanbul) = %q, want %q", got, want)
	}
	if got := Lower("HELLO Ünïcode"); got != "hello ünïcode" {
		t.Errorf("Lower = %q", got)
	}
}

func TestStripMatchesPythonWhitespace(t *testing.T) {
	// U+001C..U+001F are str.isspace() whitespace that Go's unicode.IsSpace lacks.
	if got := Strip("\x1c\x1d a b  \t\n"); got != "a b" {
		t.Errorf("Strip = %q, want %q", got, "a b")
	}
	if got := Strip(" x "); got != "x" {
		t.Errorf("Strip nbsp = %q, want %q", got, "x")
	}
}

func TestTruthyAndIntOrZero(t *testing.T) {
	for _, v := range []any{nil, false, "", jn("0"), jn("0.0"), []any{}, EmptyObj()} {
		if Truthy(v) {
			t.Errorf("Truthy(%#v) = true, want false", v)
		}
	}
	for _, v := range []any{true, "x", jn("0.5"), []any{nil}, "0"} {
		if !Truthy(v) {
			t.Errorf("Truthy(%#v) = false, want true", v)
		}
	}
	intCases := []struct {
		in   any
		want int64
	}{
		{nil, 0},
		{"", 0},
		{jn("7"), 7},
		{jn("2.9"), 2}, // int() truncates toward zero
		{jn("-2.9"), -2},
		{"  12_3  ", 123}, // int("12_3") == 123 in Python
		{true, 1},
	}
	for _, c := range intCases {
		got, err := IntOrZero(c.in)
		if err != nil || got != c.want {
			t.Errorf("IntOrZero(%#v) = %d, %v; want %d", c.in, got, err, c.want)
		}
	}
	if _, err := IntOrZero("12x"); err == nil {
		t.Error("IntOrZero(12x) should raise ValueError")
	} else if pe, ok := err.(*Error); !ok || pe.Class != "ValueError" {
		t.Errorf("IntOrZero(12x) error = %v, want ValueError", err)
	}
}

func TestStrMirrorsPython(t *testing.T) {
	cases := []struct {
		in   any
		want string
	}{
		{"s", "s"},
		{true, "True"},
		{false, "False"},
		{nil, "None"},
		{jn("42"), "42"},
		{jn("2.5"), "2.5"},
		{jn("3.0"), "3.0"},
	}
	for _, c := range cases {
		if got := Str(c.in); got != c.want {
			t.Errorf("Str(%#v) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestPathStr(t *testing.T) {
	cases := []struct {
		base  string
		parts []string
		want  string
	}{
		{"a/b", []string{"c"}, "a/b/c"},
		{"/x//y/", nil, "/x/y"},
		{"", nil, "."},
		{"a", []string{"./b", ""}, "a/b"},
		{"a", []string{"../b"}, "a/../b"}, // pathlib keeps ".."
	}
	for _, c := range cases {
		if got := PathStr(c.base, c.parts...); got != c.want {
			t.Errorf("PathStr(%q, %v) = %q, want %q", c.base, c.parts, got, c.want)
		}
	}
}

func TestIsWordRune(t *testing.T) {
	// underscore, ASCII letter, Latin-1 letter, Arabic-Indic digit (Nd),
	// superscript two (No), small roman numeral eight (Nl).
	for _, r := range []rune{'_', 'a', 'é', '٣', '²', 'ⅷ'} {
		if !IsWordRune(r) {
			t.Errorf("IsWordRune(%q) = false, want true", r)
		}
	}
	for _, r := range []rune{'-', '.', ' ', '\t'} {
		if IsWordRune(r) {
			t.Errorf("IsWordRune(%q) = true, want false", r)
		}
	}
}
