package standup

// automation_test.go — port of tests/unit/test_standup_automation.py, plus
// golden unicode-boundary cases verified against the Python reference.

import (
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/yeaboi-ai/yeaboi/go/internal/pysem"
)

// autoItem builds an activity item from key/value pairs.
func autoItem(kv ...any) *pysem.Obj {
	item := pysem.EmptyObj()
	for i := 0; i+1 < len(kv); i += 2 {
		item.Set(kv[i].(string), kv[i+1])
	}
	return item
}

// autoReview mirrors the _review test helper: a review item with defaults,
// overridden by kv pairs (dict.update keeps first-seen key positions).
func autoReview(kv ...any) *pysem.Obj {
	item := autoItem(
		"source", "azure-devops",
		"author", "Dev Person",
		"kind", "review",
		"title", "reviewed code on PR #1: fix",
		"body", "",
		"timestamp", "2026-07-27T09:00:00",
		"key", "rc-1",
		"repository", "repo-a",
		"url", "https://dev.azure.com/x",
	)
	for i := 0; i+1 < len(kv); i += 2 {
		item.Set(kv[i].(string), kv[i+1])
	}
	return item
}

// autoWizBody mirrors _wiz_body: near-identical scanner template where only
// path/line/PR number vary.
func autoWizBody(repo string, n int) string {
	return fmt.Sprintf(
		"Security finding: publicly exposed storage container detected in %s/infra/main.tf "+
			"line %d. Severity: High. Review the attached policy before merging pull request %d.",
		repo, n, n,
	)
}

// autoWizItems mirrors TestWizIncident._items: 18 near-identical review
// comments across 6 repos, posted as the human.
func autoWizItems(bodyFn func(string, int) string) []*pysem.Obj {
	repos := []string{"infra", "onboarding", "credit-risk", "security", "pricing", "automation"}
	items := []*pysem.Obj{}
	for i := 0; i < 18; i++ {
		repo := repos[i%6]
		items = append(items, autoReview(
			"body", bodyFn(repo, i),
			"repository", repo,
			"timestamp", fmt.Sprintf("2026-07-27T09:00:%02d", i),
			"key", fmt.Sprintf("rc-%d", i),
		))
	}
	return items
}

func TestAutomationBurstCrossRepoExcludesAll(t *testing.T) {
	genuine := autoReview(
		"body", "I think we should extract this into a helper — see my inline suggestion.",
		"key", "real",
	)
	items := append([]*pysem.Obj{genuine}, autoWizItems(autoWizBody)...)
	kept, clusters := partitionAutomated(items, nil)
	if !reflect.DeepEqual(kept, []*pysem.Obj{genuine}) {
		t.Fatalf("kept = %d items, want just the genuine review", len(kept))
	}
	total := 0
	reasons := map[string]bool{}
	for _, c := range clusters {
		total += c.count
		reasons[c.reason] = true
	}
	if total != 18 {
		t.Errorf("total excluded = %d, want 18", total)
	}
	if !reflect.DeepEqual(reasons, map[string]bool{"burst-cross-repo": true}) {
		t.Errorf("reasons = %v, want {burst-cross-repo}", reasons)
	}
	if clusters[0].author != "Dev Person" {
		t.Errorf("author = %q, want Dev Person", clusters[0].author)
	}
	if len(clusters[0].repositories) != 6 {
		t.Errorf("repositories = %v, want 6 entries", clusters[0].repositories)
	}
}

func TestAutomationSignedBodiesHitWizMarker(t *testing.T) {
	items := autoWizItems(func(repo string, n int) string {
		return fmt.Sprintf("Reported by Wiz: exposed bucket in %s (finding %d).", repo, n)
	})
	kept, clusters := partitionAutomated(items, nil)
	if len(kept) != 0 {
		t.Errorf("kept = %d items, want 0", len(kept))
	}
	for _, c := range clusters {
		if c.reason != "marker:wiz" {
			t.Errorf("reason = %q, want marker:wiz", c.reason)
		}
	}
}

func TestAutomationHandlingValues(t *testing.T) {
	if !reflect.DeepEqual(validAutomationHandling, []string{"exclude", "off"}) {
		t.Errorf("validAutomationHandling = %v", validAutomationHandling)
	}
}

func TestAutomationBoilerplateMarker(t *testing.T) {
	item := autoReview("body", "This comment was auto-generated by the compliance pipeline.")
	kept, clusters := partitionAutomated([]*pysem.Obj{item}, nil)
	if len(kept) != 0 {
		t.Errorf("kept = %d items, want 0", len(kept))
	}
	if clusters[0].reason != "boilerplate" {
		t.Errorf("reason = %q, want boilerplate", clusters[0].reason)
	}
}

func TestAutomationScannerNamesAreAttributionShaped(t *testing.T) {
	// "wizard"/"fortify the tests" must NOT match — bare product words are
	// excluded by design.
	for _, body := range []string{
		"walk through the setup wizard flow",
		"let's fortify the tests here",
		"nice fix",
	} {
		kept, clusters := partitionAutomated([]*pysem.Obj{autoReview("body", body)}, nil)
		if len(clusters) != 0 {
			t.Errorf("body %q: clusters = %v, want none", body, clusters)
		}
		if len(kept) != 1 {
			t.Errorf("body %q: kept = %d items, want 1", body, len(kept))
		}
	}
}

func TestAutomationKindGuardCommitsNeverFlagged(t *testing.T) {
	commit := autoReview(
		"kind", "commit",
		"title", "fix wiz.io finding in storage module",
		"body", "Reported by Wiz scan",
	)
	kept, clusters := partitionAutomated([]*pysem.Obj{commit}, nil)
	if !reflect.DeepEqual(kept, []*pysem.Obj{commit}) {
		t.Errorf("kept = %v, want [commit]", kept)
	}
	if len(clusters) != 0 {
		t.Errorf("clusters = %v, want none", clusters)
	}
}

func TestAutomationScannerNamedPRTitleNeverFlagsAHumanReview(t *testing.T) {
	// Fetchers synthesize review titles from the PR title, so a genuine human
	// review of a PR *about* scanner work must keep its credit — markers scan
	// the body only.
	review := autoReview(
		"title", "approved PR #12: fix snyk findings and add semgrep rules",
		"body", "LGTM, nice cleanup!",
	)
	kept, clusters := partitionAutomated([]*pysem.Obj{review}, nil)
	if !reflect.DeepEqual(kept, []*pysem.Obj{review}) {
		t.Errorf("kept = %v, want [review]", kept)
	}
	if len(clusters) != 0 {
		t.Errorf("clusters = %v, want none", clusters)
	}
}

func TestAutomationCustomMarkerMatchesBareWord(t *testing.T) {
	markers := parseCustomMarkers("wiz, acme-scanner")
	tokens := []string{}
	for _, m := range markers {
		tokens = append(tokens, m.token)
	}
	if !reflect.DeepEqual(tokens, []string{"wiz", "acme-scanner"}) {
		t.Fatalf("tokens = %v", tokens)
	}
	item := autoReview("body", "Wiz found an issue in this file.")
	kept, clusters := partitionAutomated([]*pysem.Obj{item}, markers)
	if len(kept) != 0 {
		t.Errorf("kept = %d items, want 0", len(kept))
	}
	if clusters[0].reason != "marker:wiz" {
		t.Errorf("reason = %q, want marker:wiz", clusters[0].reason)
	}
}

func TestAutomationParseCustomMarkersEmpty(t *testing.T) {
	if got := parseCustomMarkers(""); len(got) != 0 {
		t.Errorf("parseCustomMarkers(\"\") = %v, want empty", got)
	}
	if got := parseCustomMarkers("  , ,"); len(got) != 0 {
		t.Errorf("parseCustomMarkers(\"  , ,\") = %v, want empty", got)
	}
}

func TestAutomationBotAuthor(t *testing.T) {
	byType := autoReview("author_type", "bot", "body", "x")
	bySuffix := autoReview("author", "acme-scan[bot]", "body", "y")
	kept, clusters := partitionAutomated([]*pysem.Obj{byType, bySuffix}, nil)
	if len(kept) != 0 {
		t.Errorf("kept = %d items, want 0", len(kept))
	}
	for _, c := range clusters {
		if c.reason != "bot-author" {
			t.Errorf("reason = %q, want bot-author", c.reason)
		}
	}
}

// Golden: a custom marker with non-word edges ("[bot]-tag") follows Python's
// unicode \b — before "[" the boundary requires the PRECEDING character to be
// a word character, so a unicode letter enables the match and a space
// prevents it (verified against the Python reference).
func TestAutomationCustomMarkerUnicodeBoundaries(t *testing.T) {
	markers := parseCustomMarkers("[bot]-tag")
	flaggedItem := autoReview("body", "wired é[bot]-tag into the flow")
	kept, clusters := partitionAutomated([]*pysem.Obj{flaggedItem}, markers)
	if len(kept) != 0 || len(clusters) != 1 || clusters[0].reason != "marker:[bot]-tag" {
		t.Errorf("unicode-adjacent: kept=%d clusters=%v, want flagged as marker:[bot]-tag", len(kept), clusters)
	}
	// Space before "[": non-word|non-word is not a boundary — Python finds no
	// match, and neither must we.
	plain := autoReview("body", "wired the [bot]-tag into the flow")
	kept, clusters = partitionAutomated([]*pysem.Obj{plain}, markers)
	if len(kept) != 1 || len(clusters) != 0 {
		t.Errorf("space-adjacent: kept=%d clusters=%v, want kept unflagged", len(kept), clusters)
	}
	// Trailing unicode letter cancels the closing boundary.
	trailing := autoReview("body", "é[bot]-tagé")
	kept, clusters = partitionAutomated([]*pysem.Obj{trailing}, markers)
	if len(kept) != 1 || len(clusters) != 0 {
		t.Errorf("trailing-unicode: kept=%d clusters=%v, want kept unflagged", len(kept), clusters)
	}
}

// Golden: "ésonarqube" must NOT hit the sonar marker — é is a word character
// in Python's unicode \b, so there is no boundary before "sonarqube"
// (verified against the Python reference).
func TestAutomationUnicodeBoundaryBlocksSonarMarker(t *testing.T) {
	kept, clusters := partitionAutomated(
		[]*pysem.Obj{autoReview("body", "the ésonarqube gate flagged this")}, nil)
	if len(kept) != 1 || len(clusters) != 0 {
		t.Errorf("ésonarqube: kept=%d clusters=%v, want kept unflagged", len(kept), clusters)
	}
	// Positive control: the plain word matches.
	kept, clusters = partitionAutomated(
		[]*pysem.Obj{autoReview("body", "sonarqube flagged this")}, nil)
	if len(kept) != 0 || len(clusters) != 1 || clusters[0].reason != "marker:sonar" {
		t.Errorf("sonarqube: kept=%d clusters=%v, want flagged as marker:sonar", len(kept), clusters)
	}
}

func TestAutomationFingerprintNormalizesVariants(t *testing.T) {
	a := automationFingerprint(autoReview(
		"body", "High severity finding 12 detected in src/app/main.py — details at https://scan.example/a1b2c3d4e5f6789",
	))
	b := automationFingerprint(autoReview(
		"body", "High severity finding 99 detected in lib/core/util.py — details at https://scan.example/deadbeefcafe123",
	))
	if a == "" || a != b {
		t.Errorf("fingerprints differ: %q vs %q", a, b)
	}
	// Pinned against the Python reference output.
	if want := "high severity finding # detected in <path> — details at <url>"; a != want {
		t.Errorf("fingerprint = %q, want %q", a, want)
	}
}

func TestAutomationShortRepeatsNeverCluster(t *testing.T) {
	// Distinct timestamps so only the template rule could apply — and it must
	// not (under 40 chars).
	items := []*pysem.Obj{}
	for i := 0; i < 12; i++ {
		items = append(items, autoReview(
			"body", "lgtm",
			"repository", fmt.Sprintf("r%d", i),
			"key", fmt.Sprintf("k%d", i),
			"timestamp", fmt.Sprintf("2026-07-27T09:%02d:00", i),
		))
	}
	kept, clusters := partitionAutomated(items, nil)
	if len(kept) != 12 {
		t.Errorf("kept = %d items, want 12", len(kept))
	}
	if len(clusters) != 0 {
		t.Errorf("clusters = %v, want none", clusters)
	}
}

func TestAutomationBelowThresholdsKept(t *testing.T) {
	// 4 similar comments across 4 repos: under K=5.
	items := []*pysem.Obj{}
	for i := 0; i < 4; i++ {
		items = append(items, autoReview(
			"body", autoWizBody("x", 1),
			"repository", fmt.Sprintf("r%d", i),
			"timestamp", fmt.Sprintf("2026-07-27T09:0%d:00", i),
			"key", fmt.Sprintf("k%d", i),
		))
	}
	kept, clusters := partitionAutomated(items, nil)
	if len(kept) != 4 || len(clusters) != 0 {
		t.Errorf("cross-repo: kept=%d clusters=%v, want 4 kept and none", len(kept), clusters)
	}
	// 6 similar comments in ONE repo: under the single-repo floor of 10.
	items = nil
	for i := 0; i < 6; i++ {
		items = append(items, autoReview(
			"body", autoWizBody("solo", 1),
			"repository", "solo",
			"timestamp", fmt.Sprintf("2026-07-27T09:0%d:00", i),
			"key", fmt.Sprintf("s%d", i),
		))
	}
	kept, clusters = partitionAutomated(items, nil)
	if len(kept) != 6 || len(clusters) != 0 {
		t.Errorf("single-repo: kept=%d clusters=%v, want 6 kept and none", len(kept), clusters)
	}
}

func TestAutomationSingleRepoTemplateSpam(t *testing.T) {
	items := []*pysem.Obj{}
	for i := 0; i < 10; i++ {
		items = append(items, autoReview(
			"body", autoWizBody("solo", i),
			"repository", "solo",
			"timestamp", fmt.Sprintf("2026-07-27T09:00:%02d", i),
			"key", fmt.Sprintf("s%d", i),
		))
	}
	kept, clusters := partitionAutomated(items, nil)
	if len(kept) != 0 {
		t.Errorf("kept = %d items, want 0", len(kept))
	}
	if clusters[0].reason != "burst-template" {
		t.Errorf("reason = %q, want burst-template", clusters[0].reason)
	}
}

func TestAutomationSameSecondAcrossRepos(t *testing.T) {
	// Distinct bodies (no template match) but one identity posting in 3 repos
	// in the same second.
	items := []*pysem.Obj{}
	for i := 0; i < 3; i++ {
		items = append(items, autoReview(
			"body", fmt.Sprintf("unique comment body number %d with enough length to be plausible text", i),
			"repository", fmt.Sprintf("r%d", i),
			"timestamp", "2026-07-27T09:00:00",
			"key", fmt.Sprintf("k%d", i),
		))
	}
	kept, clusters := partitionAutomated(items, nil)
	if len(kept) != 0 {
		t.Errorf("kept = %d items, want 0", len(kept))
	}
	if clusters[0].reason != "burst-same-second" {
		t.Errorf("reason = %q, want burst-same-second", clusters[0].reason)
	}
}

func TestAutomationOrderPreservedForKept(t *testing.T) {
	auto := autoReview("body", "This comment was auto-generated by scanning.", "key", "a")
	first := autoReview(
		"body", "real comment one with actual human substance",
		"key", "f",
		"timestamp", "2026-07-27T08:00:00",
	)
	second := autoReview(
		"body", "another genuine remark from a human reviewer",
		"key", "s",
		"timestamp", "2026-07-27T10:00:00",
	)
	kept, _ := partitionAutomated([]*pysem.Obj{first, auto, second}, nil)
	keys := []string{}
	for _, item := range kept {
		keys = append(keys, strOr(item, "key"))
	}
	if !reflect.DeepEqual(keys, []string{"f", "s"}) {
		t.Errorf("kept keys = %v, want [f s]", keys)
	}
}

func TestAutomationMarkerNoticeCopy(t *testing.T) {
	_, clusters := partitionAutomated([]*pysem.Obj{autoReview("body", "Reported by Wiz: finding.")}, nil)
	lines := noticeLines(clusters)
	if len(lines) != 2 {
		t.Fatalf("lines = %v, want 2", lines)
	}
	line, tail := lines[0], lines[1]
	if !strings.Contains(line, "Excluded 1 review item(s) posted under 'Dev Person'") {
		t.Errorf("line = %q", line)
	}
	if !strings.Contains(line, "matched 'wiz'") {
		t.Errorf("line = %q", line)
	}
	// The how-to-tune instructions live in the single shared tail line, not in
	// every cluster line — the notice recurs daily, the manual must not.
	if strings.Contains(line, "automation_markers") {
		t.Errorf("line contains the tune instructions: %q", line)
	}
	if !strings.Contains(tail, "automation_markers") || !strings.Contains(tail, "automation_handling") {
		t.Errorf("tail = %q", tail)
	}
}

func TestAutomationBurstNoticeCopy(t *testing.T) {
	items := []*pysem.Obj{}
	for i := 0; i < 18; i++ {
		items = append(items, autoReview(
			"body", autoWizBody(fmt.Sprintf("r%d", i%6), i),
			"repository", fmt.Sprintf("r%d", i%6),
			"timestamp", fmt.Sprintf("2026-07-27T09:00:%02d", i),
			"key", fmt.Sprintf("k%d", i),
		))
	}
	_, clusters := partitionAutomated(items, nil)
	lines := noticeLines(clusters)
	if len(lines) != 2 {
		t.Fatalf("lines = %v, want 2", lines)
	}
	line, tail := lines[0], lines[1]
	if !strings.HasPrefix(line, "Excluded 18 near-identical review item(s) posted under 'Dev Person'") {
		t.Errorf("line = %q", line)
	}
	if !strings.Contains(line, "across 6 repositories") {
		t.Errorf("line = %q", line)
	}
	if !strings.Contains(tail, "'off'") {
		t.Errorf("tail = %q", tail)
	}
}

func TestAutomationTuneTailAppearsOnceForManyClusters(t *testing.T) {
	_, marker := partitionAutomated([]*pysem.Obj{autoReview("body", "Reported by Wiz: finding.")}, nil)
	items := []*pysem.Obj{}
	for i := 0; i < 18; i++ {
		items = append(items, autoReview(
			"body", autoWizBody(fmt.Sprintf("r%d", i%6), i),
			"repository", fmt.Sprintf("r%d", i%6),
			"timestamp", fmt.Sprintf("2026-07-27T09:00:%02d", i),
			"key", fmt.Sprintf("k%d", i),
		))
	}
	_, burst := partitionAutomated(items, nil)
	lines := noticeLines(append(append([]automationCluster{}, marker...), burst...))
	if len(lines) != 3 {
		t.Fatalf("lines = %v, want 3", lines)
	}
	tails := 0
	for _, line := range lines {
		if strings.Contains(line, "automation_handling") {
			tails++
		}
	}
	if tails != 1 {
		t.Errorf("tune tail appears %d times, want 1", tails)
	}
}

func TestAutomationNoClustersNoTail(t *testing.T) {
	if got := noticeLines(nil); len(got) != 0 {
		t.Errorf("noticeLines(nil) = %v, want empty", got)
	}
}
