"""Markdown export for agentwatch artifacts.

Markdown only, deliberately: every other mode's HTML export rides a dedicated
React export component in the committed web bundles, and agentwatch does not
have one yet — shipping HTML through another mode's component would wear the
wrong branding and payload shape. The HTML surface is a tracked follow-up for
the web-ux workstream; the export dict simply has no "html" key until then
(same convention as the missing-pptx path in reporting/export.py).
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from yeaboi.agent.state import AgentAdvisorReport, AgentSecurityReport, AgentStandupDigest, AgentUsageReport

logger = logging.getLogger(__name__)


def _md_footer() -> list[str]:
    return ["", "---", f"*Generated by yeaboi.ai on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*", ""]


def build_usage_markdown(report: AgentUsageReport) -> str:
    """The agent usage report as a shareable Markdown document."""
    lines: list[str] = [
        f"# Agent Usage — {report.period_start} → {report.period_end}",
        "",
        f"**${report.total_cost_usd:,.2f} estimated** across {report.session_count} session(s) — "
        f"{report.total_input_tokens:,} input / {report.total_output_tokens:,} output tokens, "
        f"cache {report.total_cache_read_tokens:,} read / {report.total_cache_write_tokens:,} written.",
        "",
        f"*Costs are local estimates at public rates (as of {report.pricing_as_of}) — not a provider bill.*",
    ]
    if report.unknown_model_cost_share > 0:
        lines.append(
            f"*⚠ {report.unknown_model_cost_share:.0%} of the total is priced at a fallback tier "
            "(unknown model rates).*"
        )

    if report.by_model:
        lines += [
            "",
            "## By model",
            "",
            "| model | cost | input | output | cache r/w | calls |",
            "|---|---|---|---|---|---|",
        ]
        for r in report.by_model:
            marker = "" if r.known_pricing else " \\*"
            lines.append(
                f"| {r.model}{marker} | ${r.cost_usd:,.2f} | {r.input_tokens:,} | {r.output_tokens:,} "
                f"| {r.cache_read_tokens:,}/{r.cache_write_tokens:,} | {r.calls} |"
            )

    for title, rows in (("By project", report.by_project), ("By source", report.by_source)):
        if not rows:
            continue
        lines += ["", f"## {title}", "", "| | cost | sessions | input | output |", "|---|---|---|---|---|"]
        for r in rows:
            lines.append(f"| {r.key} | ${r.cost_usd:,.2f} | {r.sessions} | {r.input_tokens:,} | {r.output_tokens:,} |")

    if report.daily_trend:
        lines += ["", "## Daily trend", "", "| date | cost | sessions |", "|---|---|---|"]
        for point in report.daily_trend:
            lines.append(f"| {point.date} | ${point.cost_usd:,.2f} | {point.sessions} |")

    for title, items in (("Insights", report.insights), ("Recommendations", report.recommendations)):
        if items:
            lines += ["", f"## {title}", ""] + [f"- {item}" for item in items]

    if report.warnings:
        lines += ["", "## Warnings", ""] + [f"- ⚠ {w}" for w in report.warnings]

    lines += _md_footer()
    return "\n".join(lines)


def standup_totals(digest: AgentStandupDigest) -> tuple[str, str | None]:
    """What a standup digest counted, as ``(count phrase, cost phrase or None)``.

    One decision, three renderers. `build_standup_markdown`, `build_standup_plaintext`
    and `render.format_standup_rich` all lead with this, and they must agree: the
    markdown one is written to disk on every run, so a headline that is only honest
    in Slack is one that ships wrong in the file nobody re-reads for months.

    ``0 session(s), $0.00 estimated`` is the shape to avoid. It is *true* on a run
    that did not collect local sessions (``include_local_sessions=False``, which is
    how the cloud routine runs) and it reads as "the agents cost nothing today".
    So a digest with no sessions counts whatever it does have, and the cost phrase
    is dropped entirely rather than printed as zero — a total of $0.00 is a claim
    about spend, and this run did not measure spend. `digest.coverage_notes` says
    which of "none ran" and "none were collected" it was; that is their job, not
    the headline's.
    """
    if digest.sessions_worked:
        return f"{digest.sessions_worked} session(s)", f"${digest.total_cost_usd:,.2f} estimated"
    if digest.repo_activity:
        return f"{len(digest.repo_activity)} agent-authored tracker item(s)", None
    return "no agent activity recorded in the window", None


def build_standup_markdown(digest: AgentStandupDigest) -> str:
    """The agent standup digest as a shareable Markdown document."""
    count, cost = standup_totals(digest)
    seen = f", agents seen: {', '.join(digest.agents_seen)}" if digest.agents_seen else ""
    lines: list[str] = [
        f"# Agent Standup — {digest.digest_date}",
        "",
        f"Window {digest.window_start} → {digest.window_end}: **{count}**" + (f", {cost}" if cost else "") + seen + ".",
    ]
    if digest.narrative:
        lines += ["", digest.narrative]
    for title, items in (
        ("Highlights", digest.highlights),
        ("In flight", digest.in_flight),
        ("Needs a human", digest.attention_items),
    ):
        if items:
            lines += ["", f"## {title}", ""] + [f"- {item}" for item in items]
    if digest.session_summaries:
        lines += ["", "## Local sessions", "", "| project | source | models | turns | cost |", "|---|---|---|---|---|"]
        for s in digest.session_summaries:
            lines.append(
                f"| {s.project} ({s.branch}) | {s.source} | {', '.join(s.models)} | {s.turns} | ${s.cost_usd:,.2f} |"
            )
    if digest.repo_activity:
        lines += ["", "## Agent-authored tracker activity", ""]
        for r in digest.repo_activity:
            status = f" ({r.status})" if r.status else ""
            link = f"[{r.title}]({r.url})" if r.url else r.title
            lines.append(f"- **{r.kind}**{status} {link} — {r.repo}, by {r.agent_marker}")
    for title, items in (("Coverage notes", digest.coverage_notes), ("Warnings", digest.warnings)):
        if items:
            lines += ["", f"## {title}", ""] + [f"- {'⚠ ' if title == 'Warnings' else ''}{item}" for item in items]
    lines += _md_footer()
    return "\n".join(lines)


def build_standup_plaintext(digest: AgentStandupDigest) -> str:
    """A compact plaintext digest for Slack delivery (no markdown tables)."""
    seen = f" · {', '.join(digest.agents_seen)}" if digest.agents_seen else ""
    count, cost = standup_totals(digest)
    headline = count + (f", {cost}" if cost else "") + seen
    lines = [f"*Agent Standup — {digest.digest_date}*", headline]
    if digest.narrative:
        lines += ["", digest.narrative]
    for title, items in (
        ("Highlights", digest.highlights),
        ("Needs a human", digest.attention_items),
    ):
        if items:
            lines += ["", f"{title}:"] + [f"• {item}" for item in items[:5]]
    if digest.coverage_notes:
        lines += ["", *(f"_{note}_" for note in digest.coverage_notes[:2])]
    return "\n".join(lines)


def build_security_markdown(report: AgentSecurityReport) -> str:
    """The agent security report as a shareable Markdown document."""
    lines: list[str] = [
        f"# Agent Security — {report.scan_date}",
        "",
        f"**Posture: {report.posture}** — {report.sessions_scanned} session(s) scanned, "
        f"{len(report.mcp_servers)} MCP server(s), {report.secrets_found} secret signal(s).",
        "",
        "*Deterministic pattern scan — an indicator, not a security audit. Findings reference "
        "file and line only; matched content is never stored.*",
    ]
    if report.summary:
        lines += ["", report.summary]
    if report.findings:
        lines += ["", "## Findings", "", "| severity | finding | where | remediation |", "|---|---|---|---|"]
        for f in report.findings:
            where = f"{f.location}:{f.line_no}" if f.line_no else f.location
            lines.append(f"| {f.severity} | {f.title} ({f.pattern}) | {where} | {f.remediation} |")
    if report.mcp_servers:
        lines += ["", "## MCP servers", "", "| name | scope | transport | flags |", "|---|---|---|---|"]
        for record in report.mcp_servers:
            lines.append(f"| {record.name} | {record.scope} | {record.transport} | {', '.join(record.flags) or '—'} |")
    if report.recommendations:
        lines += ["", "## Recommendations", ""] + [f"- {item}" for item in report.recommendations]
    if report.warnings:
        lines += ["", "## Warnings", ""] + [f"- ⚠ {w}" for w in report.warnings]
    lines += _md_footer()
    return "\n".join(lines)


def build_advisor_markdown(report: AgentAdvisorReport) -> str:
    """The agent advisor report as a shareable Markdown document."""
    lines: list[str] = [
        f"# Agent Advisor — {report.period_start} → {report.period_end}",
        "",
        f"**~${report.recoverable_usd:,.2f} recoverable** of ${report.total_cost_usd:,.2f} estimated spend"
        + (f" ({report.recoverable_share:.0%})" if report.total_cost_usd > 0 else "")
        + f" — {report.files_audited} transcript(s) audited, "
        f"{report.read_calls} Read call(s) totalling {report.read_bytes:,} bytes.",
        "",
        f"*Estimates: tokens ≈ bytes/4, priced at ~${report.effective_input_rate_per_mtok:,.2f}/Mtok input "
        f"(rates as of {report.pricing_as_of}). Computed locally from session logs — a floor, not an invoice.*",
    ]
    if report.unknown_rate_share > 0:
        lines.append(
            f"*⚠ {report.unknown_rate_share:.0%} of input tokens priced at a fallback tier (unknown model rates).*"
        )

    items = [i for i in report.line_items if i.content_bytes]
    if items:
        lines += [
            "",
            "## Waste by mechanism",
            "",
            "| mechanism | calls | size | est. cost | of Read bytes | note |",
            "|---|---|---|---|---|---|",
        ]
        for i in items:
            marker = "" if i.recoverable else " \\*"
            lines.append(
                f"| {i.label}{marker} | {i.calls or '—'} | {i.est_tokens:,} tok | ${i.est_usd:,.2f} "
                f"| {i.share_of_read_bytes:.0%} | {i.note} |"
            )
        if any(not i.recoverable for i in items):
            lines.append("")
            lines.append("*\\* sized as context, not counted in the recoverable total.*")

    lines += [
        "",
        "## Cache health",
        "",
        f"- Alignment score: **{report.alignment_score}/100**",
        f"- A Read stays in context for a median of {report.residency_median} assistant turn(s) "
        f"(p90 {report.residency_p90}) — every retained turn re-bills it as cache reads.",
        f"- {report.gaps_over_5m} inter-message gap(s) over 5 minutes ({report.gaps_over_1h} over 1h) "
        f"across {report.sessions_with_gap} session(s) — likely cache-death windows.",
    ]
    if report.volatile_signals:
        lines += ["", "## Volatile content in prompt-prefix files", "", "| file | findings | kinds |", "|---|---|---|"]
        for s in report.volatile_signals:
            kinds = ", ".join(f"{label}×{count}" for label, count in s.counts)
            lines.append(f"| {s.location} | {s.total} | {kinds} |")

    for title, prose in (("Insights", report.insights), ("Recommendations", report.recommendations)):
        if prose:
            lines += ["", f"## {title}", ""] + [f"- {item}" for item in prose]

    if report.warnings:
        lines += ["", "## Warnings", ""] + [f"- ⚠ {w}" for w in report.warnings]

    lines += _md_footer()
    return "\n".join(lines)


_BUILDERS = {
    "usage": build_usage_markdown,
    "standup": build_standup_markdown,
    "security": build_security_markdown,
    "advisor": build_advisor_markdown,
}


def export_artifact(artifact, *, kind: str) -> dict[str, Path]:
    """Write ``artifact`` under ~/.yeaboi/exports/agentwatch/<kind>/; return paths.

    One dated file per kind — a same-day re-run overwrites, which is the
    blueprint's convention (the newest run is the truth for that day).
    """
    from yeaboi.paths import get_agentwatch_export_dir

    builder = _BUILDERS[kind]
    out_dir = get_agentwatch_export_dir(kind)
    stem = f"{kind}-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    md_path = out_dir / f"{stem}.md"
    md_path.write_text(builder(artifact), encoding="utf-8")
    logger.info("agentwatch export: wrote %s", md_path)
    return {"markdown": md_path}
