"""Markdown export for agentwatch artifacts.

Markdown only, deliberately: every other mode's HTML export rides a dedicated
React export component in the committed web bundles, and agentwatch does not
have one yet — shipping HTML through another mode's component would wear the
wrong branding and payload shape. The HTML surface is a tracked follow-up for
the web-ux workstream; the export dict simply has no "html" key until then
(same convention as the missing-pptx path in reporting/export.py).
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path

from yeaboi.agent.state import AgentStandupDigest, AgentUsageReport

logger = logging.getLogger(__name__)


def _md_footer() -> list[str]:
    return ["", "---", f"*Generated by yeaboi.ai on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}*", ""]


def build_usage_markdown(report: AgentUsageReport) -> str:
    """The agent usage report as a shareable Markdown document."""
    lines: list[str] = [
        f"# Agent Usage — {report.period_start} → {report.period_end}",
        "",
        f"**${report.total_cost_usd:,.2f} estimated** across {report.session_count} session(s) — "
        f"{report.total_input_tokens:,} input / {report.total_output_tokens:,} output tokens, "
        f"cache {report.total_cache_read_tokens:,} read / {report.total_cache_write_tokens:,} written.",
        "",
        f"*Costs are local estimates at public rates (as of {report.pricing_as_of}) — not a provider bill.*",
    ]
    if report.unknown_model_cost_share > 0:
        lines.append(
            f"*⚠ {report.unknown_model_cost_share:.0%} of the total is priced at a fallback tier "
            "(unknown model rates).*"
        )

    if report.by_model:
        lines += [
            "",
            "## By model",
            "",
            "| model | cost | input | output | cache r/w | calls |",
            "|---|---|---|---|---|---|",
        ]
        for r in report.by_model:
            marker = "" if r.known_pricing else " \\*"
            lines.append(
                f"| {r.model}{marker} | ${r.cost_usd:,.2f} | {r.input_tokens:,} | {r.output_tokens:,} "
                f"| {r.cache_read_tokens:,}/{r.cache_write_tokens:,} | {r.calls} |"
            )

    for title, rows in (("By project", report.by_project), ("By source", report.by_source)):
        if not rows:
            continue
        lines += ["", f"## {title}", "", "| | cost | sessions | input | output |", "|---|---|---|---|---|"]
        for r in rows:
            lines.append(f"| {r.key} | ${r.cost_usd:,.2f} | {r.sessions} | {r.input_tokens:,} | {r.output_tokens:,} |")

    if report.daily_trend:
        lines += ["", "## Daily trend", "", "| date | cost | sessions |", "|---|---|---|"]
        for point in report.daily_trend:
            lines.append(f"| {point.date} | ${point.cost_usd:,.2f} | {point.sessions} |")

    for title, items in (("Insights", report.insights), ("Recommendations", report.recommendations)):
        if items:
            lines += ["", f"## {title}", ""] + [f"- {item}" for item in items]

    if report.warnings:
        lines += ["", "## Warnings", ""] + [f"- ⚠ {w}" for w in report.warnings]

    lines += _md_footer()
    return "\n".join(lines)


def build_standup_markdown(digest: AgentStandupDigest) -> str:
    """The agent standup digest as a shareable Markdown document."""
    lines: list[str] = [
        f"# Agent Standup — {digest.digest_date}",
        "",
        f"Window {digest.window_start} → {digest.window_end}: "
        f"**{digest.sessions_worked} session(s)**, ${digest.total_cost_usd:,.2f} estimated"
        + (f", agents seen: {', '.join(digest.agents_seen)}" if digest.agents_seen else "")
        + ".",
    ]
    if digest.narrative:
        lines += ["", digest.narrative]
    for title, items in (
        ("Highlights", digest.highlights),
        ("In flight", digest.in_flight),
        ("Needs a human", digest.attention_items),
    ):
        if items:
            lines += ["", f"## {title}", ""] + [f"- {item}" for item in items]
    if digest.session_summaries:
        lines += ["", "## Local sessions", "", "| project | source | models | turns | cost |", "|---|---|---|---|---|"]
        for s in digest.session_summaries:
            lines.append(
                f"| {s.project} ({s.branch}) | {s.source} | {', '.join(s.models)} | {s.turns} | ${s.cost_usd:,.2f} |"
            )
    if digest.repo_activity:
        lines += ["", "## Agent-authored tracker activity", ""]
        for r in digest.repo_activity:
            status = f" ({r.status})" if r.status else ""
            link = f"[{r.title}]({r.url})" if r.url else r.title
            lines.append(f"- **{r.kind}**{status} {link} — {r.repo}, by {r.agent_marker}")
    for title, items in (("Coverage notes", digest.coverage_notes), ("Warnings", digest.warnings)):
        if items:
            lines += ["", f"## {title}", ""] + [f"- {'⚠ ' if title == 'Warnings' else ''}{item}" for item in items]
    lines += _md_footer()
    return "\n".join(lines)


def build_standup_plaintext(digest: AgentStandupDigest) -> str:
    """A compact plaintext digest for Slack delivery (no markdown tables)."""
    lines = [
        f"*Agent Standup — {digest.digest_date}*",
        f"{digest.sessions_worked} session(s), ${digest.total_cost_usd:,.2f} estimated"
        + (f" · {', '.join(digest.agents_seen)}" if digest.agents_seen else ""),
    ]
    if digest.narrative:
        lines += ["", digest.narrative]
    for title, items in (
        ("Highlights", digest.highlights),
        ("Needs a human", digest.attention_items),
    ):
        if items:
            lines += ["", f"{title}:"] + [f"• {item}" for item in items[:5]]
    if digest.coverage_notes:
        lines += ["", *(f"_{note}_" for note in digest.coverage_notes[:2])]
    return "\n".join(lines)


_BUILDERS = {
    "usage": build_usage_markdown,
    "standup": build_standup_markdown,
}


def export_artifact(artifact, *, kind: str) -> dict[str, Path]:
    """Write ``artifact`` under ~/.yeaboi/exports/agentwatch/<kind>/; return paths.

    One dated file per kind — a same-day re-run overwrites, which is the
    blueprint's convention (the newest run is the truth for that day).
    """
    from yeaboi.paths import get_agentwatch_export_dir

    builder = _BUILDERS[kind]
    out_dir = get_agentwatch_export_dir(kind)
    stem = f"{kind}-{datetime.now(UTC).strftime('%Y-%m-%d')}"
    md_path = out_dir / f"{stem}.md"
    md_path.write_text(builder(artifact), encoding="utf-8")
    logger.info("agentwatch export: wrote %s", md_path)
    return {"markdown": md_path}
