/**
 * The wordmark renderer, pinned against Python's.
 *
 * `WORDMARK_SAMPLES` is `render_ascii_text()` output generated by
 * `scripts/gen_web_types.py`, so this is a genuine cross-language check rather
 * than two implementations agreeing with their own separate expectations. That
 * distinction is not academic here: the join-code wire format shipped broken
 * with a green test on each side, because each side asserted the contract it
 * had assumed. One generated artifact, both readers.
 */

import { render, screen } from '@testing-library/preact';
import { describe, expect, it } from 'vitest';

import { BLOCK_GLYPHS, WORDMARK_SAMPLES } from '../../types/enums';
import { renderWordmark, Wordmark } from './Wordmark';

describe('renderWordmark', () => {
  it.each(Object.keys(WORDMARK_SAMPLES))('matches render_ascii_text for %j', (word) => {
    expect(renderWordmark(word)).toEqual([...(WORDMARK_SAMPLES[word] as readonly [string, string])]);
  });

  it('is case-insensitive — the glyph table is uppercase only', () => {
    expect(renderWordmark('retro')).toEqual(renderWordmark('RETRO'));
  });

  it('replaces an unknown character with a gap, keeping the rows aligned', () => {
    // Dropping it instead would shift every later letter on one row only.
    const [top, bottom] = renderWordmark('a/a');
    expect(top.length).toBe(bottom.length);
    // "A" plus its separator is four cells, then the three-cell gap.
    expect(top.slice(4, 7)).toBe('   ');
    expect(bottom.slice(4, 7)).toBe('   ');
  });

  it('renders both rows to the same width for every known glyph', () => {
    // A glyph whose rows differ in width would shear the whole word after it.
    for (const [ch, [top, bottom]] of Object.entries(BLOCK_GLYPHS)) {
      expect(top.length, `glyph ${ch} rows differ in width`).toBe(bottom.length);
    }
  });
});

describe('<Wordmark>', () => {
  it('exposes the word, not the block characters, to assistive tech', () => {
    render(<Wordmark text="retro" />);
    // Without this the screen reader announces a run of U+2588s.
    expect(screen.getByRole('img', { name: 'retro' })).toBeTruthy();
  });

  it('takes an explicit label when the word is not the whole message', () => {
    render(<Wordmark text="retro" label="Sprint retrospective" />);
    expect(screen.getByRole('img', { name: 'Sprint retrospective' })).toBeTruthy();
  });

  it('renders the glyphs as real selectable text', () => {
    // The point of the block font over an image: it is characters, so it is
    // selectable, findable and scales with the type scale. Shade cells are
    // blanked for display (see below), so compare against that form.
    const expected = (WORDMARK_SAMPLES['retro'] as readonly [string, string])
      .map((row) => row.replace(/░/g, ' '))
      .join('\n');
    const { container } = render(<Wordmark text="retro" />);
    expect(container.querySelector('pre')?.textContent).toBe(expected);
  });

  it('blanks the shade cells but keeps the letter shape', () => {
    // `░` is the font's background cell. A terminal draws it dim; a <pre>
    // cannot, so it would paint at full accent weight and read as damage —
    // and only on the letters that use it, which in "yeaboi" is the Y alone.
    const { container } = render(<Wordmark text="yeaboi" />);
    const text = container.querySelector('pre')?.textContent ?? '';
    expect(text).not.toContain('░');
    // Same width, so the two rows still line up and the Y keeps its stem.
    const [top, bottom] = text.split('\n');
    expect(top?.length).toBe(WORDMARK_SAMPLES['yeaboi']?.[0].length);
    expect(bottom).toContain('█');
  });
});
