"""Regenerate the frozen mascot sprite layers from the website art.

Dev tool — NOT imported at runtime (keeps Pillow out of the shipped app).
Run from the repo root:  uv run python scripts/gen_mascot_sprites.py
"""

from pathlib import Path

from PIL import Image

# Letter -> rgb. MUST stay identical to MASCOT_PALETTE in _mascot.py.
PALETTE = {
    "k": (9, 14, 18),  # outline
    "o": (26, 32, 40),  # sunglass lens
    "G": (34, 158, 122),  # head green
    "g": (22, 110, 92),  # head green shadow
    "W": (232, 240, 238),  # glint / belly white
    "L": (150, 190, 190),  # body light blue-grey
    "M": (96, 140, 144),  # body mid blue-grey
    "S": (60, 100, 108),  # body shadow
    "b": (250, 176, 44),  # bill / feet
    "r": (228, 104, 22),  # orange shadow
}
LETTERS = list(PALETTE)
RGBS = [PALETTE[c] for c in LETTERS]
WIDTH = 34
ASSETS = Path("docs/assets")
OUT = Path("src/yeaboi/ui/shared/_mascot_sprites.py")


def nearest(r, g, b):
    return LETTERS[
        min(range(len(RGBS)), key=lambda i: (RGBS[i][0] - r) ** 2 + (RGBS[i][1] - g) ** 2 + (RGBS[i][2] - b) ** 2)
    ]


def despeckle(grid, min_size=3):
    """Drop connected islands smaller than min_size (8-connectivity)."""
    h = len(grid)
    w = len(grid[0])
    seen = [[False] * w for _ in range(h)]
    keep = [[False] * w for _ in range(h)]
    for sy in range(h):
        for sx in range(w):
            if grid[sy][sx] == "." or seen[sy][sx]:
                continue
            stack = [(sx, sy)]
            comp = []
            seen[sy][sx] = True
            while stack:
                x, y = stack.pop()
                comp.append((x, y))
                for dx in (-1, 0, 1):
                    for dy in (-1, 0, 1):
                        nx, ny = x + dx, y + dy
                        if 0 <= nx < w and 0 <= ny < h and not seen[ny][nx] and grid[ny][nx] != ".":
                            seen[ny][nx] = True
                            stack.append((nx, ny))
            if len(comp) >= min_size:
                for x, y in comp:
                    keep[y][x] = True
    return ["".join(grid[y][x] if keep[y][x] else "." for x in range(w)) for y in range(h)]


def trace(name):
    im = Image.open(ASSETS / f"{name}.png").convert("RGBA").transpose(Image.FLIP_LEFT_RIGHT)
    w, h = im.size
    height = round(WIDTH * h / w)
    if height % 2:
        height += 1
    # Flatten (snap to palette) FIRST, then NEAREST downscale so blocks stay solid.
    src = im.load()
    flat = Image.new("RGBA", (w, h))
    fp = flat.load()
    for y in range(h):
        for x in range(w):
            r, g, b, a = src[x, y]
            fp[x, y] = (*PALETTE[nearest(r, g, b)], 255) if a >= 128 else (0, 0, 0, 0)
    small = flat.resize((WIDTH, height), Image.NEAREST).load()
    grid = []
    for y in range(height):
        grid.append("".join(nearest(*small[x, y][:3]) if small[x, y][3] >= 128 else "." for x in range(WIDTH)))
    return despeckle(grid)


def emit(name, grid):
    body = ",\n    ".join(f'"{row}"' for row in grid)
    return f"{name} = (\n    {body},\n)\n"


def main():
    parts = ["# AUTO-GENERATED by scripts/gen_mascot_sprites.py — do not edit by hand.\n\n"]
    for const, asset in (("DUCK_BASE", "duck-base"), ("DUCK_WING", "duck-wing"), ("DUCK_GLASSES", "duck-glasses")):
        parts.append(emit(const, trace(asset)))
        parts.append("\n")
    OUT.write_text("".join(parts))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
