"""The mode vocabulary every browser surface brands itself from.

Three things used to be spread across the exporters, the boards and the gate:
which accent a mode wears, what word its masthead is set in, and how the chrome
dict that carries both is assembled. This is the one place that knows.

A leaf — it imports nothing from ``yeaboi`` — so ``html_theme``, ``retro.page``,
``poker.page`` and ``sharing.gate`` can all import it at module scope with no
cycle.

# See docs: "Architecture" — the four layers; this is presentation vocabulary,
# not domain state
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

# Human names for the eight modes that can be behind a share. Used for a tab
# title, and nothing else — see ``GATE_BRANDED_MODES`` for the one place where
# the choice of words has a consequence.
MODE_LABELS: dict[str, str] = {
    "standup": "Daily Standup",
    "retro": "Retro",
    "poker": "Planning Poker",
    "reporting": "Delivery Report",
    "planning": "Sprint Plan",
    "analysis": "Team Profile",
    "performance": "Performance",
    "roadmap": "Roadmap",
}

# The short word each mode's masthead is set in. Kept separate from the label
# because the display face is a grid of block glyphs roughly three columns per
# letter: "Delivery Report" does not fit anywhere, "report" does.
MODE_WORDMARKS: dict[str, str] = {
    "standup": "standup",
    "retro": "retro",
    "poker": "poker",
    "reporting": "report",
    "planning": "plan",
    "analysis": "team",
    "performance": "review",
    "roadmap": "roadmap",
}

# What the gate says a visitor is being invited to.
#
# Spelled out rather than derived from the label or the wordmark, because
# deriving it produces English nobody would write: the wordmark gives
# "Someone shared a team with you" and the label gives "a Planning Poker".
# Eight strings of user-facing copy are worth eight strings.
MODE_SHARE_PHRASES: dict[str, str] = {
    "standup": "a standup",
    "retro": "a retro",
    "poker": "a planning poker session",
    "reporting": "a delivery report",
    "planning": "a sprint plan",
    "analysis": "a team profile",
    "performance": "a performance artifact",
    "roadmap": "a roadmap",
}

# Modes that own a ``[data-mode]`` accent in frontend/src/design/tokens.css.
# Every entry here must have both a dark and a light rendition there;
# ``test_every_mode_accent_has_a_light_rendition`` enforces that side.
_ACCENT_MODES = frozenset(
    {"retro", "poker", "analysis", "usage", "reporting", "standup", "planning", "performance", "ship"}
)

# Modes with no accent of their own, and whose accent they borrow. This was
# copy-pasted into roadmap/export.py and anonymize/export.py, which is exactly
# how the gate ended up with no accent at all: there was nowhere to look it up.
_BORROWED_ACCENTS: dict[str, str] = {
    "roadmap": "planning",
    "anonymize": "analysis",
}

# Which modes may name themselves on the *unauthenticated* gate.
#
# The gate is reachable by anyone holding the tunnel URL, so whatever it says is
# said to a stranger. One word from a fixed vocabulary is a fair trade for a
# visitor knowing what they are being asked to join — except for `performance`,
# where the word itself is the disclosure: "somebody's 1:1 or six-month review
# is behind this door" tells a stranger something real about a named colleague
# in a way that "a retro" does not. That gate stays neutral.
GATE_BRANDED_MODES: frozenset[str] = frozenset(MODE_LABELS) - {"performance"}


#: The byline every surface carries. One string, because five surfaces render
#: it and a sixth (the gate) used to hardcode its own copy in TypeScript.
DEFAULT_FOOTER = "Generated by yeaboi.ai"


def frame_title(mode: str) -> str:
    """Return the terminal frame's title bar for ``mode``.

    The one place that spells this. It had three copies — ``build_chrome``, the
    gate's boot island and retro's ``App.tsx`` — which is fine until the format
    changes in one of them.
    """
    return f"yeaboi — {mode}" if mode else "yeaboi"


def accent_mode(mode: str) -> str:
    """Return the ``[data-mode]`` value ``mode`` should wear, or ``""``.

    Not every surface owns a distinct accent, so this names the accent to wear
    rather than the authoring mode. Unknown input returns ``""`` — callers
    interpolate the result into an HTML attribute, so this doubles as the
    allowlist that makes escaping unnecessary.
    """
    if mode in _ACCENT_MODES:
        return mode
    return _BORROWED_ACCENTS.get(mode, "")


def build_chrome(
    *,
    mode: str,
    title: str,
    wordmark: str,
    subtitle: str = "",
    facts: Sequence[tuple[str, str]] = (),
    badges: Sequence[str] = (),
    nav: Sequence[tuple[str, str]] = (),
    footer: str = "",
) -> dict[str, object]:
    """Build the chrome payload a page's masthead and footer are drawn from.

    The shape is mirrored by ``PageChrome`` in ``frontend/src/shared/chrome.ts``
    and pinned by the wire-shape guard, so a field dropped here fails
    ``npm run typecheck`` rather than blanking a masthead months later.

    Optional keys are *omitted* rather than emitted empty. That is load-bearing
    for the fixtures: an empty ``facts`` array and an absent one render the same
    but are different bytes, and the exports are compared byte-for-byte.

    Args:
        mode: The accent to wear — pass it through :func:`accent_mode` first if
            it might be an authoring mode rather than an accent mode.
        title: The page ``<h1>``.
        wordmark: The word set in the display face. Keep it short.
        subtitle: Muted line under the title.
        facts: Header eyebrows as ``(label, value)``. Values that are empty are
            dropped, so a caller can pass an optional fact unconditionally.
        badges: Accent eyebrows with no value.
        nav: ``(section_id, label)`` contents links.
        footer: Footer line. Defaults to the standard credit.
    """
    chrome: dict[str, object] = {
        "mode": mode,
        "frame": frame_title(mode),
        "wordmark": wordmark,
        "title": title,
        "footer": footer or DEFAULT_FOOTER,
    }
    if subtitle:
        chrome["subtitle"] = subtitle
    if facts:
        # Note the asymmetry, which is deliberate and pinned by the fixtures:
        # a caller passing no facts at all omits the key, but a caller passing
        # facts that are *all* empty gets an empty list. The first is "this
        # page has no facts row", the second is "it has one and today it is
        # blank" — and only the caller knows which.
        chrome["facts"] = [[label, value] for label, value in facts if value]
    if badges:
        chrome["badges"] = list(badges)
    if nav:
        chrome["nav"] = [[id_, label] for id_, label in nav]
    return chrome


def is_chrome(value: Mapping[str, object]) -> bool:
    """True if ``value`` has the five keys every chrome payload carries."""
    return {"mode", "frame", "wordmark", "title", "footer"} <= set(value)
