"""Export a PokerReport to Markdown and self-contained HTML.

Mirrors the retro exporter (retro/export.py): readable artifacts written under
``~/.yeaboi/exports/poker/<project>/`` so a session's outcome persists as a
shareable document, not just on the tracker. The TUI **Export** button writes
the current session on demand; the page loop also writes one at close.

Ticket text and voter names are attacker-influenced (tracker content + LAN
participants), so the HTML escapes every field with ``html.escape`` — the same
defense the retro exporter uses. The HTML uses the shared design system
(``html_theme``) so poker pages look consistent with the rest of the app.

# See docs: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import logging
import re
from collections.abc import Sequence
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import PokerReport, PokerTicketResult
from yeaboi.html_theme import escape as _e

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "poker"


def _title(report: PokerReport) -> str:
    scope = f" — {report.scope_label}" if report.scope_label else ""
    return f"Planning Poker{scope}"


def _pts(value: float | None) -> str:
    """Render a points value ("—" for none, ints without the trailing .0)."""
    if value is None:
        return "—"
    return str(int(value)) if float(value) == int(value) else str(value)


def _votes_str(ticket: PokerTicketResult) -> str:
    """Render the accepted votes as ``Alex 5 · Sam 8`` (empty if none)."""
    return " · ".join(f"{v.voter} {v.value}" for v in ticket.votes if v.value)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_poker_markdown(report: PokerReport) -> str:
    """Return the poker session as a Markdown document."""
    from yeaboi.markdown_convert import md_table_cell as _cell

    estimated = sum(1 for t in report.tickets if t.estimated)
    lines: list[str] = [
        f"# {_title(report)}",
        "",
        f"**Date:** {report.date}  ",
        f"**Source:** {report.source or '—'} · {report.scope_label or '—'}  ",
        f"**Estimated:** {estimated}/{len(report.tickets)} tickets  ",
        f"**Participants:** {', '.join(report.participants) if report.participants else '—'}",
        "",
        "| Ticket | Summary | Before | Final | Votes |",
        "|--------|---------|--------|-------|-------|",
    ]
    for t in report.tickets:
        key = f"[{t.key}]({t.url})" if t.url else t.key
        final = _pts(t.final_points) if t.estimated else "_skipped_"
        votes = _votes_str(t) or "—"
        lines.append(f"| {key} | {_cell(t.summary)} | {_pts(t.initial_points)} | {final} | {_cell(votes)} |")
    lines.append("")

    ai_notes = [(t.key, t.ai_note) for t in report.tickets if t.ai_note]
    if ai_notes:
        lines += ["## AI perspectives", ""]
        for key, note in ai_notes:
            lines.append(f"- **{key}** — {_cell(note)}")
        lines.append("")

    duels = [t for t in report.tickets if t.duel_transcript]
    if duels:
        lines += ["## Duels", ""]
        for t in duels:
            lines.append(f"**{t.key}** — {t.duel_low} vs {t.duel_high}")
            lines.append("")
            lines += [f"> {line}" for line in t.duel_transcript.splitlines()]
            lines.append("")

    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines += ["---", "", f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {ts}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def _estimation_sparkline(report: PokerReport, history: Sequence[dict], estimated: int) -> str:
    """Estimated-tickets trend across this session's past poker runs, or ""."""
    from yeaboi.html_theme import history_series, sparkline_card

    points = history_series(
        history,
        date_key="poker_date",
        value_key="estimated_count",
        cutoff_date=report.date,
        current=(report.date, estimated),
    )
    return sparkline_card(
        points,
        title="Estimation trend",
        svg_title=f"Tickets estimated — last {len(points)} sessions",
    )


def _votes_html(ticket: PokerTicketResult) -> str:
    """Accepted votes as avatar + value pairs (falls back to a dash)."""
    from yeaboi.html_theme import avatar

    votes = [v for v in ticket.votes if v.value]
    if not votes:
        return "&mdash;"
    return "".join(
        f"<span style='display:inline-flex;align-items:center;gap:.3rem;margin-right:.6rem;white-space:nowrap'>"
        f"{avatar(v.voter)}{_e(str(v.value))}</span>"
        for v in votes
    )


def build_poker_html(report: PokerReport, *, history: Sequence[dict] = ()) -> str:
    """Return the poker session as a self-contained HTML document (shared design system).

    ``history`` is optional ``PokerStore.get_history`` rows (newest-first); with
    two or more sessions it powers the estimation-trend sparkline.
    """
    from yeaboi.html_theme import avatar, html_page, legend, section, segment_bar, stat_tile

    estimated = sum(1 for t in report.tickets if t.estimated)
    skipped = len(report.tickets) - estimated

    # Overview: stat tiles + estimated/skipped split + trend + participants.
    tiles = [
        stat_tile(str(len(report.tickets)), "Tickets"),
        stat_tile(str(estimated), "Estimated"),
        stat_tile(str(len(report.participants)), "Participants"),
    ]
    overview: list[str] = [f"<div class='stat-grid'>{''.join(tiles)}</div>"]
    if report.tickets:
        split_bar = segment_bar(
            [(estimated, "--ok"), (skipped, "--muted")],
            title=f"{estimated} of {len(report.tickets)} tickets estimated",
        )
        key = legend([(f"Estimated {estimated}", "--ok"), (f"Skipped {skipped}", "--muted")])
        overview.append(f"<div style='margin-bottom:.6rem'>{split_bar}{key}</div>")
    overview.append(_estimation_sparkline(report, history, estimated))
    if report.participants:
        people = "".join(
            f"<span style='display:inline-flex;align-items:center;gap:.35rem;margin-right:.8rem'>"
            f"{avatar(name)}{_e(name)}</span>"
            for name in report.participants
        )
        overview.append(
            f"<p style='display:flex;flex-wrap:wrap;align-items:center;gap:.3rem'>"
            f"<strong>Participants:</strong> {people}</p>"
        )
    parts: list[str] = [section("overview", "Overview", "".join(overview))]

    # Tickets: tabular data stays a table; keys become badge chips, votes get avatars.
    rows = [
        "<table class='data-table'><thead>"
        "<tr><th>Ticket</th><th>Summary</th><th>Before</th><th>Final</th><th>Votes</th></tr></thead><tbody>"
    ]
    for t in report.tickets:
        if t.url:
            key = f"<a class='badge' href='{_e(t.url, quote=True)}' target='_blank' rel='noopener'>{_e(t.key)}</a>"
        else:
            key = _e(t.key)
        final = _e(_pts(t.final_points)) if t.estimated else "<em style='color:var(--muted)'>skipped</em>"
        rows.append(
            f"<tr><td>{key}</td><td>{_e(t.summary)}</td>"
            f"<td>{_e(_pts(t.initial_points))}</td><td>{final}</td><td>{_votes_html(t)}</td></tr>"
        )
    rows.append("</tbody></table>")
    parts.append(section("tickets", "Tickets", "".join(rows)))

    ai_notes = [(t.key, t.ai_note) for t in report.tickets if t.ai_note]
    if ai_notes:
        from yeaboi.html_theme import prose_bullets

        blocks: list[str] = []
        for key, note in ai_notes:
            lis = "".join(f"<li>{_e(fragment)}</li>" for fragment in prose_bullets(note)) or f"<li>{_e(note)}</li>"
            blocks.append(f"<div class='analysis-section'><h3>{_e(key)}</h3><ul>{lis}</ul></div>")
        parts.append(
            section("ai", "AI perspectives", f"<div class='analysis-grid member-grid'>{''.join(blocks)}</div>")
        )

    duels = [t for t in report.tickets if t.duel_transcript]
    if duels:
        duel_parts: list[str] = []
        for t in duels:
            duel_parts.append(f"<p><strong>{_e(t.key)}</strong> &mdash; {_e(t.duel_low)} vs {_e(t.duel_high)}</p>")
            duel_parts.append(f"<pre style='white-space:pre-wrap'>{_e(t.duel_transcript)}</pre>")
        parts.append(section("duels", "Duels", "".join(duel_parts)))

    nav: list[tuple[str, str]] = [("overview", "Overview"), ("tickets", "Tickets")]
    if ai_notes:
        nav.append(("ai", "AI perspectives"))
    if duels:
        nav.append(("duels", "Duels"))

    meta = [f"{report.source or '—'} · {report.scope_label or '—'}", f"{estimated}/{len(report.tickets)} estimated"]
    return html_page(
        title=f"{_title(report)} — {report.date}",
        heading=_title(report),
        subtitle=report.date,
        meta=meta,
        nav=nav,
        body="".join(parts),
        footer_note=f"Generated by yeaboi.ai • {datetime.now().strftime('%Y-%m-%d')}",
    )


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------


def export_poker(report: PokerReport, *, project_name: str = "", history: Sequence[dict] = ()) -> dict[str, Path]:
    """Write the poker session as Markdown + HTML under the poker export dir.

    Returns ``{"markdown": Path, "html": Path}``. One file per day (dated
    filename) — a re-run the same day overwrites so the latest wins.
    ``history`` (PokerStore.get_history rows) feeds the HTML trend chart.
    """
    from yeaboi.paths import get_poker_export_dir

    key = _slug(project_name or report.project_name or report.session_id)
    out_dir = get_poker_export_dir(key)
    stem = f"poker-{report.date or 'latest'}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(build_poker_markdown(report), encoding="utf-8")
    html_path.write_text(build_poker_html(report, history=history), encoding="utf-8")
    logger.info("Poker session exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
