"""Export a PokerReport to Markdown and self-contained HTML.

Mirrors the retro exporter (retro/export.py): readable artifacts written under
``~/.yeaboi/exports/poker/<project>/`` so a session's outcome persists as a
shareable document, not just on the tracker. The TUI **Export** button writes
the current session on demand; the page loop also writes one at close.

Ticket text and voter names are attacker-influenced (tracker content + LAN
participants), so the HTML escapes every field with ``html.escape`` — the same
defense the retro exporter uses. The HTML reuses the plan report's stylesheet
(``html_exporter._CSS``) so poker pages look consistent with the rest of the app.

# See docs: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import PokerReport, PokerTicketResult
from yeaboi.html_theme import escape as _e

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "poker"


def _title(report: PokerReport) -> str:
    scope = f" — {report.scope_label}" if report.scope_label else ""
    return f"Planning Poker{scope}"


def _pts(value: float | None) -> str:
    """Render a points value ("—" for none, ints without the trailing .0)."""
    if value is None:
        return "—"
    return str(int(value)) if float(value) == int(value) else str(value)


def _votes_str(ticket: PokerTicketResult) -> str:
    """Render the accepted votes as ``Alex 5 · Sam 8`` (empty if none)."""
    return " · ".join(f"{v.voter} {v.value}" for v in ticket.votes if v.value)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_poker_markdown(report: PokerReport) -> str:
    """Return the poker session as a Markdown document."""
    from yeaboi.markdown_convert import md_table_cell as _cell

    estimated = sum(1 for t in report.tickets if t.estimated)
    lines: list[str] = [
        f"# {_title(report)}",
        "",
        f"**Date:** {report.date}  ",
        f"**Source:** {report.source or '—'} · {report.scope_label or '—'}  ",
        f"**Estimated:** {estimated}/{len(report.tickets)} tickets  ",
        f"**Participants:** {', '.join(report.participants) if report.participants else '—'}",
        "",
        "| Ticket | Summary | Before | Final | Votes |",
        "|--------|---------|--------|-------|-------|",
    ]
    for t in report.tickets:
        key = f"[{t.key}]({t.url})" if t.url else t.key
        final = _pts(t.final_points) if t.estimated else "_skipped_"
        votes = _votes_str(t) or "—"
        lines.append(f"| {key} | {_cell(t.summary)} | {_pts(t.initial_points)} | {final} | {_cell(votes)} |")
    lines.append("")

    ai_notes = [(t.key, t.ai_note) for t in report.tickets if t.ai_note]
    if ai_notes:
        lines += ["## AI perspectives", ""]
        for key, note in ai_notes:
            lines.append(f"- **{key}** — {_cell(note)}")
        lines.append("")

    duels = [t for t in report.tickets if t.duel_transcript]
    if duels:
        lines += ["## Duels", ""]
        for t in duels:
            lines.append(f"**{t.key}** — {t.duel_low} vs {t.duel_high}")
            lines.append("")
            lines += [f"> {line}" for line in t.duel_transcript.splitlines()]
            lines.append("")

    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines += ["---", "", f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {ts}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def build_poker_html(report: PokerReport) -> str:
    """Return the poker session as a self-contained HTML document (reuses the plan CSS)."""
    from yeaboi.html_exporter import _CSS

    estimated = sum(1 for t in report.tickets if t.estimated)
    date_span = f"<span style='color:var(--text-muted);font-weight:400'>&mdash; {_e(report.date)}</span>"
    parts: list[str] = [
        '<div class="container">',
        f"<h1>{_e(_title(report))} {date_span}</h1>",
        (
            f"<p><strong>Source:</strong> {_e(report.source or '—')} · {_e(report.scope_label or '—')}"
            f" &nbsp;·&nbsp; <strong>Estimated:</strong> {estimated}/{len(report.tickets)}"
            "<br><strong>Participants:</strong> "
            f"{_e(', '.join(report.participants)) if report.participants else '&mdash;'}</p>"
        ),
        "<table><thead><tr><th>Ticket</th><th>Summary</th><th>Before</th><th>Final</th><th>Votes</th></tr></thead>",
        "<tbody>",
    ]
    for t in report.tickets:
        key = f"<a href='{_e(t.url)}'>{_e(t.key)}</a>" if t.url else _e(t.key)
        final = _e(_pts(t.final_points)) if t.estimated else "<em style='color:var(--text-muted)'>skipped</em>"
        votes = _e(_votes_str(t)) or "&mdash;"
        parts.append(
            f"<tr><td>{key}</td><td>{_e(t.summary)}</td>"
            f"<td>{_e(_pts(t.initial_points))}</td><td>{final}</td><td>{votes}</td></tr>"
        )
    parts.append("</tbody></table>")

    ai_notes = [(t.key, t.ai_note) for t in report.tickets if t.ai_note]
    if ai_notes:
        parts.append("<h2>AI perspectives</h2><ul style='margin:0;padding-left:1.1rem'>")
        for key, note in ai_notes:
            parts.append(f"<li><strong>{_e(key)}</strong> &mdash; {_e(note)}</li>")
        parts.append("</ul>")

    duels = [t for t in report.tickets if t.duel_transcript]
    if duels:
        parts.append("<h2>Duels</h2>")
        for t in duels:
            parts.append(f"<p><strong>{_e(t.key)}</strong> &mdash; {_e(t.duel_low)} vs {_e(t.duel_high)}</p>")
            parts.append(f"<pre style='white-space:pre-wrap'>{_e(t.duel_transcript)}</pre>")

    parts.append("</div>")  # container
    body = "".join(parts)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{_e(_title(report))} — {_e(report.date)}</title>
  <style>{_CSS}</style>
</head>
<body>
{body}
<footer class="site-footer">
  Generated by yeaboi.ai &bull; {_e(datetime.now().strftime("%Y-%m-%d"))}
</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------


def export_poker(report: PokerReport, *, project_name: str = "") -> dict[str, Path]:
    """Write the poker session as Markdown + HTML under the poker export dir.

    Returns ``{"markdown": Path, "html": Path}``. One file per day (dated
    filename) — a re-run the same day overwrites so the latest wins.
    """
    from yeaboi.paths import get_poker_export_dir

    key = _slug(project_name or report.project_name or report.session_id)
    out_dir = get_poker_export_dir(key)
    stem = f"poker-{report.date or 'latest'}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(build_poker_markdown(report), encoding="utf-8")
    html_path.write_text(build_poker_html(report), encoding="utf-8")
    logger.info("Poker session exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
