"""Export a PokerReport to Markdown and self-contained HTML.

Mirrors the retro exporter (retro/export.py): readable artifacts written under
``~/.yeaboi/exports/poker/<project>/`` so a session's outcome persists as a
shareable document, not just on the tracker. The TUI **Export** button writes
the current session on demand; the page loop also writes one at close.

Ticket text and voter names are attacker-influenced (tracker content + LAN
participants). The Markdown builder still escapes by hand, because Markdown has
no structural defense; the HTML no longer needs one — it carries the session as
a JSON payload that ``frontend/src/export`` draws, and a React text child cannot
become markup however it is spelled.

# See docs: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import json
import logging
import re
from collections.abc import Sequence
from dataclasses import asdict
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import PokerReport, PokerTicketResult
from yeaboi.html_theme import safe_url

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "poker"


def _title(report: PokerReport) -> str:
    scope = f" — {report.scope_label}" if report.scope_label else ""
    return f"Planning Poker{scope}"


def _stem(report: PokerReport) -> str:
    """The filename stem both artifacts share.

    Shared so the HTML's ``<noscript>`` note can name the Markdown file sitting
    beside it. Guessing that name in two places is exactly how the note ends up
    pointing at a file nobody wrote.
    """
    return f"poker-{report.date or 'latest'}"


def _pts(value: float | None) -> str:
    """Render a points value ("—" for none, ints without the trailing .0)."""
    if value is None:
        return "—"
    return str(int(value)) if float(value) == int(value) else str(value)


def _votes_str(ticket: PokerTicketResult) -> str:
    """Render the accepted votes as ``Alex 5 · Sam 8`` (empty if none)."""
    return " · ".join(f"{v.voter} {v.value}" for v in ticket.votes if v.value)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_poker_markdown(report: PokerReport, *, generated_ts: str = "") -> str:
    """Return the poker session as a Markdown document.

    ``generated_ts`` pins the footer timestamp; empty means "now". The seam
    hoists it into :func:`build_poker_export_inputs` so the sidecar and the
    reference implementation render the same bytes from the same document.
    """
    from yeaboi.markdown_convert import md_table_cell as _cell

    estimated = sum(1 for t in report.tickets if t.estimated)
    lines: list[str] = [
        f"# {_title(report)}",
        "",
        f"**Date:** {report.date}  ",
        f"**Source:** {report.source or '—'} · {report.scope_label or '—'}  ",
        f"**Estimated:** {estimated}/{len(report.tickets)} tickets  ",
        f"**Participants:** {', '.join(report.participants) if report.participants else '—'}",
        "",
        "| Ticket | Summary | Before | Final | Votes |",
        "|--------|---------|--------|-------|-------|",
    ]
    for t in report.tickets:
        # safe_url: tracker URLs are attacker-influenced, and a Markdown link
        # becomes an <a href> downstream (Notion/Confluence/GitHub).
        key = f"[{t.key}]({safe})" if (safe := safe_url(t.url)) else t.key
        final = _pts(t.final_points) if t.estimated else "_skipped_"
        votes = _votes_str(t) or "—"
        lines.append(f"| {key} | {_cell(t.summary)} | {_pts(t.initial_points)} | {final} | {_cell(votes)} |")
    lines.append("")

    ai_notes = [(t.key, t.ai_note) for t in report.tickets if t.ai_note]
    if ai_notes:
        lines += ["## AI perspectives", ""]
        for key, note in ai_notes:
            lines.append(f"- **{key}** — {_cell(note)}")
        lines.append("")

    duels = [t for t in report.tickets if t.duel_transcript]
    if duels:
        lines += ["## Duels", ""]
        for t in duels:
            lines.append(f"**{t.key}** — {t.duel_low} vs {t.duel_high}")
            lines.append("")
            lines += [f"> {line}" for line in t.duel_transcript.splitlines()]
            lines.append("")

    ts = generated_ts or datetime.now().strftime("%Y-%m-%d %H:%M")
    lines += ["---", "", f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {ts}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def _ticket_payload(ticket: PokerTicketResult) -> dict:
    """One ticket as data: what it was worth before, what the room said, who said it.

    ``final`` is ``None`` whenever the room skipped the ticket, even if a stale
    ``final_points`` survived on the record — a number beside "skipped" is a
    contradiction, and the bundle would have to pick one to believe.
    """
    out: dict = {
        "key": ticket.key,
        "summary": ticket.summary,
        "before": ticket.initial_points,
        "final": ticket.final_points if ticket.estimated else None,
        "estimated": bool(ticket.estimated),
        "votes": [{"voter": v.voter, "value": str(v.value)} for v in ticket.votes if v.value],
    }
    # safe_url here, not in the bundle's `safeUrl`, only because the tracker URL
    # is also what the Markdown twin links — one allowlist, both artifacts.
    if safe := safe_url(ticket.url):
        out["url"] = safe
    if ticket.ai_note:
        out["aiNote"] = ticket.ai_note
    if ticket.duel_transcript:
        out["duel"] = {"low": ticket.duel_low, "high": ticket.duel_high, "transcript": ticket.duel_transcript}
    return out


def poker_export_args(
    report: PokerReport, *, history: Sequence[dict] = (), generated_date: str = ""
) -> dict[str, object]:
    """Return the chrome + payload keyword arguments for one poker document.

    Split out to match :func:`yeaboi.retro.export.retro_export_args`: the seam
    returns these args rather than a page, so the sidecar can build the payload
    while Python keeps rendering the HTML shell around it. ``generated_date``
    pins the footer date (empty means "now"). Poker has no editable share, so
    there is no ``editable`` flag here.
    """
    from yeaboi.html_theme import trend

    estimated = sum(1 for t in report.tickets if t.estimated)
    tickets = [_ticket_payload(t) for t in report.tickets]

    # The contents links are built here because the shell renders before the
    # report does; which sections exist is a fact about the payload either way.
    nav: list[tuple[str, str]] = [("overview", "Overview"), ("tickets", "Tickets")]
    if any(t.get("aiNote") for t in tickets):
        nav.append(("ai", "AI perspectives"))
    if any(t.get("duel") for t in tickets):
        nav.append(("duels", "Duels"))

    return dict(
        mode="poker",
        title=_title(report),
        wordmark="poker",
        facts=[
            ("SOURCE", report.source or ""),
            ("SCOPE", report.scope_label or ""),
            ("DATE", report.date or ""),
            ("ESTIMATED", f"{estimated}/{len(report.tickets)}"),
        ],
        nav=nav,
        report={
            "kind": "poker",
            "tickets": tickets,
            "participants": list(report.participants),
            "trend": trend(
                history,
                date_key="poker_date",
                value_key="estimated_count",
                title="Estimation trend",
                label="Tickets estimated",
                cutoff_date=report.date,
                current=(report.date, estimated),
            ),
        },
        footer=f"Generated by yeaboi.ai • {generated_date or datetime.now().strftime('%Y-%m-%d')}",
    )


def build_poker_html(report: PokerReport, *, history: Sequence[dict] = ()) -> str:
    """Return the poker session as a self-contained HTML document.

    ``history`` is optional ``PokerStore.get_history`` rows (newest-first); with
    two or more sessions it powers the estimation-trend sparkline.
    """
    from yeaboi.html_theme import export_page

    doc = _export_doc(report, history=history)
    return export_page(**doc["args"], markdown_name=f"{_stem(report)}.md")


# ---------------------------------------------------------------------------
# The build-export seam — poker.build_export
# ---------------------------------------------------------------------------


def build_poker_export_inputs(report: PokerReport, *, history: Sequence[dict] = ()) -> dict:
    """Freeze one poker document into the ``poker.build_export`` wire params.

    A single ``datetime.now()`` capture hoists the seam's only nondeterminism
    into the params, and the json round-trip freezes the report into the same
    plain-JSON shape a stored one takes — so the sidecar and the reference
    implementation see byte-identical inputs.
    """
    now = datetime.now()
    return json.loads(
        json.dumps(
            {
                "report": asdict(report),
                "history": list(history),
                "generated_ts": now.strftime("%Y-%m-%d %H:%M"),
                "generated_date": now.strftime("%Y-%m-%d"),
            }
        )
    )


def build_poker_export(inputs: dict) -> dict:
    """Python reference implementation of ``poker.build_export``.

    Rebuilds the report through the store deserializer — the same round-trip a
    stored report takes — then renders with the wire-pinned timestamps. Key
    order is contractual: ``args`` is json.dumps-ed into the page boot payload.
    """
    from yeaboi.gocore.client import CONTRACT_VERSION
    from yeaboi.poker.store import report_from_dict

    report = report_from_dict(inputs["report"])
    return {
        "contract_version": CONTRACT_VERSION,
        "markdown": build_poker_markdown(report, generated_ts=inputs["generated_ts"]),
        "args": poker_export_args(report, history=inputs["history"], generated_date=inputs["generated_date"]),
    }


def _valid_poker_export(result: object, inputs: dict) -> bool:
    """Structural checks on a sidecar result — any failure means malformed → Python."""
    if not isinstance(result, dict):
        return False
    if not (isinstance(result.get("markdown"), str) and result["markdown"]):
        return False
    args = result.get("args")
    if not isinstance(args, dict):
        return False
    report = args.get("report")
    if not isinstance(report, dict) or report.get("kind") != "poker":
        return False
    # The ticket count is a structural fact the inputs already fix; a result
    # that disagrees would render a different session, not a slower one.
    tickets = report.get("tickets")
    return isinstance(tickets, list) and len(tickets) == len(inputs["report"].get("tickets") or ())


def go_build_poker_export(inputs: dict) -> dict | None:
    """``poker.build_export`` served by the sidecar, or None → Python computes."""
    client = _client()
    if client is None:
        return None
    from yeaboi.gocore import CoreError

    try:
        result = client.request("poker.build_export", inputs)
    except CoreError as exc:
        logger.warning("gocore: poker.build_export failed (%s) — falling back to Python", exc)
        return None
    if not _valid_poker_export(result, inputs):
        logger.warning("gocore: poker.build_export result malformed — falling back to Python")
        return None
    logger.info("gocore: poker.build_export served by the sidecar")
    return result


def _client():
    """The discovered sidecar client, or None; never raises (an export must not sink)."""
    try:
        from yeaboi import gocore

        return gocore.get_client()
    except Exception as exc:  # noqa: BLE001 — dispatch must never sink an export
        logger.warning("gocore: client unavailable (%s: %s) — using the Python path", type(exc).__name__, exc)
        return None


def _export_doc(report: PokerReport, *, history: Sequence[dict] = ()) -> dict:
    """One poker document — markdown + export args — sidecar-served when available."""
    inputs = build_poker_export_inputs(report, history=history)
    return go_build_poker_export(inputs) or build_poker_export(inputs)


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------


def export_poker(report: PokerReport, *, project_name: str = "", history: Sequence[dict] = ()) -> dict[str, Path]:
    """Write the poker session as Markdown + HTML under the poker export dir.

    Returns ``{"markdown": Path, "html": Path}``. One file per day (dated
    filename) — a re-run the same day overwrites so the latest wins.
    ``history`` (PokerStore.get_history rows) feeds the HTML trend chart.
    """
    from yeaboi.html_theme import export_page
    from yeaboi.paths import get_poker_export_dir

    key = _slug(project_name or report.project_name or report.session_id)
    out_dir = get_poker_export_dir(key)
    stem = _stem(report)
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    # One seam call renders both artifacts — the markdown and the HTML's args
    # come from the same dispatch, so the two files can never disagree about
    # which side (sidecar or Python) built them.
    doc = _export_doc(report, history=history)
    md_path.write_text(doc["markdown"], encoding="utf-8")
    html_path.write_text(export_page(**doc["args"], markdown_name=f"{stem}.md"), encoding="utf-8")
    logger.info("Poker session exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
