"""Unit tests for the Retro Markdown + HTML exporters.

The HTML is drawn by ``frontend/src/export`` from a JSON island, so these
assertions are about the *payload*. How an empty column becomes a footnote, and
which colour each column wears, are asserted in ``Retro.test.tsx``.
"""

import logging

from tests._pages import assert_self_contained, island
from yeaboi.agent.state import Annotation, RetroCard, RetroReport
from yeaboi.retro import export as retro_export
from yeaboi.retro.export import (
    build_retro_export,
    build_retro_export_inputs,
    build_retro_html,
    build_retro_markdown,
    export_retro,
    go_build_retro_export,
)


def _report():
    return RetroReport(
        date="2026-07-10",
        session_id="sess-1",
        project_name="Demo",
        sprint_name="Sprint 5",
        cards=(
            RetroCard(grid="went_well", text="fast deploys", author="Sam", origin="web"),
            RetroCard(
                grid="didnt_go_well",
                text="flaky tests",
                author="Rae",
                origin="web",
                reactions=(("👍", 3), ("🔥", 1)),
            ),
            RetroCard(grid="action_items", text="add retry guard", author="AI", origin="ai"),
        ),
        participants=("Sam", "Rae"),
    )


class TestMarkdown:
    def test_contains_headings_and_cards(self):
        md = build_retro_markdown(_report())
        assert "# Sprint Retro — Sprint 5" in md
        assert "## What went well" in md
        assert "fast deploys" in md
        assert "add retry guard" in md and "_(AI)_" in md

    def test_empty_grid_shows_placeholder(self):
        md = build_retro_markdown(RetroReport(date="2026-07-10"))
        assert "_No cards._" in md

    def test_reaction_counts_shown(self):
        md = build_retro_markdown(_report())
        assert "👍 3" in md and "🔥 1" in md

    def test_card_grids_are_tables(self):
        md = build_retro_markdown(_report())
        # Went well / didn't go well render as native tables with author + reactions.
        assert "| Card | By | Reactions |" in md
        assert "| fast deploys | Sam | — |" in md
        assert "| flaky tests | Rae | 👍 3  🔥 1 |" in md

    def test_action_items_are_checkboxes(self):
        md = build_retro_markdown(_report())
        assert "- [ ] add retry guard _(AI)_" in md

    def test_branded_footer(self):
        md = build_retro_markdown(_report())
        assert "🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)" in md


def _columns(html) -> dict:
    """The payload's columns, keyed by grid."""
    return {column["grid"]: column["cards"] for column in island(html)["report"]["columns"]}


class TestHtml:
    def test_self_contained_and_has_cards(self):
        html = build_retro_html(_report())
        assert "<!DOCTYPE html>" in html and "<style>" in html
        columns = _columns(html)
        assert columns["went_well"] == [{"text": "fast deploys", "reactions": [], "author": "Sam"}]
        assert columns["didnt_go_well"][0]["reactions"] == [["👍", 3], ["🔥", 1]]

    def test_every_column_ships_including_the_empty_ones(self):
        # Whether an empty column gets a card or a footnote is the bundle's
        # decision, so it has to be told the column exists.
        assert list(_columns(build_retro_html(_report()))) == [
            "went_well",
            "didnt_go_well",
            "action_items",
            "demos",
        ]
        assert _columns(build_retro_html(_report()))["demos"] == []

    def test_ai_cards_are_attributed_to_the_model_not_a_person(self):
        card = _columns(build_retro_html(_report()))["action_items"][0]
        assert card["ai"] is True
        assert "author" not in card  # the stored author on those rows is the literal "AI"

    def test_untrusted_text_travels_as_data_not_markup(self):
        rep = RetroReport(
            date="2026-07-10",
            cards=(RetroCard(grid="demos", text="<script>alert(1)</script>", author="<b>x</b>"),),
        )
        html = build_retro_html(rep)
        assert "<script>alert(1)</script>" not in html
        card = _columns(html)["demos"][0]
        assert card["text"] == "<script>alert(1)</script>"
        assert card["author"] == "<b>x</b>"

    def test_chrome_facts(self):
        boot = island(build_retro_html(_report()))
        assert boot["chrome"]["title"] == "Sprint Retro — Sprint 5"
        assert boot["chrome"]["wordmark"] == "retro"
        assert dict(tuple(f) for f in boot["chrome"]["facts"]) == {
            "DATE": "2026-07-10",
            "CARDS": "3",
            "PARTICIPANTS": "2",
        }

    def test_noscript_names_the_markdown_twin(self):
        assert "retro-2026-07-10.md" in build_retro_html(_report())

    def test_zero_reaction_counts_are_not_reactions(self):
        rep = RetroReport(
            date="2026-07-10",
            cards=(RetroCard(grid="demos", text="x", reactions=(("👍", 0), ("🔥", 2))),),
        )
        assert _columns(build_retro_html(rep))["demos"][0]["reactions"] == [["🔥", 2]]


def _report_with_carried():
    return RetroReport(
        date="2026-07-10",
        carried_action_items=(
            RetroCard(grid="action_items", text="ship the docs", status="done"),
            RetroCard(grid="action_items", text="keep <b>going</b>", status="carried_over"),
        ),
    )


class TestCarriedSection:
    def test_markdown_lists_carried_with_status_labels(self):
        md = build_retro_markdown(_report_with_carried())
        assert "Last sprint's action items — progress" in md
        assert "**[Done]** ship the docs" in md
        assert "**[Carried Over]** keep" in md

    def test_html_carries_status_keys_not_labels(self):
        # `CARRIED_STATUS_LABELS` is codegen'd into types/enums.ts from board.py;
        # sending the label too would let a stale bundle disagree with the server.
        carried = island(build_retro_html(_report_with_carried()))["report"]["carried"]
        assert carried == [
            {"status": "done", "text": "ship the docs"},
            {"status": "carried_over", "text": "keep <b>going</b>"},
        ]

    def test_html_defaults_a_missing_status(self):
        report = RetroReport(carried_action_items=(RetroCard(grid="action_items", text="x"),))
        assert island(build_retro_html(report))["report"]["carried"][0]["status"] == "pending"

    def test_no_carried_section_when_empty(self):
        md = build_retro_markdown(RetroReport(date="2026-07-10"))
        assert "Last sprint's action items — progress" not in md


class TestExportWrites:
    def test_writes_md_and_html(self, tmp_path, monkeypatch):
        # Redirect the export dir into tmp_path.
        target = tmp_path / "demo"

        def _fake_dir(key):
            target.mkdir(parents=True, exist_ok=True)
            return target

        monkeypatch.setattr("yeaboi.paths.get_retro_export_dir", _fake_dir)
        paths = export_retro(_report(), project_name="Demo")
        assert paths["markdown"].exists() and paths["html"].exists()
        assert paths["markdown"].read_text().startswith("# Sprint Retro")


class TestSharedDesignSystem:
    def test_retro_html_uses_shared_theme(self):
        html = build_retro_html(_report())
        assert 'data-theme="midnight"' in html
        assert 'data-mode="retro"' in html  # the accent, set before first paint
        assert_self_contained(html)


def _history(*rows):
    """Newest-first rows mirroring RetroStore.get_history output."""
    return [
        {"id": i, "run_at": f"{d}T18:00:00", "retro_date": d, "project_name": "Demo", "card_count": n}
        for i, (d, n) in enumerate(rows)
    ]


class TestTrend:
    def test_trend_from_history(self):
        history = _history(("2026-07-10", 3), ("2026-06-26", 8), ("2026-06-12", 6))
        trend = island(build_retro_html(_report(), history=history))["report"]["trend"]
        assert trend["title"] == "Card volume trend"
        assert trend["points"][0] == ["2026-06-12", 6]  # oldest first

    def test_no_history_no_trend(self):
        assert island(build_retro_html(_report()))["report"]["trend"] is None

    def test_future_history_rows_excluded(self):
        # Re-exporting an old retro must not draw retros held after it.
        history = _history(("2026-08-01", 9), ("2026-06-26", 8))
        trend = island(build_retro_html(_report(), history=history))["report"]["trend"]
        assert [day for day, _ in trend["points"]] == ["2026-06-26", "2026-07-10"]

    def test_export_writes_forward_history(self, tmp_path, monkeypatch):
        target = tmp_path / "demo"

        def _fake_dir(key):
            target.mkdir(parents=True, exist_ok=True)
            return target

        monkeypatch.setattr("yeaboi.paths.get_retro_export_dir", _fake_dir)
        history = _history(("2026-07-10", 3), ("2026-06-26", 8))
        paths = export_retro(_report(), project_name="Demo", history=history)
        assert island(paths["html"].read_text())["report"]["trend"] is not None

    def test_self_contained_with_history(self):
        html = build_retro_html(_report(), history=_history(("2026-07-10", 3), ("2026-06-26", 8)))
        assert_self_contained(html)


# ---------------------------------------------------------------------------
# The build-export seam
# ---------------------------------------------------------------------------


def _inputs(report=None, **kwargs):
    return build_retro_export_inputs(report if report is not None else _report(), **kwargs)


class TestExportInputs:
    def test_timestamps_are_captured_once_and_agree(self):
        inputs = _inputs()
        # Both stamps come from one datetime.now(); the date must be the ts's
        # own day, or a document could carry a footer from the day before.
        assert inputs["generated_ts"].startswith(inputs["generated_date"])

    def test_inputs_are_plain_json(self):
        # The json round-trip is what makes the wire params byte-identical to
        # what a stored report deserializes from — tuples become lists here.
        inputs = _inputs()
        assert inputs == __import__("json").loads(__import__("json").dumps(inputs))
        assert isinstance(inputs["report"]["cards"], list)
        assert inputs["report"]["cards"][1]["reactions"] == [["👍", 3], ["🔥", 1]]

    def test_editable_flag_travels(self):
        assert _inputs(editable=True)["editable"] is True
        assert _inputs()["editable"] is False

    def test_history_rows_travel_verbatim(self):
        history = _history(("2026-07-10", 3), ("2026-06-26", 8))
        assert _inputs(history=history)["history"] == history


class TestReferenceImplementation:
    def test_round_trip_reproduces_the_document(self):
        # The reference implementation rebuilds through the store deserializer;
        # what it renders must match rendering the report directly.
        report = _report()
        result = build_retro_export(_inputs(report))
        assert result["markdown"].splitlines()[0] == build_retro_markdown(report).splitlines()[0]
        assert result["args"]["report"]["kind"] == "retro"

    def test_pinned_timestamps_make_the_document_a_golden(self):
        inputs = {**_inputs(), "generated_ts": "2026-07-10 09:30", "generated_date": "2026-07-10"}
        first = build_retro_export(inputs)
        assert first == build_retro_export(inputs)  # deterministic, byte for byte
        assert "· 2026-07-10 09:30_" in first["markdown"]
        assert first["args"]["footer"] == "Generated by yeaboi.ai • 2026-07-10"

    def test_annotations_reach_the_payload(self):
        report = RetroReport(
            date="2026-07-10",
            annotations=(Annotation(kind="note", text="the deploy was rolled back", author="Rae"),),
        )
        result = build_retro_export(_inputs(report))
        assert result["args"]["report"]["annotations"][0]["text"] == "the deploy was rolled back"
        assert "the deploy was rolled back" in result["markdown"]

    def test_result_carries_the_contract_version(self):
        from yeaboi.gocore.client import CONTRACT_VERSION

        assert build_retro_export(_inputs())["contract_version"] == CONTRACT_VERSION

    def test_key_order_is_contractual(self):
        # `args` is json.dumps-ed into the page boot payload, so key order is
        # part of the wire, not a detail of this dict.
        result = build_retro_export(_inputs())
        assert list(result) == ["contract_version", "markdown", "args"]
        assert list(result["args"]["report"]) == ["kind", "columns", "participants", "carried", "trend"]


class TestGoDispatch:
    """retro.build_export dispatch: Go results win; any failure → Python."""

    def test_no_client_means_python_path(self, monkeypatch):
        monkeypatch.setattr("yeaboi.gocore.get_client", lambda: None)
        assert go_build_retro_export(_inputs()) is None

    def test_client_construction_failure_returns_none(self, monkeypatch):
        def boom():
            raise RuntimeError("discovery exploded")

        monkeypatch.setattr("yeaboi.gocore.get_client", boom)
        assert go_build_retro_export(_inputs()) is None

    def test_core_error_returns_none_for_fallback(self, monkeypatch):
        from yeaboi.gocore import CoreError

        class BrokenClient:
            def request(self, *args, **kwargs):
                raise CoreError("sidecar exploded")

        monkeypatch.setattr("yeaboi.gocore.get_client", lambda: BrokenClient())
        assert go_build_retro_export(_inputs()) is None

    def test_empty_markdown_is_malformed(self, monkeypatch):
        canned = build_retro_export(_inputs())

        class FakeClient:
            def request(self, method, params, on_progress=None, timeout=None):
                return {**canned, "markdown": ""}

        monkeypatch.setattr("yeaboi.gocore.get_client", lambda: FakeClient())
        assert go_build_retro_export(_inputs()) is None

    def test_wrong_report_kind_is_malformed(self, monkeypatch):
        canned = build_retro_export(_inputs())
        wrong = {**canned, "args": {**canned["args"], "report": {**canned["args"]["report"], "kind": "poker"}}}

        class FakeClient:
            def request(self, method, params, on_progress=None, timeout=None):
                return wrong

        monkeypatch.setattr("yeaboi.gocore.get_client", lambda: FakeClient())
        assert go_build_retro_export(_inputs()) is None

    def test_short_column_list_is_malformed(self, monkeypatch):
        # Every grid ships, including the empty ones — a short list would draw
        # a board missing a column.
        canned = build_retro_export(_inputs())
        report = {**canned["args"]["report"], "columns": canned["args"]["report"]["columns"][:2]}

        class FakeClient:
            def request(self, method, params, on_progress=None, timeout=None):
                return {**canned, "args": {**canned["args"], "report": report}}

        monkeypatch.setattr("yeaboi.gocore.get_client", lambda: FakeClient())
        assert go_build_retro_export(_inputs()) is None

    def test_carried_count_mismatch_is_malformed(self, monkeypatch):
        inputs = _inputs(_report_with_carried())
        canned = build_retro_export(inputs)
        report = {**canned["args"]["report"], "carried": canned["args"]["report"]["carried"][:1]}

        class FakeClient:
            def request(self, method, params, on_progress=None, timeout=None):
                return {**canned, "args": {**canned["args"], "report": report}}

        monkeypatch.setattr("yeaboi.gocore.get_client", lambda: FakeClient())
        assert go_build_retro_export(inputs) is None

    def test_good_results_are_returned_verbatim(self, monkeypatch, caplog):
        canned = build_retro_export(_inputs())

        class FakeClient:
            def request(self, method, params, on_progress=None, timeout=None):
                assert method == "retro.build_export"
                return canned

        monkeypatch.setattr("yeaboi.gocore.get_client", lambda: FakeClient())
        with caplog.at_level(logging.INFO, logger="yeaboi.retro.export"):
            assert go_build_retro_export(_inputs()) == canned
        assert "retro.build_export served by the sidecar" in caplog.text

    def test_the_page_renders_from_a_sidecar_document(self, monkeypatch):
        # The seam's whole point: a served document draws the same page.
        canned = build_retro_export(_inputs())

        class FakeClient:
            def request(self, method, params, on_progress=None, timeout=None):
                return canned

        monkeypatch.setattr("yeaboi.gocore.get_client", lambda: FakeClient())
        html = build_retro_html(_report())
        assert island(html)["report"]["columns"] == canned["args"]["report"]["columns"]

    def test_export_falls_back_without_a_sidecar(self, tmp_path, monkeypatch):
        # The Python path stays complete: no binary, both artifacts still written.
        target = tmp_path / "demo"
        monkeypatch.setattr("yeaboi.gocore.get_client", lambda: None)

        def _fake_dir(key):
            target.mkdir(parents=True, exist_ok=True)
            return target

        monkeypatch.setattr("yeaboi.paths.get_retro_export_dir", _fake_dir)
        paths = export_retro(_report(), project_name="Demo")
        assert paths["markdown"].read_text(encoding="utf-8").startswith("# Sprint Retro")
        assert "<!DOCTYPE html>" in paths["html"].read_text(encoding="utf-8")

    def test_both_artifacts_come_from_one_dispatch(self, tmp_path, monkeypatch):
        # One seam call per export — the .md and the .html can never disagree
        # about which side built them.
        calls = []
        target = tmp_path / "demo"

        def _counting(report, *, history=(), editable=False):
            calls.append(report)
            return build_retro_export(build_retro_export_inputs(report, history=history, editable=editable))

        monkeypatch.setattr(retro_export, "_export_doc", _counting)

        def _fake_dir(key):
            target.mkdir(parents=True, exist_ok=True)
            return target

        monkeypatch.setattr("yeaboi.paths.get_retro_export_dir", _fake_dir)
        export_retro(_report(), project_name="Demo")
        assert len(calls) == 1
