"""Unit tests for Daily Standup Markdown + HTML export."""

from tests._pages import assert_self_contained, island
from yeaboi.agent.state import MemberUpdate, StandupReport
from yeaboi.standup import export
from yeaboi.standup.export import (
    _leftover_links,
    _md_runs,
    _runs,
    _team_summary_runs,
    _ticket_key_map,
    build_standup_html,
    build_standup_markdown,
    export_standup,
)


def _report(**over) -> StandupReport:
    base = dict(
        date="2026-07-10",
        session_id="demo",
        sprint_name="Sprint 5",
        sprint_day=3,
        sprint_total_days=10,
        confidence_pct=82,
        confidence_label="At risk",
        confidence_rationale="behind ideal burn",
        team_summary="steady progress",
        member_updates=(
            MemberUpdate(name="Alice", summary="login page", source="inferred"),
            MemberUpdate(
                name="Bob",
                summary="paired on auth",
                blockers="waiting on review",
                source="combined",
                self_report="paired with Alice on auth",
            ),
        ),
        activity_counts=(("github", 2), ("jira", 1)),
        warnings=("Jira: authentication failed — check token",),
    )
    base.update(over)
    return StandupReport(**base)


class TestMarkdown:
    def test_contains_key_sections(self):
        md = build_standup_markdown(_report())
        assert "# Daily Standup — 2026-07-10" in md
        assert "day 3 of 10" in md
        assert "**Confidence:** At risk (82%)" in md
        assert "## ⚠ Notices" in md
        assert "Jira: authentication failed" in md
        assert "## Team Summary" in md
        # Member updates render as per-member sections with labeled bullets.
        assert "### Alice" in md
        assert "### Bob (you)" in md
        assert "login page" in md
        assert "- **Blocker:** waiting on review" in md
        assert "> ✍ paired with Alice on auth" in md
        assert "github: 2, jira: 1" in md
        # Branded footer with a real link.
        assert "🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)" in md

    def test_empty_report(self):
        md = build_standup_markdown(StandupReport(date="2026-07-10"))
        assert "# Daily Standup" in md
        assert "_No individual updates._" in md

    def test_images_in_screenshots_section(self):
        md = build_standup_markdown(_report(images=("/tmp/shot1.png", "/tmp/shot2.png")))
        # Screenshots follow the member sections in their own section.
        assert "## Screenshots" in md
        assert "![Screenshot](/tmp/shot1.png)" in md
        assert "![Screenshot](/tmp/shot2.png)" in md

    def test_pipe_in_member_content_passes_through(self):
        # No table anymore — pipes need no escaping and survive verbatim.
        rep = _report(member_updates=(MemberUpdate(name="Alice", summary="a | b", source="inferred"),))
        md = build_standup_markdown(rep)
        assert "a | b" in md

    def test_category_bullets_with_links(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="tickets and code",
                    ticketing_summary="moved PSOT-1 to review",
                    ticketing_links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                    code_summary="opened a PR",
                    code_links=(("fix login", "https://github.com/o/r/pull/9"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        # Ticket key becomes an inline markdown link inside the bullet text.
        assert "- **Ticketing:** moved [PSOT-1](https://x.atlassian.net/browse/PSOT-1) to review" in md
        # Non-ticket-shaped link labels stay as explicit refs on the bullet.
        assert "- **Code:** opened a PR — [fix login](https://github.com/o/r/pull/9)" in md

    def test_team_summary_bullets_bold_names(self):
        rep = _report(team_summary="Alice shipped the login page. Bob is blocked on review.")
        md = build_standup_markdown(rep)
        assert "- **Alice** shipped the login page." in md
        assert "- **Bob** is blocked on review." in md


class TestMemberLinks:
    def test_markdown_ticket_key_linked_inline(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="moved PSOT-1 to review",
                    links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        # The key text itself is the link — no separate Links line needed.
        assert "moved [PSOT-1](https://x.atlassian.net/browse/PSOT-1) to review" in md
        assert "**Links:**" not in md

    def test_markdown_legacy_links_bullet_for_unmentioned_refs(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="general work",
                    links=(("fix login", "https://github.com/o/r/pull/9"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        assert "- **Links:** [fix login](https://github.com/o/r/pull/9)" in md

    def test_html_links_travel_as_label_url_pairs(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="work",
                    links=(("<b>PSOT-1</b>", "https://x.atlassian.net/browse/PSOT-1?a=1&b=2"),),
                ),
            )
        )
        html = build_standup_html(rep)
        assert "<b>PSOT-1</b>" not in html  # never markup in the document
        member = island(html)["report"]["members"][0]
        assert member["links"] == [["<b>PSOT-1</b>", "https://x.atlassian.net/browse/PSOT-1?a=1&b=2"]]

    def test_unsafe_link_keeps_its_label_and_loses_its_url(self):
        # Dropping the row would silently shrink the evidence a reader is shown.
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="work", links=(("see this", "javascript:alert(1)"),)),)
        )
        assert island(build_standup_html(rep))["report"]["members"][0]["links"] == [["see this", ""]]

    def test_no_links_no_section(self):
        md = build_standup_markdown(_report())
        assert "**Links:**" not in md


class TestRuns:
    """The `Run[]` contract that replaced the escape-then-substitute pair.

    Both artifacts read this one structure — the page through `RichText`, the
    Markdown through `_md_runs` — so these assert the *spans*, and the fact that
    the two renderings of the same spans agree.
    """

    URL = "https://x.atlassian.net/browse/PSOT-1"

    def test_mapped_key_becomes_a_link_run(self):
        assert _runs("moved PSOT-1 to review", {"PSOT-1": self.URL}) == [
            {"s": "moved "},
            {"s": "PSOT-1", "href": self.URL},
            {"s": " to review"},
        ]

    def test_unknown_key_is_a_plain_run(self):
        runs = _runs("moved PSOT-2 to review", {"PSOT-1": self.URL})
        assert all("href" not in run for run in runs)
        assert "".join(run["s"] for run in runs) == "moved PSOT-2 to review"

    def test_markup_in_the_prose_stays_text(self):
        # No escaping anywhere: the text is a text child on the page, and the
        # angle brackets are simply part of the string.
        assert _runs("a & b <script> PSOT-1", {"PSOT-1": self.URL})[0] == {"s": "a & b <script> "}

    def test_unsafe_key_url_never_becomes_a_link(self):
        # The `_ticket_key_map` fallback builds URLs from a configured base, so
        # a hostile base must not produce a live link.
        assert _runs("PSOT-1", {"PSOT-1": "javascript:alert(1)"}) == [{"s": "PSOT-1"}]

    def test_longer_key_never_half_matches(self):
        runs = _runs("closed PSOT-12", {"PSOT-1": "https://x/1", "PSOT-12": "https://x/12"})
        assert runs[1] == {"s": "PSOT-12", "href": "https://x/12"}

    def test_the_two_renderings_agree(self):
        runs = _runs("moved PSOT-1", {"PSOT-1": self.URL})
        assert _md_runs(runs) == f"moved [PSOT-1]({self.URL})"
        # …and the same list is what the page gets, verbatim.
        rep = _report(
            team_summary="",
            member_updates=(
                MemberUpdate(name="Alice", summary="moved PSOT-1", ticketing_links=(("PSOT-1", self.URL),)),
            ),
        )
        assert island(build_standup_html(rep))["report"]["members"][0]["summary"] == runs

    def test_bold_and_link_can_share_a_sentence(self):
        runs = _team_summary_runs("Alice shipped PSOT-1.", {"PSOT-1": self.URL}, ["Alice"])[0]
        assert {"s": "Alice", "strong": True} in runs
        assert {"s": "PSOT-1", "href": self.URL} in runs
        assert _md_runs(runs) == f"**Alice** shipped [PSOT-1]({self.URL})."

    def test_key_map_from_link_evidence(self):
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_links=(("PSOT-1", self.URL),)),)
        )
        assert _ticket_key_map(rep) == {"PSOT-1": self.URL}

    def test_fallback_prefix_gated(self, monkeypatch):
        monkeypatch.setenv("JIRA_BASE_URL", "https://x.atlassian.net")
        rep = _report(
            team_summary="PSOT-99 landed; encoded as UTF-8 with SHA-256 digests per ISO-8601.",
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_links=(("PSOT-1", self.URL),)),),
        )
        key_map = _ticket_key_map(rep)
        assert key_map["PSOT-99"] == "https://x.atlassian.net/browse/PSOT-99"
        # Prefix gate: regex-shaped non-tickets never become links.
        assert "UTF-8" not in key_map and "SHA-256" not in key_map and "ISO-8601" not in key_map

    def test_no_fallback_without_base_url(self, monkeypatch):
        monkeypatch.delenv("JIRA_BASE_URL", raising=False)
        rep = _report(
            team_summary="PSOT-99 landed.",
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_links=(("PSOT-1", self.URL),)),),
        )
        assert "PSOT-99" not in _ticket_key_map(rep)

    def test_no_evidence_no_guessing(self, monkeypatch):
        monkeypatch.setenv("JIRA_BASE_URL", "https://x.atlassian.net")
        rep = _report(team_summary="PSOT-99 landed.")
        assert _ticket_key_map(rep) == {}

    def test_leftover_links(self):
        links = (("PSOT-1", "https://x/1"), ("fix login", "https://x/pr/9"))
        # PSOT-1 is mentioned inline → only the PR title is left over.
        assert _leftover_links("moved PSOT-1", links) == [("fix login", "https://x/pr/9")]
        # Nothing mentioned → both are left over.
        assert _leftover_links("quiet day", links) == list(links)


class TestTeamSummaryRuns:
    def test_one_run_list_per_sentence_with_names_and_tickets(self):
        sentences = _team_summary_runs(
            "Alice shipped PSOT-1. Bob is blocked on the auth migration.",
            {"PSOT-1": "https://x/browse/PSOT-1"},
            ["Alice Smith", "Bob"],
        )
        assert len(sentences) == 2
        assert {"s": "Alice", "strong": True} in sentences[0]
        assert {"s": "PSOT-1", "href": "https://x/browse/PSOT-1"} in sentences[0]
        assert {"s": "Bob", "strong": True} in sentences[1]

    def test_single_sentence_is_a_single_list(self):
        # Whether that renders as a paragraph or a bullet is the bundle's call.
        assert _team_summary_runs("Steady progress across the board.", {}, ["Alice"]) == [
            [{"s": "Steady progress across the board."}]
        ]

    def test_full_name_wins_over_first_name(self):
        # Longest-first alternation: one bold run, not a nested pair.
        assert _team_summary_runs("Alice Smith shipped it.", {}, ["Alice Smith"])[0] == [
            {"s": "Alice Smith", "strong": True},
            {"s": " shipped it."},
        ]

    def test_a_member_name_that_looks_like_markup_stays_text(self):
        assert _team_summary_runs("<i>Eve</i> shipped it.", {}, ["<i>Eve</i>"])[0][0] == {
            "s": "<i>Eve</i>",
            "strong": True,
        }

    def test_reaches_the_page(self):
        rep = _report(team_summary="Alice shipped the login page. Bob is blocked.")
        summary = island(build_standup_html(rep))["report"]["summary"]
        assert len(summary) == 2
        assert {"s": "Alice", "strong": True} in summary[0]


class TestHtml:
    def test_selfcontained_and_untrusted_text_is_data(self):
        rep = _report(team_summary="<script>alert(1)</script>")
        html = build_standup_html(rep)
        assert html.startswith("<!DOCTYPE html>")
        assert "<style>" in html  # inline CSS, self-contained
        assert "<script>alert(1)</script>" not in html  # never markup in the document
        report = island(html)["report"]
        assert report["confidence"]["label"] == "At risk"
        assert report["warnings"] == ["Jira: authentication failed — check token"]
        # The probe reaches the payload verbatim; the island's JSON encoding is
        # what makes it inert, not an escape pass.
        assert report["summary"] == [[{"s": "<script>alert(1)</script>"}]]

    def test_empty_report(self):
        report = island(build_standup_html(StandupReport(date="2026-07-10")))["report"]
        assert report["members"] == []

    def test_overview_facts(self):
        report = island(build_standup_html(_report()))["report"]
        assert report["sprint"] == {"name": "Sprint 5", "day": 3, "total": 10}
        assert report["confidence"]["pct"] == 82
        assert report["confidence"]["label"] == "At risk"
        assert sum(n for _, n in report["activityCounts"]) == 3

    def test_nav_links_present_sections(self):
        nav = dict(tuple(entry) for entry in island(build_standup_html(_report()))["chrome"]["nav"])
        assert set(nav) == {"overview", "summary", "updates", "details"}
        assert "screenshots" not in nav  # no images in the base report

    def test_ticket_key_linked_inline_no_link_line(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="moved PSOT-1 to review",
                    ticketing_summary="PSOT-1 now in review",
                    ticketing_links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                ),
            )
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert {"s": "PSOT-1", "href": "https://x.atlassian.net/browse/PSOT-1"} in member["summary"]
        # The key is inline in the prose, so it is not repeated as a chip.
        assert member["categories"][0]["links"] == []

    def test_blocked_member_carries_its_blocker(self):
        members = {m["name"]: m for m in island(build_standup_html(_report()))["report"]["members"]}
        assert members["Bob"]["blockers"] == [{"s": "waiting on review"}]
        assert "blockers" not in members["Alice"]

    def test_activity_counts_travel_in_category_order(self):
        # [tickets, code, docs] — the order the chips and the bars both use.
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_activity_count=3, code_activity_count=0),)
        )
        assert island(build_standup_html(rep))["report"]["members"][0]["counts"] == [3, 0, 0]

    def test_self_report_ticket_key_linked(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    self_report="will pick up PSOT-14 next",
                    ticketing_links=(("PSOT-14", "https://x.atlassian.net/browse/PSOT-14"),),
                ),
            )
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert {"s": "PSOT-14", "href": "https://x.atlassian.net/browse/PSOT-14"} in member["selfReport"]

    def test_self_report_marks_the_member_as_their_own_author(self):
        members = {m["name"]: m for m in island(build_standup_html(_report()))["report"]["members"]}
        assert members["Bob"]["own"] is True
        assert "".join(r["s"] for r in members["Bob"]["selfReport"]) == "paired with Alice on auth"
        assert "own" not in members["Alice"]

    def test_category_sections_render(self):
        # Adaptive grid: a category earns its column with activity or links.
        html = build_standup_html(
            _report(
                member_updates=(
                    MemberUpdate(
                        name="Alice",
                        summary="busy day",
                        ticketing_summary="Moved PSOT-1.",
                        ticketing_activity_count=1,
                        code_summary="Merged a PR.",
                        code_activity_count=1,
                        documentation_summary="Updated the runbook.",
                        documentation_activity_count=1,
                    ),
                ),
            )
        )
        member = island(html)["report"]["members"][0]
        assert [c["label"] for c in member["categories"]] == ["Ticketing", "Code", "Documentation"]

    def test_images_base64_embedded(self, tmp_path):
        img = tmp_path / "shot.png"
        img.write_bytes(b"\x89PNG fake")
        images = island(build_standup_html(_report(images=(str(img),))))["report"]["images"]
        assert len(images) == 1 and images[0].startswith("data:image/png;base64,")

    def test_missing_image_skipped(self):
        # markup(): the inlined bundle carries the duck sprites as data URIs, so
        # a check against the whole document reads those instead of the report.
        assert island(build_standup_html(_report(images=("/nope/gone.png",))))["report"]["images"] == []


class TestExportWrites:
    def test_writes_md_and_html(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        paths = export_standup(_report(), project_name="My Demo Project")
        assert paths["markdown"].exists() and paths["markdown"].suffix == ".md"
        assert paths["html"].exists() and paths["html"].suffix == ".html"
        # slug of project name is used for the subdir
        assert paths["markdown"].parent.name == "my-demo-project"
        assert "Daily Standup" in paths["markdown"].read_text()
        assert paths["html"].read_text().startswith("<!DOCTYPE html>")

    def test_rerun_same_day_overwrites(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        export_standup(_report(confidence_pct=50), project_name="Demo")
        paths = export_standup(_report(confidence_pct=90), project_name="Demo")
        # one dated file per day, latest wins
        files = list(paths["markdown"].parent.glob("standup-2026-07-10.*"))
        assert len(files) == 2  # .md + .html
        assert "(90%)" in paths["markdown"].read_text()

    def test_slug_helper(self):
        assert export._slug("My Project!!") == "my-project"
        assert export._slug("") == "standup"

    def test_images_localized_into_export_dir(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        img = tmp_path / "shot.png"
        img.write_bytes(b"png")
        paths = export_standup(_report(images=(str(img),)), project_name="Demo")
        md = paths["markdown"].read_text()
        assert "![Screenshot](images/shot.png)" in md
        assert (paths["markdown"].parent / "images" / "shot.png").exists()


class TestSkippedSourcesLine:
    def test_markdown_lists_skipped_sources(self):
        md = build_standup_markdown(_report(skipped_sources=(("github", "STANDUP_GITHUB_REPO not set"),)))
        assert "Sources skipped — github (STANDUP_GITHUB_REPO not set)" in md

    def test_html_lists_skipped_sources_in_details(self):
        report = island(build_standup_html(_report(skipped_sources=(("notion", "NOTION_ROOT_PAGE_ID not set"),))))
        assert report["report"]["skipped"] == [["notion", "NOTION_ROOT_PAGE_ID not set"]]

    def test_plaintext_lists_skipped_sources(self):
        from yeaboi.standup.render import format_standup_plaintext

        text = format_standup_plaintext(_report(skipped_sources=(("confluence", "CONFLUENCE_SPACE_KEY not set"),)))
        assert "Sources skipped — confluence (CONFLUENCE_SPACE_KEY not set)" in text

    def test_no_skipped_sources_no_line(self):
        from yeaboi.standup.render import format_standup_plaintext

        assert "Sources skipped" not in format_standup_plaintext(_report())


class TestSharedDesignSystem:
    def test_standup_html_uses_shared_theme(self):
        html = build_standup_html(_report())
        assert 'data-theme="midnight"' in html
        assert "yeaboi-export-theme" in html  # theme switcher present
        assert_self_contained(html)


def _history(*rows):
    """Store-shaped history rows, newest-first like StandupStore.get_history."""
    out = []
    for day, pct, *rest in rows:
        out.append(
            {
                "id": len(out),
                "run_at": f"{day}T10:00:00",
                "standup_date": day,
                "sprint_day": 1,
                "confidence_pct": pct,
                "status": rest[0] if rest else "success",
            }
        )
    return out


class TestVisuals:
    def test_trend_present_with_history(self):
        html = build_standup_html(
            _report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70), ("2026-07-08", 65))
        )
        trend = island(html)["report"]["trend"]
        assert trend["title"] == "Confidence trend"
        # A percentage cannot exceed 100, so the drawn domain says so.
        assert trend["floor"] == 0 and trend["ceiling"] == 100

    def test_trend_absent_without_two_points(self):
        assert island(build_standup_html(_report()))["report"]["trend"] is None
        one = build_standup_html(_report(), history=_history(("2026-07-10", 82)))
        assert island(one)["report"]["trend"] is None

    def test_trend_is_oldest_first(self):
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-01", 50)))
        assert island(html)["report"]["trend"]["points"][0] == ["2026-07-01", 50]

    def test_trend_skips_failed_and_dedupes_and_ignores_future(self):
        history = _history(
            ("2026-07-12", 90),  # after report.date → ignored
            ("2026-07-10", 82),
            ("2026-07-10", 40),  # older rerun of same day → deduped
            ("2026-07-09", 0, "failed"),  # failed → skipped
            ("2026-07-08", 60),
        )
        points = island(build_standup_html(_report(), history=history))["report"]["trend"]["points"]
        assert points == [["2026-07-08", 60], ["2026-07-10", 82]]

    def test_confidence_label_travels_for_the_end_dot(self):
        # The dot's colour is the bundle's business; the label it derives from
        # is the server's, and this is the only thing that has to cross.
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70)))
        assert island(html)["report"]["confidence"]["label"] == "At risk"

    def test_sprint_progress_is_derivable(self):
        report = island(build_standup_html(_report()))["report"]
        assert report["sprint"]["day"] == 3 and report["sprint"]["total"] == 10
        no_days = island(build_standup_html(_report(sprint_total_days=0, sprint_day=0)))["report"]
        assert no_days["sprint"]["total"] == 0  # nothing to draw a bar from

    def test_team_activity_counts_per_member(self):
        rep = _report(
            member_updates=(
                MemberUpdate(name="Alice", summary="x", ticketing_activity_count=3, code_activity_count=2),
                MemberUpdate(name="Bob", summary="y", documentation_activity_count=1),
                MemberUpdate(name="Zed", summary="quiet"),  # all-zero → no bar row
            )
        )
        counts = {m["name"]: m["counts"] for m in island(build_standup_html(rep))["report"]["members"]}
        assert counts == {"Alice": [3, 2, 0], "Bob": [0, 0, 1], "Zed": [0, 0, 0]}

    def test_activity_counts_by_source(self):
        assert island(build_standup_html(_report()))["report"]["activityCounts"] == [["github", 2], ["jira", 1]]

    def test_coverage_statuses_travel_as_words(self):
        rep = _report(category_coverage=(("ticketing", "covered"), ("documentation", "not_configured")))
        assert island(build_standup_html(rep))["report"]["coverage"] == [
            ["ticketing", "covered"],
            ["documentation", "not_configured"],
        ]

    def test_member_name_is_never_markup(self):
        rep = _report(member_updates=(MemberUpdate(name="<img src=x>", summary="x"),))
        html = build_standup_html(rep)
        assert "<img src=x>" not in html
        assert island(html)["report"]["members"][0]["name"] == "<img src=x>"

    def test_self_contained_with_history(self):
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70)))
        assert_self_contained(html)


class TestDayOverDayExport:
    def _rep(self, **over):
        base = dict(
            confidence_delta=-8,
            confidence_trend="declining",
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="login page",
                    progress_note="Still on PSOT-9 from the last standup.",
                    outlook="Likely to wrap up PSOT-9 today.",
                    ticketing_links=(("PSOT-9", "https://acme.atlassian.net/browse/PSOT-9"),),
                ),
            ),
        )
        base.update(over)
        return _report(**base)

    def test_markdown_progress_and_outlook_bullets(self):
        md = build_standup_markdown(self._rep())
        assert "- **Since last standup:** Still on [PSOT-9]" in md
        assert "- **Outlook:** Likely to wrap up [PSOT-9]" in md

    def test_markdown_confidence_trend_suffix(self):
        md = build_standup_markdown(self._rep())
        assert "(▼ 8 vs last standup)" in md
        md_up = build_standup_markdown(self._rep(confidence_delta=6, confidence_trend="improving"))
        assert "(▲ +6 vs last standup)" in md_up

    def test_markdown_no_trend_no_suffix(self):
        md = build_standup_markdown(self._rep(confidence_delta=0, confidence_trend=""))
        assert "vs last standup" not in md

    def test_html_progress_note_and_outlook_are_linkified(self):
        member = island(build_standup_html(self._rep()))["report"]["members"][0]
        link = {"s": "PSOT-9", "href": "https://acme.atlassian.net/browse/PSOT-9"}
        # Ticket keys inside both prose fields become link runs.
        assert link in member["progressNote"]
        assert link in member["outlook"]

    def test_html_trend_chip(self):
        html = build_standup_html(self._rep())
        assert "▼ 8 vs last standup" in html
        html_up = build_standup_html(self._rep(confidence_delta=6, confidence_trend="improving"))
        assert "▲ +6 vs last standup" in html_up

    def test_html_no_trend_no_chip(self):
        html = build_standup_html(self._rep(confidence_delta=0, confidence_trend=""))
        assert "vs last standup" not in html

    def test_html_escapes_hostile_fields(self):
        rep = self._rep(
            member_updates=(MemberUpdate(name="Alice", summary="x", progress_note="<b>bold</b>", outlook="<i>it</i>"),),
        )
        html = build_standup_html(rep)
        assert "<b>bold</b>" not in html
        assert "<i>it</i>" not in html

    def test_empty_fields_are_absent_not_empty(self):
        member = island(build_standup_html(_report()))["report"]["members"][0]
        assert "progressNote" not in member and "outlook" not in member


class TestCardReadability:
    """Sentence-split bullets, link chips, and the adaptive category grid."""

    def test_summary_splits_into_bullets(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary=(
                        "PSOT-1593 was moved to In Progress. Several sub-tasks remain in To Do; "
                        "the access-key work is In Progress."
                    ),
                    ticketing_activity_count=3,
                ),
            ),
        )
        category = island(build_standup_html(rep))["report"]["members"][0]["categories"][0]
        assert [_md_runs(item) for item in category["items"]] == [
            "PSOT-1593 was moved to In Progress.",
            "Several sub-tasks remain in To Do",
            "the access-key work is In Progress.",
        ]

    def test_leftover_links_render_as_chip_row(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="Moved PSOT-1 forward.",
                    ticketing_links=(
                        ("PSOT-2", "https://j/browse/PSOT-2"),
                        ("PSOT-3", "https://j/browse/PSOT-3"),
                    ),
                    ticketing_activity_count=3,
                ),
            ),
        )
        category = island(build_standup_html(rep))["report"]["members"][0]["categories"][0]
        # PSOT-1 is inline in the prose, so only the two unmentioned keys are
        # left over as evidence chips.
        assert category["links"] == [
            ["PSOT-2", "https://j/browse/PSOT-2"],
            ["PSOT-3", "https://j/browse/PSOT-3"],
        ]

    def test_empty_category_becomes_footnote_not_column(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="Moved PSOT-1 forward.",
                    ticketing_activity_count=2,
                    documentation_summary="No documentation activity detected in the selected sources.",
                    documentation_activity_count=0,
                ),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert [c["label"] for c in member["categories"]] == ["Ticketing"]
        assert member["footnotes"] == [
            {
                "label": "Documentation",
                "runs": [{"s": "No documentation activity detected in the selected sources."}],
            }
        ]

    def test_not_configured_wording_survives_in_footnote(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="Moved PSOT-1 forward.",
                    ticketing_activity_count=1,
                    documentation_summary="Documentation sources are not configured for this standup.",
                    documentation_activity_count=0,
                ),
            ),
        )
        # "not configured" must stay distinguishable from "no activity detected".
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert _md_runs(member["footnotes"][0]["runs"]).startswith("Documentation sources are not configured")

    def test_all_quiet_member_has_no_grid(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Quiet",
                    summary="No activity detected.",
                    ticketing_summary="No ticketing activity detected.",
                    code_summary="No code activity detected in the selected repositories.",
                    documentation_summary="No documentation activity detected in the selected sources.",
                ),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert member["categories"] == []
        assert len(member["footnotes"]) == 3

    def test_links_only_category_still_gets_column(self):
        # Evidence links with no prose (legacy-ish shape) must not vanish.
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    code_links=(("PR 42", "https://g/pull/42"),),
                ),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert member["categories"] == [{"label": "Code", "items": [], "links": [["PR 42", "https://g/pull/42"]]}]

    def test_bullets_still_linkify_ticket_keys(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="PSOT-9 moved to review; PSOT-14 pulled in.",
                    ticketing_links=(("PSOT-9", "https://j/browse/PSOT-9"),),
                    ticketing_activity_count=2,
                ),
            ),
        )
        category = island(build_standup_html(rep))["report"]["members"][0]["categories"][0]
        assert category["items"][0][0] == {"s": "PSOT-9", "href": "https://j/browse/PSOT-9"}
