"""Unit tests for Daily Standup Markdown + HTML export."""

import json
from dataclasses import replace

from tests._pages import assert_self_contained, island
from yeaboi.agent.state import ActivityEvidence, MemberUpdate, OpsSignal, StandupReport
from yeaboi.standup import export
from yeaboi.standup.export import (
    _leftover_links,
    _md_runs,
    _runs,
    _team_summary_runs,
    _ticket_key_map,
    build_standup_html,
    build_standup_markdown,
    export_standup,
)


def _report(**over) -> StandupReport:
    base = dict(
        date="2026-07-10",
        session_id="demo",
        sprint_name="Sprint 5",
        sprint_day=3,
        sprint_total_days=10,
        confidence_pct=82,
        confidence_label="At risk",
        confidence_rationale="behind ideal burn",
        team_summary="steady progress",
        member_updates=(
            MemberUpdate(name="Alice", summary="login page", source="inferred"),
            MemberUpdate(
                name="Bob",
                summary="paired on auth",
                blockers="waiting on review",
                source="combined",
                self_report="paired with Alice on auth",
            ),
        ),
        activity_counts=(("github", 2), ("jira", 1)),
        warnings=("Jira: authentication failed — check token",),
    )
    base.update(over)
    return StandupReport(**base)


class TestMarkdown:
    def test_contains_key_sections(self):
        md = build_standup_markdown(_report())
        assert "# Daily Standup — 2026-07-10" in md
        assert "day 3 of 10" in md
        assert "**Confidence:** At risk (82%)" in md
        assert "## ⚠ Notices" in md
        assert "Jira: authentication failed" in md
        assert "## Team Summary" in md
        # Member updates render as per-member sections with labeled bullets.
        assert "### Alice" in md
        assert "### Bob (you)" in md
        assert "login page" in md
        assert "- **Blocker:** waiting on review" in md
        assert "> ✍ paired with Alice on auth" in md
        assert "github: 2, jira: 1" in md
        # Branded footer with a real link.
        assert "🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)" in md

    def test_empty_report(self):
        md = build_standup_markdown(StandupReport(date="2026-07-10"))
        assert "# Daily Standup" in md
        assert "_No individual updates._" in md

    def test_images_in_screenshots_section(self):
        md = build_standup_markdown(_report(images=("/tmp/shot1.png", "/tmp/shot2.png")))
        # Screenshots follow the member sections in their own section.
        assert "## Screenshots" in md
        assert "![Screenshot](/tmp/shot1.png)" in md
        assert "![Screenshot](/tmp/shot2.png)" in md

    def test_pipe_in_member_content_passes_through(self):
        # No table anymore — pipes need no escaping and survive verbatim.
        rep = _report(member_updates=(MemberUpdate(name="Alice", summary="a | b", source="inferred"),))
        md = build_standup_markdown(rep)
        assert "a | b" in md

    def test_category_bullets_with_links(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="tickets and code",
                    ticketing_summary="moved PSOT-1 to review",
                    ticketing_links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                    code_summary="opened a PR",
                    code_links=(("fix login", "https://github.com/o/r/pull/9"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        # Ticket key becomes an inline markdown link inside the bullet text.
        assert "- **Ticketing:** moved [PSOT-1](https://x.atlassian.net/browse/PSOT-1) to review" in md
        # Non-ticket-shaped link labels stay as explicit refs on the bullet.
        assert "- **Code:** opened a PR — [fix login](https://github.com/o/r/pull/9)" in md

    def test_team_summary_bullets_bold_names(self):
        rep = _report(team_summary="Alice shipped the login page. Bob is blocked on review.")
        md = build_standup_markdown(rep)
        assert "- **Alice** shipped the login page." in md
        assert "- **Bob** is blocked on review." in md


class TestMemberLinks:
    def test_markdown_ticket_key_linked_inline(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="moved PSOT-1 to review",
                    links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        # The key text itself is the link — no separate Links line needed.
        assert "moved [PSOT-1](https://x.atlassian.net/browse/PSOT-1) to review" in md
        assert "**Links:**" not in md

    def test_markdown_legacy_links_bullet_for_unmentioned_refs(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="general work",
                    links=(("fix login", "https://github.com/o/r/pull/9"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        assert "- **Links:** [fix login](https://github.com/o/r/pull/9)" in md

    def test_html_links_travel_as_label_url_pairs(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="work",
                    links=(("<b>PSOT-1</b>", "https://x.atlassian.net/browse/PSOT-1?a=1&b=2"),),
                ),
            )
        )
        html = build_standup_html(rep)
        assert "<b>PSOT-1</b>" not in html  # never markup in the document
        member = island(html)["report"]["members"][0]
        assert member["links"] == [["<b>PSOT-1</b>", "https://x.atlassian.net/browse/PSOT-1?a=1&b=2"]]

    def test_unsafe_link_keeps_its_label_and_loses_its_url(self):
        # Dropping the row would silently shrink the evidence a reader is shown.
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="work", links=(("see this", "javascript:alert(1)"),)),)
        )
        assert island(build_standup_html(rep))["report"]["members"][0]["links"] == [["see this", ""]]

    def test_no_links_no_section(self):
        md = build_standup_markdown(_report())
        assert "**Links:**" not in md


class TestRuns:
    """The `Run[]` contract that replaced the escape-then-substitute pair.

    Both artifacts read this one structure — the page through `RichText`, the
    Markdown through `_md_runs` — so these assert the *spans*, and the fact that
    the two renderings of the same spans agree.
    """

    URL = "https://x.atlassian.net/browse/PSOT-1"

    def test_mapped_key_becomes_a_link_run(self):
        assert _runs("moved PSOT-1 to review", {"PSOT-1": self.URL}) == [
            {"s": "moved "},
            {"s": "PSOT-1", "href": self.URL},
            {"s": " to review"},
        ]

    def test_unknown_key_is_a_plain_run(self):
        runs = _runs("moved PSOT-2 to review", {"PSOT-1": self.URL})
        assert all("href" not in run for run in runs)
        assert "".join(run["s"] for run in runs) == "moved PSOT-2 to review"

    def test_markup_in_the_prose_stays_text(self):
        # No escaping anywhere: the text is a text child on the page, and the
        # angle brackets are simply part of the string.
        assert _runs("a & b <script> PSOT-1", {"PSOT-1": self.URL})[0] == {"s": "a & b <script> "}

    def test_unsafe_key_url_never_becomes_a_link(self):
        # The `_ticket_key_map` fallback builds URLs from a configured base, so
        # a hostile base must not produce a live link.
        assert _runs("PSOT-1", {"PSOT-1": "javascript:alert(1)"}) == [{"s": "PSOT-1"}]

    def test_longer_key_never_half_matches(self):
        runs = _runs("closed PSOT-12", {"PSOT-1": "https://x/1", "PSOT-12": "https://x/12"})
        assert runs[1] == {"s": "PSOT-12", "href": "https://x/12"}

    def test_the_two_renderings_agree(self):
        runs = _runs("moved PSOT-1", {"PSOT-1": self.URL})
        assert _md_runs(runs) == f"moved [PSOT-1]({self.URL})"
        # …and the same list is what the page gets, verbatim.
        rep = _report(
            team_summary="",
            member_updates=(
                MemberUpdate(name="Alice", summary="moved PSOT-1", ticketing_links=(("PSOT-1", self.URL),)),
            ),
        )
        # The member summary ships as bullet fragments (one run-list each).
        assert island(build_standup_html(rep))["report"]["members"][0]["summary"] == [runs]

    def test_bold_and_link_can_share_a_sentence(self):
        runs = _team_summary_runs("Alice shipped PSOT-1.", {"PSOT-1": self.URL}, ["Alice"])[0]
        assert {"s": "Alice", "strong": True} in runs
        assert {"s": "PSOT-1", "href": self.URL} in runs
        assert _md_runs(runs) == f"**Alice** shipped [PSOT-1]({self.URL})."

    def test_key_map_from_link_evidence(self):
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_links=(("PSOT-1", self.URL),)),)
        )
        assert _ticket_key_map(rep) == {"PSOT-1": self.URL}

    def test_fallback_prefix_gated(self, monkeypatch):
        monkeypatch.setenv("JIRA_BASE_URL", "https://x.atlassian.net")
        rep = _report(
            team_summary="PSOT-99 landed; encoded as UTF-8 with SHA-256 digests per ISO-8601.",
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_links=(("PSOT-1", self.URL),)),),
        )
        key_map = _ticket_key_map(rep)
        assert key_map["PSOT-99"] == "https://x.atlassian.net/browse/PSOT-99"
        # Prefix gate: regex-shaped non-tickets never become links.
        assert "UTF-8" not in key_map and "SHA-256" not in key_map and "ISO-8601" not in key_map

    def test_no_fallback_without_base_url(self, monkeypatch):
        monkeypatch.delenv("JIRA_BASE_URL", raising=False)
        rep = _report(
            team_summary="PSOT-99 landed.",
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_links=(("PSOT-1", self.URL),)),),
        )
        assert "PSOT-99" not in _ticket_key_map(rep)

    def test_no_evidence_no_guessing(self, monkeypatch):
        monkeypatch.setenv("JIRA_BASE_URL", "https://x.atlassian.net")
        rep = _report(team_summary="PSOT-99 landed.")
        assert _ticket_key_map(rep) == {}

    def test_leftover_links(self):
        links = (("PSOT-1", "https://x/1"), ("fix login", "https://x/pr/9"))
        # PSOT-1 is mentioned inline → only the PR title is left over.
        assert _leftover_links("moved PSOT-1", links) == [("fix login", "https://x/pr/9")]
        # Nothing mentioned → both are left over.
        assert _leftover_links("quiet day", links) == list(links)


class TestTeamSummaryRuns:
    def test_one_run_list_per_sentence_with_names_and_tickets(self):
        sentences = _team_summary_runs(
            "Alice shipped PSOT-1. Bob is blocked on the auth migration.",
            {"PSOT-1": "https://x/browse/PSOT-1"},
            ["Alice Smith", "Bob"],
        )
        assert len(sentences) == 2
        assert {"s": "Alice", "strong": True} in sentences[0]
        assert {"s": "PSOT-1", "href": "https://x/browse/PSOT-1"} in sentences[0]
        assert {"s": "Bob", "strong": True} in sentences[1]

    def test_single_sentence_is_a_single_list(self):
        # Whether that renders as a paragraph or a bullet is the bundle's call.
        assert _team_summary_runs("Steady progress across the board.", {}, ["Alice"]) == [
            [{"s": "Steady progress across the board."}]
        ]

    def test_full_name_wins_over_first_name(self):
        # Longest-first alternation: one bold run, not a nested pair.
        assert _team_summary_runs("Alice Smith shipped it.", {}, ["Alice Smith"])[0] == [
            {"s": "Alice Smith", "strong": True},
            {"s": " shipped it."},
        ]

    def test_a_member_name_that_looks_like_markup_stays_text(self):
        assert _team_summary_runs("<i>Eve</i> shipped it.", {}, ["<i>Eve</i>"])[0][0] == {
            "s": "<i>Eve</i>",
            "strong": True,
        }

    def test_reaches_the_page(self):
        rep = _report(team_summary="Alice shipped the login page. Bob is blocked.")
        summary = island(build_standup_html(rep))["report"]["summary"]
        assert len(summary) == 2
        assert {"s": "Alice", "strong": True} in summary[0]


class TestHtml:
    def test_selfcontained_and_untrusted_text_is_data(self):
        rep = _report(team_summary="<script>alert(1)</script>")
        html = build_standup_html(rep)
        assert html.startswith("<!DOCTYPE html>")
        assert "<style>" in html  # inline CSS, self-contained
        assert "<script>alert(1)</script>" not in html  # never markup in the document
        report = island(html)["report"]
        assert report["confidence"]["label"] == "At risk"
        assert report["warnings"] == ["Jira: authentication failed — check token"]
        # The probe reaches the payload verbatim; the island's JSON encoding is
        # what makes it inert, not an escape pass.
        assert report["summary"] == [[{"s": "<script>alert(1)</script>"}]]

    def test_empty_report(self):
        report = island(build_standup_html(StandupReport(date="2026-07-10")))["report"]
        assert report["members"] == []

    def test_overview_facts(self):
        report = island(build_standup_html(_report()))["report"]
        assert report["sprint"] == {"name": "Sprint 5", "day": 3, "total": 10}
        assert report["confidence"]["pct"] == 82
        assert report["confidence"]["label"] == "At risk"
        assert sum(n for _, n in report["activityCounts"]) == 3

    def test_nav_links_present_sections(self):
        nav = dict(tuple(entry) for entry in island(build_standup_html(_report()))["chrome"]["nav"])
        assert set(nav) == {"overview", "summary", "updates", "details"}
        assert "screenshots" not in nav  # no images in the base report

    def test_ticket_key_linked_inline_no_link_line(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="moved PSOT-1 to review",
                    ticketing_summary="PSOT-1 now in review",
                    ticketing_links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                ),
            )
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert {"s": "PSOT-1", "href": "https://x.atlassian.net/browse/PSOT-1"} in member["summary"][0]
        # The key is inline in the prose, so it is not repeated as a chip.
        assert member["categories"][0]["links"] == []

    def test_blocked_member_carries_its_blocker(self):
        members = {m["name"]: m for m in island(build_standup_html(_report()))["report"]["members"]}
        assert members["Bob"]["blockers"] == [{"s": "waiting on review"}]
        assert "blockers" not in members["Alice"]

    def test_activity_counts_travel_in_category_order(self):
        # [tickets, code, docs] — the order the chips and the bars both use.
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_activity_count=3, code_activity_count=0),)
        )
        assert island(build_standup_html(rep))["report"]["members"][0]["counts"] == [3, 0, 0]

    def test_self_report_ticket_key_linked(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    self_report="will pick up PSOT-14 next",
                    ticketing_links=(("PSOT-14", "https://x.atlassian.net/browse/PSOT-14"),),
                ),
            )
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert {"s": "PSOT-14", "href": "https://x.atlassian.net/browse/PSOT-14"} in member["selfReport"]

    def test_self_report_marks_the_member_as_their_own_author(self):
        members = {m["name"]: m for m in island(build_standup_html(_report()))["report"]["members"]}
        assert members["Bob"]["own"] is True
        assert "".join(r["s"] for r in members["Bob"]["selfReport"]) == "paired with Alice on auth"
        assert "own" not in members["Alice"]

    def test_category_sections_render(self):
        # Adaptive grid: a category earns its column with activity or links.
        html = build_standup_html(
            _report(
                member_updates=(
                    MemberUpdate(
                        name="Alice",
                        summary="busy day",
                        ticketing_summary="Moved PSOT-1.",
                        ticketing_activity_count=1,
                        code_summary="Merged a PR.",
                        code_activity_count=1,
                        documentation_summary="Updated the runbook.",
                        documentation_activity_count=1,
                    ),
                ),
            )
        )
        member = island(html)["report"]["members"][0]
        assert [c["label"] for c in member["categories"]] == ["Ticketing", "Code", "Documentation"]

    def test_images_base64_embedded(self, tmp_path):
        img = tmp_path / "shot.png"
        img.write_bytes(b"\x89PNG fake")
        images = island(build_standup_html(_report(images=(str(img),))))["report"]["images"]
        assert len(images) == 1 and images[0].startswith("data:image/png;base64,")

    def test_missing_image_skipped(self):
        # markup(): the inlined bundle carries the duck sprites as data URIs, so
        # a check against the whole document reads those instead of the report.
        assert island(build_standup_html(_report(images=("/nope/gone.png",))))["report"]["images"] == []


class TestExportWrites:
    def test_writes_md_and_html(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        paths = export_standup(_report(), project_name="My Demo Project")
        assert paths["markdown"].exists() and paths["markdown"].suffix == ".md"
        assert paths["html"].exists() and paths["html"].suffix == ".html"
        # slug of project name is used for the subdir
        assert paths["markdown"].parent.name == "my-demo-project"
        assert "Daily Standup" in paths["markdown"].read_text()
        assert paths["html"].read_text().startswith("<!DOCTYPE html>")

    def test_rerun_same_day_overwrites(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        export_standup(_report(confidence_pct=50), project_name="Demo")
        paths = export_standup(_report(confidence_pct=90), project_name="Demo")
        # one dated file per day, latest wins
        files = list(paths["markdown"].parent.glob("standup-2026-07-10.*"))
        assert len(files) == 2  # .md + .html
        assert "(90%)" in paths["markdown"].read_text()

    def test_slug_helper(self):
        assert export._slug("My Project!!") == "my-project"
        assert export._slug("") == "standup"

    def test_images_localized_into_export_dir(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        img = tmp_path / "shot.png"
        img.write_bytes(b"png")
        paths = export_standup(_report(images=(str(img),)), project_name="Demo")
        md = paths["markdown"].read_text()
        assert "![Screenshot](images/shot.png)" in md
        assert (paths["markdown"].parent / "images" / "shot.png").exists()


class TestSkippedSourcesLine:
    """Two audiences, one field.

    The diagnostic surfaces (HTML details, and the TUI panel tested elsewhere) list
    every skip, because someone is reading them to answer "where is my GitHub?".
    The broadcast surfaces — Slack/email plaintext and the Markdown export — list
    only ``unmet_sources``, or a Jira-only team appends the same five-source
    apology to every standup it ever posts.
    """

    def test_markdown_lists_a_source_the_user_asked_for(self):
        md = build_standup_markdown(
            _report(skipped_sources=(("github", "STANDUP_GITHUB_REPO not set"),), unmet_sources=("github",))
        )
        assert "Sources skipped — GitHub (STANDUP_GITHUB_REPO not set)" in md

    def test_plaintext_lists_a_source_the_user_asked_for(self):
        from yeaboi.standup.render import format_standup_plaintext

        text = format_standup_plaintext(
            _report(
                skipped_sources=(("confluence", "CONFLUENCE_SPACE_KEY not set"),),
                unmet_sources=("confluence",),
            )
        )
        assert "Sources skipped — Confluence (CONFLUENCE_SPACE_KEY not set)" in text

    def test_broadcast_surfaces_stay_silent_about_a_deliberate_non_choice(self):
        # Nothing here was asked for. Saying so on every standup forever is a nag,
        # and Slack/email are exactly where a nag cannot be ignored.
        from yeaboi.standup.render import format_standup_plaintext

        report = _report(
            skipped_sources=(
                ("github", "GITHUB_TOKEN not set"),
                ("local_git", "no repo path configured"),
                ("notion", "NOTION_ROOT_PAGE_ID not set"),
            ),
            unmet_sources=(),
        )
        assert "Sources skipped" not in format_standup_plaintext(report)
        assert "Sources skipped" not in build_standup_markdown(report)

    def test_a_broadcast_names_only_the_unmet_subset(self):
        from yeaboi.standup.render import format_standup_plaintext

        report = _report(
            skipped_sources=(
                ("github", "selected, but no organisations or repositories in scope"),
                ("local_git", "no repo path configured"),
            ),
            unmet_sources=("github",),
        )
        text = format_standup_plaintext(report)
        assert "GitHub (selected, but no organisations or repositories in scope)" in text
        assert "Local Git" not in text

    def test_html_details_still_list_every_skip(self):
        # The diagnostic surface keeps the full picture — this is the one place a
        # reader goes on purpose to find out what was not scanned.
        report = island(
            build_standup_html(
                _report(
                    skipped_sources=(
                        ("notion", "NOTION_ROOT_PAGE_ID not set"),
                        ("local_git", "no repo path configured"),
                    ),
                    unmet_sources=(),
                )
            )
        )
        assert report["report"]["skipped"] == [
            ["notion", "NOTION_ROOT_PAGE_ID not set"],
            ["local_git", "no repo path configured"],
        ]

    def test_every_surface_names_a_source_the_same_way(self):
        # The progress steps label sources; a report that says "azdo_repos" looks
        # like a different source from the one the steps just named.
        from yeaboi.standup.render import format_standup_plaintext

        report = _report(skipped_sources=(("azdo_repos", "not selected in setup"),), unmet_sources=("azdo_repos",))
        assert "Azure DevOps code" in build_standup_markdown(report)
        assert "Azure DevOps code" in format_standup_plaintext(report)

    def test_no_skipped_sources_no_line(self):
        from yeaboi.standup.render import format_standup_plaintext

        assert "Sources skipped" not in format_standup_plaintext(_report())


class TestSharedDesignSystem:
    def test_standup_html_uses_shared_theme(self):
        html = build_standup_html(_report())
        assert 'data-theme="midnight"' in html
        assert "yeaboi-export-theme" in html  # theme switcher present
        assert_self_contained(html)


def _history(*rows):
    """Store-shaped history rows, newest-first like StandupStore.get_history."""
    out = []
    for day, pct, *rest in rows:
        out.append(
            {
                "id": len(out),
                "run_at": f"{day}T10:00:00",
                "standup_date": day,
                "sprint_day": 1,
                "confidence_pct": pct,
                "status": rest[0] if rest else "success",
            }
        )
    return out


class TestVisuals:
    def test_trend_present_with_history(self):
        html = build_standup_html(
            _report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70), ("2026-07-08", 65))
        )
        trend = island(html)["report"]["trend"]
        assert trend["title"] == "Confidence trend"
        # A percentage cannot exceed 100, so the drawn domain says so.
        assert trend["floor"] == 0 and trend["ceiling"] == 100

    def test_trend_absent_without_two_points(self):
        assert island(build_standup_html(_report()))["report"]["trend"] is None
        one = build_standup_html(_report(), history=_history(("2026-07-10", 82)))
        assert island(one)["report"]["trend"] is None

    def test_trend_is_oldest_first(self):
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-01", 50)))
        assert island(html)["report"]["trend"]["points"][0] == ["2026-07-01", 50]

    def test_trend_skips_failed_and_dedupes_and_ignores_future(self):
        history = _history(
            ("2026-07-12", 90),  # after report.date → ignored
            ("2026-07-10", 82),
            ("2026-07-10", 40),  # older rerun of same day → deduped
            ("2026-07-09", 0, "failed"),  # failed → skipped
            ("2026-07-08", 60),
        )
        points = island(build_standup_html(_report(), history=history))["report"]["trend"]["points"]
        assert points == [["2026-07-08", 60], ["2026-07-10", 82]]

    def test_confidence_label_travels_for_the_end_dot(self):
        # The dot's colour is the bundle's business; the label it derives from
        # is the server's, and this is the only thing that has to cross.
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70)))
        assert island(html)["report"]["confidence"]["label"] == "At risk"

    def test_sprint_progress_is_derivable(self):
        report = island(build_standup_html(_report()))["report"]
        assert report["sprint"]["day"] == 3 and report["sprint"]["total"] == 10
        no_days = island(build_standup_html(_report(sprint_total_days=0, sprint_day=0)))["report"]
        assert no_days["sprint"]["total"] == 0  # nothing to draw a bar from

    def test_team_activity_counts_per_member(self):
        rep = _report(
            member_updates=(
                MemberUpdate(name="Alice", summary="x", ticketing_activity_count=3, code_activity_count=2),
                MemberUpdate(name="Bob", summary="y", documentation_activity_count=1),
                MemberUpdate(name="Zed", summary="quiet"),  # all-zero → no bar row
            )
        )
        counts = {m["name"]: m["counts"] for m in island(build_standup_html(rep))["report"]["members"]}
        assert counts == {"Alice": [3, 2, 0], "Bob": [0, 0, 1], "Zed": [0, 0, 0]}

    def test_activity_counts_by_source(self):
        assert island(build_standup_html(_report()))["report"]["activityCounts"] == [["github", 2], ["jira", 1]]

    def test_coverage_statuses_travel_as_words(self):
        rep = _report(category_coverage=(("ticketing", "covered"), ("documentation", "not_configured")))
        assert island(build_standup_html(rep))["report"]["coverage"] == [
            ["ticketing", "covered"],
            ["documentation", "not_configured"],
        ]

    def test_member_name_is_never_markup(self):
        rep = _report(member_updates=(MemberUpdate(name="<img src=x>", summary="x"),))
        html = build_standup_html(rep)
        assert "<img src=x>" not in html
        assert island(html)["report"]["members"][0]["name"] == "<img src=x>"

    def test_self_contained_with_history(self):
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70)))
        assert_self_contained(html)


class TestDayOverDayExport:
    def _rep(self, **over):
        base = dict(
            confidence_delta=-8,
            confidence_trend="declining",
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="login page",
                    progress_note="Still on PSOT-9 from the last standup.",
                    outlook="Likely to wrap up PSOT-9 today.",
                    ticketing_links=(("PSOT-9", "https://acme.atlassian.net/browse/PSOT-9"),),
                ),
            ),
        )
        base.update(over)
        return _report(**base)

    def test_markdown_progress_and_outlook_bullets(self):
        md = build_standup_markdown(self._rep())
        assert "- **Since last standup:** Still on [PSOT-9]" in md
        assert "- **Outlook:** Likely to wrap up [PSOT-9]" in md

    def test_markdown_confidence_trend_suffix(self):
        md = build_standup_markdown(self._rep())
        assert "(▼ 8 vs last standup)" in md
        md_up = build_standup_markdown(self._rep(confidence_delta=6, confidence_trend="improving"))
        assert "(▲ +6 vs last standup)" in md_up

    def test_markdown_no_trend_no_suffix(self):
        md = build_standup_markdown(self._rep(confidence_delta=0, confidence_trend=""))
        assert "vs last standup" not in md

    def test_html_progress_note_and_outlook_are_linkified(self):
        member = island(build_standup_html(self._rep()))["report"]["members"][0]
        link = {"s": "PSOT-9", "href": "https://acme.atlassian.net/browse/PSOT-9"}
        # Ticket keys inside both prose fields become link runs.
        assert link in member["progressNote"]
        assert link in member["outlook"]

    def test_html_trend_chip(self):
        html = build_standup_html(self._rep())
        assert "▼ 8 vs last standup" in html
        html_up = build_standup_html(self._rep(confidence_delta=6, confidence_trend="improving"))
        assert "▲ +6 vs last standup" in html_up

    def test_html_no_trend_no_chip(self):
        html = build_standup_html(self._rep(confidence_delta=0, confidence_trend=""))
        assert "vs last standup" not in html

    def test_html_escapes_hostile_fields(self):
        rep = self._rep(
            member_updates=(MemberUpdate(name="Alice", summary="x", progress_note="<b>bold</b>", outlook="<i>it</i>"),),
        )
        html = build_standup_html(rep)
        assert "<b>bold</b>" not in html
        assert "<i>it</i>" not in html

    def test_empty_fields_are_absent_not_empty(self):
        member = island(build_standup_html(_report()))["report"]["members"][0]
        assert "progressNote" not in member and "outlook" not in member


class TestCardReadability:
    """Sentence-split bullets, link chips, and the adaptive category grid."""

    def test_summary_splits_into_bullets(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary=(
                        "PSOT-1593 was moved to In Progress. Several sub-tasks remain in To Do; "
                        "the access-key work is In Progress."
                    ),
                    ticketing_activity_count=3,
                ),
            ),
        )
        category = island(build_standup_html(rep))["report"]["members"][0]["categories"][0]
        assert [_md_runs(item) for item in category["items"]] == [
            "PSOT-1593 was moved to In Progress.",
            "Several sub-tasks remain in To Do",
            "the access-key work is In Progress.",
        ]

    def test_leftover_links_render_as_chip_row(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="Moved PSOT-1 forward.",
                    ticketing_links=(
                        ("PSOT-2", "https://j/browse/PSOT-2"),
                        ("PSOT-3", "https://j/browse/PSOT-3"),
                    ),
                    ticketing_activity_count=3,
                ),
            ),
        )
        category = island(build_standup_html(rep))["report"]["members"][0]["categories"][0]
        # PSOT-1 is inline in the prose, so only the two unmentioned keys are
        # left over as evidence chips.
        assert category["links"] == [
            ["PSOT-2", "https://j/browse/PSOT-2"],
            ["PSOT-3", "https://j/browse/PSOT-3"],
        ]

    def test_canonical_empty_state_is_suppressed_not_a_footnote(self):
        # "No documentation activity detected…" is a report-wide coverage fact
        # the Details section states once; repeating it per card buried the
        # members who did something.
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="Moved PSOT-1 forward.",
                    ticketing_activity_count=2,
                    documentation_summary="No documentation activity detected in the selected sources.",
                    documentation_activity_count=0,
                ),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert [c["label"] for c in member["categories"]] == ["Ticketing"]
        assert member["footnotes"] == []
        md = build_standup_markdown(rep)
        assert "No documentation activity detected" not in md

    def test_bespoke_empty_category_prose_still_becomes_footnote(self):
        # Only the canonical machine sentences are droppable; an LLM that said
        # something of its own about a quiet category keeps its footnote.
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="Moved PSOT-1 forward.",
                    ticketing_activity_count=2,
                    documentation_summary="Nothing published, though two drafts are in review.",
                    documentation_activity_count=0,
                ),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert member["footnotes"] == [
            {
                "label": "Documentation",
                "runs": [{"s": "Nothing published, though two drafts are in review."}],
            }
        ]

    def test_canonical_not_configured_is_suppressed_but_bespoke_wording_survives(self):
        # The canonical "Documentation sources not configured." is a coverage
        # fact — the Details line states it (as "not configured") once for the
        # whole report, so per-card copies drop. Bespoke wording is a footnote.
        from yeaboi.standup import categories as categories_mod

        canonical = categories_mod.empty_summary("documentation", categories_mod.NOT_CONFIGURED)
        base = dict(name="Alice", summary="x", ticketing_summary="Moved PSOT-1 forward.", ticketing_activity_count=1)
        rep = _report(member_updates=(MemberUpdate(**base, documentation_summary=canonical),))
        assert island(build_standup_html(rep))["report"]["members"][0]["footnotes"] == []

        bespoke = "Documentation sources are not configured for this standup."
        rep = _report(member_updates=(MemberUpdate(**base, documentation_summary=bespoke),))
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert _md_runs(member["footnotes"][0]["runs"]) == bespoke

    def _quiet_member(self, name: str = "Quiet") -> MemberUpdate:
        return MemberUpdate(
            name=name,
            summary="No activity detected.",
            ticketing_summary="No ticketing activity detected in the selected sources.",
            code_summary="No code activity detected in the selected repositories.",
            documentation_summary="No documentation activity detected in the selected sources.",
        )

    def test_all_quiet_member_collapses_into_the_quiet_strip(self):
        # A card that would say nothing but "No activity detected" is not a
        # card: the name moves to `quietMembers` and the markdown gets one
        # shared line, so two silent people cost two words, not two sections.
        rep = _report(
            member_updates=(
                MemberUpdate(name="Alice", summary="Moved PSOT-1 forward.", ticketing_activity_count=1),
                self._quiet_member("Quiet"),
                self._quiet_member("Silent"),
            ),
        )
        report = island(build_standup_html(rep))["report"]
        assert [m["name"] for m in report["members"]] == ["Alice"]
        assert report["quietMembers"] == ["Quiet", "Silent"]
        md = build_standup_markdown(rep)
        assert "### Quiet" not in md
        assert "_No activity detected: Quiet, Silent._" in md

    def test_member_with_a_hand_edited_category_summary_keeps_the_full_card(self):
        # A host can edit ticketing/code/documentation summaries on a share;
        # the downloaded copy renders through this same predicate, so an edited
        # sentence on a zero-activity member must not vanish into the strip.
        edited = replace(self._quiet_member("Edited"), ticketing_summary="Actually shipped the audit fix offline.")
        rep = _report(member_updates=(edited,))
        report = island(build_standup_html(rep))["report"]
        assert [m["name"] for m in report["members"]] == ["Edited"]
        assert report["quietMembers"] == []

    def test_member_behind_a_failed_source_keeps_the_card_and_its_caveat(self):
        # On a day Jira 401s, "No activity detected: Bo" would be a positive
        # claim nobody verified — the FAILED sentence is not a droppable empty
        # state, so the member keeps a card and the caveat keeps its footnote.
        from yeaboi.standup import categories as categories_mod

        failed = categories_mod.empty_summary("ticketing", categories_mod.FAILED)
        member = replace(self._quiet_member("Bo"), ticketing_summary=failed)
        rep = _report(member_updates=(member,))
        report = island(build_standup_html(rep))["report"]
        assert [m["name"] for m in report["members"]] == ["Bo"]
        assert report["quietMembers"] == []
        assert any(failed in _md_runs(f["runs"]) for f in report["members"][0]["footnotes"])

    def test_member_with_a_practice_or_blocker_keeps_the_full_card(self):
        # A votable signal or a blocker must never disappear into the strip.
        from yeaboi.agent.state import PracticeSignal

        signal = PracticeSignal(rule="untracked-work", title="Untracked work", detail="d")
        blocked = replace(self._quiet_member("Blocked"), blockers="Waiting on infra.")
        flagged = replace(self._quiet_member("Flagged"), practices=(signal,))
        rep = _report(member_updates=(blocked, flagged))
        report = island(build_standup_html(rep))["report"]
        assert [m["name"] for m in report["members"]] == ["Blocked", "Flagged"]
        assert report["quietMembers"] == []

    def test_editable_share_keeps_quiet_members_as_cards(self):
        # The strip has no edit anchors; a host correcting the record needs the card.
        rep = _report(member_updates=(self._quiet_member("Quiet"),))
        payload = export.standup_export_args(rep, editable=True)["report"]
        assert [m["name"] for m in payload["members"]] == ["Quiet"]
        assert payload["quietMembers"] == []

    def test_links_only_category_still_gets_column(self):
        # Evidence links with no prose (legacy-ish shape) must not vanish.
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    code_links=(("PR 42", "https://g/pull/42"),),
                ),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert member["categories"] == [
            {"label": "Code", "items": [], "links": [["PR 42", "https://g/pull/42"]], "evidence": []}
        ]

    def test_bullets_still_linkify_ticket_keys(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="PSOT-9 moved to review; PSOT-14 pulled in.",
                    ticketing_links=(("PSOT-9", "https://j/browse/PSOT-9"),),
                    ticketing_activity_count=2,
                ),
            ),
        )
        category = island(build_standup_html(rep))["report"]["members"][0]["categories"][0]
        assert category["items"][0][0] == {"s": "PSOT-9", "href": "https://j/browse/PSOT-9"}


def _evidence(**over) -> ActivityEvidence:
    base = dict(
        kind="commit",
        key="78e4201d",
        title="Fix login redirect",
        url="https://g/c1",
        repository="yeaboi/web",
        status="",
        timestamp="2026-07-30T09:15:00",
    )
    base.update(over)
    return ActivityEvidence(**base)


class TestEvidence:
    """Structured evidence rows: the SHA-chip replacement."""

    def test_evidence_travels_with_renamed_keys(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    code_summary="Merged the login fix.",
                    code_activity_count=1,
                    code_evidence=(_evidence(),),
                ),
            ),
        )
        category = island(build_standup_html(rep))["report"]["members"][0]["categories"][0]
        assert category["evidence"] == [
            {
                "kind": "commit",
                "key": "78e4201d",
                "title": "Fix login redirect",
                "url": "https://g/c1",
                "repo": "yeaboi/web",
                "status": "",
                "time": "2026-07-30T09:15:00",
                "children": [],
                "type": "",
                "parent": "",
                "subtask": False,
                "tickets": [],
            }
        ]

    def test_hostile_url_degrades_but_row_survives(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    code_activity_count=1,
                    code_evidence=(_evidence(url="javascript:alert(1)"),),
                ),
            ),
        )
        row = island(build_standup_html(rep))["report"]["members"][0]["categories"][0]["evidence"][0]
        assert row["url"] == ""
        assert row["title"] == "Fix login redirect"

    def test_category_earns_column_on_evidence_alone(self):
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="x", code_evidence=(_evidence(),)),),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert [c["label"] for c in member["categories"]] == ["Code"]

    def test_evidence_payload_tolerates_plain_dicts(self):
        # A report that round-tripped through a generic asdict/JSON path hands
        # the exporter dicts, not dataclasses.
        as_dict = {
            "kind": "pr",
            "key": "#91",
            "title": "Enable SSO",
            "url": "https://g/pr/91",
            "repository": "yeaboi/web",
            "status": "merged",
            "timestamp": "",
        }
        assert export._evidence_payload([as_dict])[0]["repo"] == "yeaboi/web"

    def test_hierarchy_facts_travel_on_the_wire(self):
        # Dataclass-shaped: the trio + named keys, under the wire spellings.
        row = export._evidence_payload(
            [_evidence(kind="issue", key="PSOT-3", issue_type="Sub-task", parent_key="PSOT-1", subtask=True)]
        )[0]
        assert (row["type"], row["parent"], row["subtask"]) == ("Sub-task", "PSOT-1", True)
        pr = export._evidence_payload([_evidence(kind="pr", key="#91", ticket_keys=("PSOT-1", "#77"))])[0]
        assert pr["tickets"] == ["PSOT-1", "#77"]
        # Dict-shaped (asdict/JSON round-trip) reads the same fields.
        as_dict = {"kind": "issue", "key": "PSOT-3", "issue_type": "Sub-task", "parent_key": "PSOT-1", "subtask": True}
        row = export._evidence_payload([as_dict])[0]
        assert (row["type"], row["parent"], row["subtask"]) == ("Sub-task", "PSOT-1", True)
        # Legacy rows without the fields default rather than fail.
        legacy = export._evidence_payload([{"kind": "issue", "key": "PSOT-1"}])[0]
        assert (legacy["type"], legacy["parent"], legacy["subtask"], legacy["tickets"]) == ("", "", False, [])

    def test_duplicate_pr_merge_rows_collapse_on_reexport(self):
        # Reports stored before the engine deduped merge commits carry the
        # branch-side and target-side merges as two rows — same subject,
        # different SHAs. Re-exports of history deserve one merge, one row.
        rows = (
            _evidence(key="e8bc280c", url="https://a/c/1", title="Merge pull request 48780 from psot/x"),
            _evidence(key="31a595f1", url="https://a/c/2", title="Merge pull request 48780 from psot/x"),
            _evidence(key="abc123", url="https://a/c/3", title="Bound the history table"),
        )
        payload = export._evidence_payload(rows)
        assert [r["key"] for r in payload] == ["e8bc280c", "abc123"]
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="x", code_activity_count=3, code_evidence=rows),),
        )
        md = build_standup_markdown(rep)
        assert md.count("Merge pull request 48780") == 1

    def test_duplicate_merges_collapse_under_a_pr_too(self):
        # The dedupe is standup's reference grammar, not a top-level tidy-up: two
        # rows are the same merge wherever they sit, including folded under the PR
        # they belong to. The projection is shared, so the grammar is handed to it.
        dupes = (
            _evidence(key="e8bc280c", url="https://a/c/1", title="Merge pull request 48780 from psot/x"),
            _evidence(key="31a595f1", url="https://a/c/2", title="Merge pull request 48780 from psot/x"),
            _evidence(key="abc123", url="https://a/c/3", title="Bound the history table"),
        )
        parent = _evidence(kind="pr", key="#48780", url="https://a/pr/1", title="Ship it", children=dupes)

        (row,) = export._evidence_payload([parent])

        assert [c["key"] for c in row["children"]] == ["e8bc280c", "abc123"]

    def test_markdown_renders_nested_evidence_bullets_with_cap(self):
        rows = tuple(_evidence(key=f"#{i}", url=f"https://g/pr/{i}", title=f"Change {i}") for i in range(6))
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    code_summary="Merged six PRs.",
                    code_activity_count=6,
                    code_evidence=rows,
                ),
            ),
        )
        md = build_standup_markdown(rep)
        # The prose one-liner is dropped when evidence rows exist — it is an
        # LLM restatement of the same rows, and rendered every fact twice.
        assert "- **Code:**" in md
        assert "Merged six PRs." not in md
        assert "  - [#0](https://g/pr/0) Change 0 · yeaboi/web" in md
        assert "  - [#3](https://g/pr/3) Change 3 · yeaboi/web" in md
        assert "#4" not in md  # capped at 4 rows
        assert "  - …and 2 more" in md

    def test_markdown_legacy_report_keeps_ref_join(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    code_summary="Merged the login fix.",
                    code_links=(("78e4201d", "https://g/c1"),),
                    code_activity_count=1,
                ),
            ),
        )
        md = build_standup_markdown(rep)
        assert "- **Code:** Merged the login fix. — [78e4201d](https://g/c1)" in md


class TestEvidenceChildren:
    """Commits folded under their PR — the breakdown, not N flat rows."""

    def _pr_with_commits(self, n=2):
        commits = tuple(
            _evidence(key=f"aaa{i}", title=f"Commit {i}", url=f"https://g/c/{i}", timestamp=f"2026-07-31T1{i}:00:00")
            for i in range(n)
        )
        return _evidence(
            kind="pr", key="!91", title="Enable SSO", url="https://g/pr/91", status="merged", children=commits
        )

    def test_children_travel_nested_with_renamed_keys(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice", summary="x", code_activity_count=3, code_evidence=(self._pr_with_commits(),)
                ),
            ),
        )
        row = island(build_standup_html(rep))["report"]["members"][0]["categories"][0]["evidence"][0]
        assert [c["key"] for c in row["children"]] == ["aaa0", "aaa1"]
        assert row["children"][0]["repo"] == "yeaboi/web"
        assert row["children"][0]["children"] == []

    def test_markdown_pr_line_carries_commit_breakdown(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    code_summary="Merged the SSO PR.",
                    code_activity_count=5,
                    code_evidence=(self._pr_with_commits(4),),
                ),
            ),
        )
        md = build_standup_markdown(rep)
        assert "  - [!91](https://g/pr/91) Enable SSO · yeaboi/web — merged — 4 commits" in md
        assert "    - [aaa0](https://g/c/0) Commit 0" in md
        assert "    - [aaa2](https://g/c/2) Commit 2" in md
        assert "aaa3" not in md  # child cap of 3
        assert "    - …and 1 more" in md

    def test_markdown_escapes_brackets_when_a_title_is_the_link_label(self):
        # Tracker titles travel inside [ ] now (doc rows, first mentions); a
        # bracketed title must not corrupt the link syntax on Notion/GitHub.
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    documentation_summary="Edited the runbook.",
                    documentation_activity_count=1,
                    documentation_evidence=(
                        _evidence(kind="page", key="42", title="[Draft] MFA Runbook", url="https://c/p", repository=""),
                    ),
                ),
            ),
        )
        md = build_standup_markdown(rep)
        assert "[\\[Draft\\] MFA Runbook](https://c/p)" in md

    def test_markdown_doc_row_links_the_title_not_the_page_id(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    documentation_summary="Edited the runbook.",
                    documentation_activity_count=1,
                    documentation_evidence=(
                        _evidence(kind="page", key="1892385692", title="MFA Runbook", url="https://c/p", repository=""),
                    ),
                ),
            ),
        )
        md = build_standup_markdown(rep)
        assert "  - [MFA Runbook](https://c/p)" in md
        assert "1892385692" not in md


class TestTeamSummaryRendersVerbatim:
    """Exporters never run the fuzzy rationale-echo strip.

    ``team_summary`` is host-editable on a share; a downstream 70%-overlap
    strip could silently delete a sentence a human wrote about sprint status.
    The strip is generation-time only (`engine._strip_rationale_echo`), so
    whatever the stored report says — LLM output or a host's edit — is what
    every surface renders.
    """

    def test_a_sentence_overlapping_the_rationale_survives_every_surface(self):
        rep = _report(
            team_summary=(
                "We are on day 2 of 10 with 0 of ~3 ideal points burned, which is why I am "
                "flagging the API work. Alice shipped the exporter."
            ),
            confidence_rationale="Day 2 of 10: 0 of ~3 ideal points burned (0%).",
        )
        md = build_standup_markdown(rep)
        assert "flagging the API work" in md
        payload = island(build_standup_html(rep))["report"]
        assert len(payload["summary"]) == 2


class TestSummaryBullets:
    """The member intro ships as terse clause bullets, one run-list each."""

    def test_multi_clause_summary_becomes_bullets(self):
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="Closed the login work; continuing the audit fix."),),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert [runs[0]["s"] for runs in member["summary"]] == ["Closed the login work", "continuing the audit fix."]

    def test_markdown_multi_clause_summary_is_a_list(self):
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="Closed the login work; continuing the audit fix."),),
        )
        md = build_standup_markdown(rep)
        assert "- Closed the login work" in md
        assert "- continuing the audit fix." in md

    def test_bullets_re_mentioning_only_covered_tickets_are_dropped(self):
        # Real-run shape: "Edited PSOT-1639" then "continuing PSOT-1639 in
        # progress" is one fact twice. A clause naming any NEW key survives.
        # The links put both keys in the report's key map — dedupe is gated on
        # keys the tracker actually produced.
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="Edited PSOT-1639; continuing PSOT-1639 in progress; carrying PSOT-1638 through review.",
                    ticketing_links=(
                        ("PSOT-1639", "https://j/browse/PSOT-1639"),
                        ("PSOT-1638", "https://j/browse/PSOT-1638"),
                    ),
                    ticketing_activity_count=2,
                ),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        bullets = ["".join(run["s"] for run in runs) for runs in member["summary"]]
        assert bullets[0].startswith("Edited PSOT-1639")
        assert bullets[1].startswith("carrying PSOT-1638")
        assert len(bullets) == 2
        md = build_standup_markdown(rep)
        assert "continuing" not in md

    def test_keyless_bullets_are_never_deduped(self):
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="Paired on the migration; paired on the migration."),),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert len(member["summary"]) == 2

    def test_lookalike_keys_never_gate_a_bullet(self):
        # "UTF-8" matches the key regex but no tracker produced it — the second
        # clause is its own fact and must survive.
        rep = _report(
            member_updates=(
                MemberUpdate(name="Alice", summary="Fixed the UTF-8 encoder; added UTF-8 round-trip tests."),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        assert len(member["summary"]) == 2


class TestFirstMentionTitles:
    """The first linked mention of a ticket in a card carries its title."""

    def _report_with_titles(self, summary, outlook=""):
        return _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary=summary,
                    outlook=outlook,
                    ticketing_summary="Ticket movement.",
                    ticketing_links=(("PSOT-9", "https://j/browse/PSOT-9"),),
                    ticketing_activity_count=1,
                    ticketing_evidence=(
                        _evidence(kind="update", key="PSOT-9", title="Fix login", url="https://j/browse/PSOT-9"),
                    ),
                ),
            ),
        )

    def test_first_mention_titled_then_bare(self):
        rep = self._report_with_titles("Closed PSOT-9.", outlook="Nothing left on PSOT-9.")
        member = island(build_standup_html(rep))["report"]["members"][0]
        first = next(r for r in member["summary"][0] if r.get("href"))
        again = next(r for r in member["outlook"] if r.get("href"))
        assert first["s"] == "PSOT-9 Fix login"
        assert again["s"] == "PSOT-9"

    def test_markdown_gets_the_same_enrichment(self):
        md = build_standup_markdown(self._report_with_titles("Closed PSOT-9."))
        assert "[PSOT-9 Fix login](https://j/browse/PSOT-9)" in md

    def test_key_without_a_collected_title_stays_bare(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="Closed PSOT-9.",
                    ticketing_links=(("PSOT-9", "https://j/browse/PSOT-9"),),
                    ticketing_activity_count=1,
                ),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        linked = next(r for r in member["summary"][0] if r.get("href"))
        assert linked["s"] == "PSOT-9"

    def test_long_titles_are_trimmed(self):
        long_title = "A" * 90
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="Closed PSOT-9.",
                    ticketing_links=(("PSOT-9", "https://j/browse/PSOT-9"),),
                    ticketing_activity_count=1,
                    ticketing_evidence=(
                        _evidence(kind="update", key="PSOT-9", title=long_title, url="https://j/browse/PSOT-9"),
                    ),
                ),
            ),
        )
        member = island(build_standup_html(rep))["report"]["members"][0]
        linked = next(r for r in member["summary"][0] if r.get("href"))
        assert linked["s"].endswith("…")
        assert len(linked["s"]) <= len("PSOT-9 ") + 60


def _signal(**over):
    from yeaboi.agent.state import PracticeSignal

    base = dict(
        rule="untracked-work",
        title="Untracked work",
        detail="#91 'Add retry' carries no ticket reference in the branch, title, or description.",
        evidence=(("#91", "https://example.invalid/pull/91"),),
    )
    base.update(over)
    return PracticeSignal(**base)


class TestWindowBounds:
    def test_payload_carries_the_window_verbatim(self):
        report = _report(
            activity_window_start="2026-07-12T00:00:00+02:00",
            activity_window_end="2026-07-13T10:30:00+02:00",
        )
        data = island(build_standup_html(report))["report"]
        assert data["window"] == {"start": "2026-07-12T00:00:00+02:00", "end": "2026-07-13T10:30:00+02:00"}

    def test_window_is_always_present_and_empty_on_a_legacy_report(self):
        # A report stored before the timeline existed re-exports forever with
        # empty bounds — the page derives the axis from event times instead.
        data = island(build_standup_html(_report()))["report"]
        assert data["window"] == {"start": "", "end": ""}


class TestPracticesInExports:
    def _report_with_practices(self, *signals, rollup=(("untracked-work", 1),)):
        return _report(
            member_updates=(MemberUpdate(name="Alice", summary="login page", practices=tuple(signals)),),
            practice_rollup=rollup,
        )

    def test_markdown_renders_the_signal_and_its_evidence(self):
        md = build_standup_markdown(self._report_with_practices(_signal()))
        assert "**Untracked work:**" in md
        assert "carries no ticket reference" in md
        assert "https://example.invalid/pull/91" in md

    def test_markdown_marks_a_repeat(self):
        md = build_standup_markdown(self._report_with_practices(_signal(repeat=True)))
        assert "again today" in md

    def test_markdown_has_no_practice_bullet_when_there_are_none(self):
        assert "Untracked work" not in build_standup_markdown(_report())

    def test_payload_omits_practices_when_empty(self):
        data = island(build_standup_html(_report()))["report"]
        assert all("practices" not in member for member in data["members"])
        assert data["practices"] == []

    def test_payload_carries_the_signal_as_runs_and_links(self):
        data = island(build_standup_html(self._report_with_practices(_signal())))["report"]
        practice = data["members"][0]["practices"][0]
        assert practice["rule"] == "untracked-work"
        assert practice["title"] == "Untracked work"
        # Prose crosses the wire as runs — no markup, ever.
        assert isinstance(practice["detail"], list)
        assert practice["evidence"] == [["#91", "https://example.invalid/pull/91"]]

    def test_payload_never_carries_the_feedback_handles(self):
        # Internal identity for the feedback ledger. An export is a file with
        # nothing to vote from, so shipping them would be dead weight the
        # reader can neither see nor use.
        data = island(build_standup_html(self._report_with_practices(_signal(handles=("url:https://x/pull/91",)))))
        assert "handles" not in data["report"]["members"][0]["practices"][0]
        assert "url:https://x/pull/91" not in json.dumps(data)

    def test_rollup_carries_its_label_and_a_member_count(self):
        data = island(build_standup_html(self._report_with_practices(_signal())))["report"]
        assert data["practices"] == [{"rule": "untracked-work", "count": 1, "title": "Untracked work"}]

    def test_an_unknown_rule_id_still_gets_a_title(self):
        # The engine owns the vocabulary; a rule the title map has not caught up
        # with must still render as words rather than a raw slug.
        report = self._report_with_practices(_signal(), rollup=(("invented-tomorrow", 2),))
        data = island(build_standup_html(report))["report"]
        assert data["practices"] == [{"rule": "invented-tomorrow", "count": 2, "title": "Invented tomorrow"}]

    def test_ticket_keys_inside_a_practice_detail_linkify(self):
        report = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="login page",
                    ticketing_links=(("PSOT-12", "https://example.invalid/browse/PSOT-12"),),
                    practices=(_signal(detail="PSOT-12 shipped but the board still has it not started."),),
                ),
            ),
        )
        runs = island(build_standup_html(report))["report"]["members"][0]["practices"][0]["detail"]
        assert any(run.get("href") == "https://example.invalid/browse/PSOT-12" for run in runs)

    def test_html_stays_self_contained_with_practices(self):
        assert_self_contained(build_standup_html(self._report_with_practices(_signal())))


class TestConflictCards:
    def _card(self):
        from yeaboi.agent.state import ConflictCard

        return ConflictCard(
            fingerprint="YEA-12:status:status_conflict",
            title="YEA-12 — the board says Done, but a pull request is still open",
            detail="YEA-12 is Done on the board while a PR still names it.",
            severity="medium",
            entity_id="YEA-12",
            property_name="status",
            claims=(("jira", "Done", "YEA-12", "https://j/12"), ("github", "open", "auth fix", "https://g/41")),
            recommended_action="Reopen YEA-12, or merge the pull request.",
            members=("Bob",),
        )

    def test_payload_carries_conflicts_and_nav(self):
        args = export.standup_export_args(_report(conflicts=(self._card(),)))
        assert ("conflicts", "Conflicts") in args["nav"]
        cards = args["report"]["conflicts"]
        assert len(cards) == 1
        assert cards[0]["fingerprint"] == "YEA-12:status:status_conflict"  # the stable list key
        assert cards[0]["severity"] == "medium"  # a word, never a colour
        assert cards[0]["action"] == "Reopen YEA-12, or merge the pull request."
        assert cards[0]["claims"][0] == {"source": "jira", "value": "Done", "label": "YEA-12", "url": "https://j/12"}
        assert cards[0]["members"] == ["Bob"]

    def test_clean_day_keeps_the_key_but_not_the_nav(self):
        # The key is always emitted (the fixture guard needs to see it); the
        # nav entry only exists when there is a section to jump to.
        args = export.standup_export_args(_report())
        assert args["report"]["conflicts"] == []
        assert ("conflicts", "Conflicts") not in args["nav"]

    def test_markdown_renders_a_conflicts_section(self):
        md = export.build_standup_markdown(_report(conflicts=(self._card(),)))
        assert "## Conflicts" in md
        assert "the board says Done" in md
        assert "[YEA-12](https://j/12)" in md
        assert "Reopen YEA-12" in md

    def test_markdown_has_no_section_on_a_clean_day(self):
        assert "## Conflicts" not in export.build_standup_markdown(_report())

    def test_markdown_neutralises_link_syntax_in_card_text(self):
        # A PR title is attacker-authored text that travels inside card.detail,
        # and this Markdown lands on Notion/Slack where [x](url) is a live
        # link. The bracket syntax must come out neutralised.
        from yeaboi.agent.state import ConflictCard

        card = ConflictCard(
            fingerprint="YEA-12:status:status_conflict",
            title="YEA-12 — the board says Done, but a pull request is still open",
            detail="YEA-12 is Done, while “[Approve access](https://evil.example)” still names it.",
            entity_id="YEA-12",
            claims=(("jira", "Done", "[click](https://evil.example)", ""),),
            recommended_action="Reopen [YEA-12](https://evil.example) maybe.",
        )
        md = export.build_standup_markdown(_report(conflicts=(card,)))
        assert "[Approve access](https://evil.example)" not in md
        assert "[click](https://evil.example)" not in md
        assert "[YEA-12](https://evil.example)" not in md
        assert "\\[Approve access\\]" in md


_OPS = (
    OpsSignal(
        kind="incident",
        family="incidents",
        source="pagerduty",
        count=2,
        resolved=1,
        severity="high",
        services=("checkout",),
        window_start="2026-06-26T00:00:00+00:00",
        window_end="2026-07-10T00:00:00+00:00",
        samples=("Checkout latency [above SLO](javascript:alert(1))",),
    ),
)


class TestProductionExport:
    def test_no_section_at_all_when_nothing_is_connected(self):
        assert "Production" not in build_standup_markdown(_report())

    def test_the_markdown_section_names_counts_and_its_own_window(self):
        md = build_standup_markdown(_report(ops_signals=_OPS))
        assert "## Production (since 2026-06-26)" in md
        assert "2 incidents via pagerduty" in md
        assert "Team-wide; not attributed to anyone." in md

    def test_a_monitor_name_cannot_mint_a_link(self):
        # Samples are vendor text an outsider can author, and this Markdown
        # lands on Notion/Confluence/Slack where `[x](url)` goes live. The
        # brackets come back escaped, so the label never closes a link.
        md = build_standup_markdown(_report(ops_signals=_OPS))
        assert "Checkout latency \\[above SLO\\](javascript:alert(1))" in md

    def test_the_html_payload_carries_words_and_numbers_only(self):
        production = island(build_standup_html(_report(ops_signals=_OPS)))["report"]["production"]
        assert production[0]["count"] == 2 and production[0]["severity"] == "high"
        assert production[0]["window"]["start"] == "2026-06-26T00:00:00+00:00"
        # No colour, no markup, and no field a person could ride in.
        assert not {"accent", "colour", "color", "html", "author", "member"} & set(production[0])

    def test_the_nav_earns_its_entry(self):
        # The nav is drawn by the bundle, so the claim is about the payload.
        def nav_keys(report):
            return [key for key, _ in island(build_standup_html(report))["chrome"]["nav"]]

        assert "production" not in nav_keys(_report())
        assert "production" in nav_keys(_report(ops_signals=_OPS))


class TestSoloExport:
    def test_a_solo_report_has_no_team_summary_heading(self):
        md = build_standup_markdown(_report(solo=True))
        assert "## Summary" in md
        assert "Team Summary" not in md
        assert "## Team Summary" in build_standup_markdown(_report())
