"""Unit tests for reporting/export — Markdown, HTML, and file writing."""

from tests._pages import island, markup
from yeaboi.agent.state import DeliveredItem, DeliveryReport
from yeaboi.reporting import export


def _report():
    return DeliveryReport(
        period_label="Last sprint",
        period_start="2026-06-29",
        period_end="2026-07-13",
        project_name="Acme Portal",
        sprint_names=("Sprint 12",),
        headline="Shipped SSO.",
        executive_summary="We delivered single sign-on.",
        themes=(("Security", ("SSO login", "MFA rollout")),),
        highlights=("SSO live for all users",),
        metrics=(("Items delivered", "7"), ("Contributors", "3")),
        delivered_items=(
            DeliveredItem(
                key="ACME-1", title="SSO <script>alert(1)</script>", status="Done", source="jira", assignee="Ada"
            ),
        ),
        emoji_theme=(("headline", "🚀"), ("metrics", "📊")),
        warnings=("test warning",),
        generated_at="2026-07-13",
    )


class TestMarkdown:
    def test_contains_sections(self):
        md = export.build_report_markdown(_report())
        assert "# 🚀 Delivery Report — Acme Portal" in md
        assert "Last sprint" in md
        assert "By the numbers" in md
        assert "Security" in md
        assert "ACME-1" in md
        assert "test warning" in md

    def test_empty_report_renders(self):
        md = export.build_report_markdown(DeliveryReport(period_label="Last month (~2 sprints)"))
        assert "Delivery Report" in md

    def test_chart_embedded_with_charts_dir(self, tmp_path):
        import pytest

        pytest.importorskip("matplotlib")
        md = export.build_report_markdown(_report(), charts_dir=tmp_path)
        assert f"![Delivered items]({tmp_path / 'delivered.png'})" in md
        assert (tmp_path / "delivered.png").exists()

    def test_no_charts_dir_no_image(self):
        md = export.build_report_markdown(_report())
        assert "![Delivered items]" not in md

    def test_metrics_and_items_are_tables(self):
        md = export.build_report_markdown(_report())
        assert "| Metric | Value |" in md
        assert "| Items delivered | **7** |" in md
        assert "| Key | Title | Status | By |" in md
        assert "| `ACME-1` |" in md and "| Ada |" in md

    def test_branded_footer(self):
        md = export.build_report_markdown(_report())
        assert "🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)" in md

    def test_delivered_counts_by_person_then_status(self):
        by_person = export._delivered_counts(_report())
        assert by_person == [("Ada", 1)]
        unassigned = DeliveryReport(
            delivered_items=(
                DeliveredItem(key="A-1", title="x", status="Done", source="jira"),
                DeliveredItem(key="A-2", title="y", status="Closed", source="jira"),
            )
        )
        assert sorted(export._delivered_counts(unassigned)) == [("Closed", 1), ("Done", 1)]


class TestHtml:
    def test_self_contained_and_untrusted_text_is_data(self):
        html = export.build_report_html(_report())
        assert html.lstrip().startswith("<!DOCTYPE html>")
        assert "<style>" in html  # inline CSS, no external stylesheet
        assert "<script>alert(1)</script>" not in html
        item = island(html)["report"]["items"][0]
        assert item == {
            "key": "ACME-1",
            "title": "SSO <script>alert(1)</script>",
            "status": "Done",
            "assignee": "Ada",
        }

    def test_payload_carries_every_section(self):
        report = island(export.build_report_html(_report()))["report"]
        assert report["headline"] == "Shipped SSO."
        assert report["metrics"] == [["Items delivered", "7"], ["Contributors", "3"]]
        assert report["summary"] == "We delivered single sign-on."
        assert report["themes"] == [{"title": "Security", "outcomes": ["SSO login", "MFA rollout"]}]
        assert report["highlights"] == ["SSO live for all users"]
        assert report["warnings"] == ["test warning"]

    def test_chrome_facts(self):
        boot = island(export.build_report_html(_report()))
        # The headline emoji leads the title, as it does in the Markdown twin.
        assert boot["chrome"]["title"] == "🚀 Delivery Report — Acme Portal"
        assert boot["chrome"]["wordmark"] == "report"
        assert dict(tuple(f) for f in boot["chrome"]["facts"]) == {
            "PERIOD": "Last sprint",
            "DATES": "2026-06-29 → 2026-07-13",
            "DELIVERED": "1",
        }

    def test_emoji_are_the_hosts_choice_not_the_vocabulary(self):
        assert island(export.build_report_html(_report()))["report"]["emoji"] == {
            "headline": "🚀",
            "metrics": "📊",
        }

    def test_noscript_names_the_markdown_twin(self):
        assert "report-last-sprint-2026-07-13.md" in export.build_report_html(_report())


class TestExportReport:
    def test_writes_all_files(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.get_reporting_export_dir", lambda key: tmp_path)
        paths = export.export_report(_report(), theme="aurora")
        try:
            import pptx  # noqa: F401 — docs extra present → the deck rides along

            assert set(paths) == {"markdown", "html", "slides", "pptx"}
            assert paths["pptx"].suffix == ".pptx"
        except ImportError:
            assert set(paths) == {"markdown", "html", "slides"}
        for p in paths.values():
            assert p.exists() and p.stat().st_size > 0
        assert paths["slides"].name.endswith("-slides.html")

    def test_pptx_absent_without_python_pptx(self, tmp_path, monkeypatch):
        """A missing docs extra must degrade to the three HTML/MD files, no crash."""
        monkeypatch.setattr("yeaboi.paths.get_reporting_export_dir", lambda key: tmp_path)
        monkeypatch.setattr("yeaboi.reporting.pptx_export.build_report_pptx", lambda *a, **k: None)
        paths = export.export_report(_report(), theme="aurora")
        assert set(paths) == {"markdown", "html", "slides"}

    def test_export_pptx_only(self, tmp_path, monkeypatch):
        import pytest

        pytest.importorskip("pptx", reason="docs extra not installed")
        monkeypatch.setattr("yeaboi.paths.get_reporting_export_dir", lambda key: tmp_path)
        path = export.export_pptx_only(_report(), theme="mono")
        assert path is not None and path.exists() and path.suffix == ".pptx"

    def test_style_forwarded_to_both_presentation_builders(self, tmp_path, monkeypatch):
        from yeaboi.reporting.style import DeckStyle

        monkeypatch.setattr("yeaboi.paths.get_reporting_export_dir", lambda key: tmp_path)
        seen: dict = {}

        def fake_html(report, *, theme, style=None):
            seen["slides"] = style
            return "<html></html>"

        def fake_pptx(report, path, *, theme, style=None):
            seen["pptx"] = style
            return None

        monkeypatch.setattr("yeaboi.reporting.presentation.build_presentation_html", fake_html)
        monkeypatch.setattr("yeaboi.reporting.pptx_export.build_report_pptx", fake_pptx)
        style = DeckStyle(layout="compact")
        export.export_report(_report(), style=style)
        assert seen["slides"] == style and seen["pptx"] == style

    def test_export_pptx_only_forwards_style(self, tmp_path, monkeypatch):
        from yeaboi.reporting.style import DeckStyle

        monkeypatch.setattr("yeaboi.paths.get_reporting_export_dir", lambda key: tmp_path)
        seen: dict = {}
        monkeypatch.setattr(
            "yeaboi.reporting.pptx_export.build_report_pptx",
            lambda report, path, *, theme, style=None: seen.setdefault("style", style),
        )
        style = DeckStyle(slide_numbers=True)
        export.export_pptx_only(_report(), style=style)
        assert seen["style"] == style

    def test_chart_written_for_markdown_html_uses_inline_bar(self, tmp_path, monkeypatch):
        import pytest

        pytest.importorskip("matplotlib")
        monkeypatch.setattr("yeaboi.paths.get_reporting_export_dir", lambda key: tmp_path)
        paths = export.export_report(_report(), theme="aurora")
        # Markdown links the chart relatively (it lives beside the .md, and
        # flows to Notion/Confluence via export_targets)…
        assert "![Delivered items](delivered.png)" in paths["markdown"].read_text(encoding="utf-8")
        assert (tmp_path / "delivered.png").exists()
        # …while the HTML sends counts and draws its own theme-aware bar, so it
        # never carries the theme-blind PNG.
        html = paths["html"].read_text(encoding="utf-8")
        assert "delivered.png" not in markup(html)
        assert island(html)["report"]["breakdown"] == [["Ada", 1]]


class TestSharedDesignSystem:
    def test_report_html_uses_shared_theme(self):
        html = export.build_report_html(_report())
        assert 'data-theme="midnight"' in html
        assert 'data-mode="reporting"' in html  # the accent, set before first paint
        assert 'src="http' not in html and "<link" not in html  # self-contained


def _history(*rows):
    """Newest-first rows mirroring ReportingStore.get_history output."""
    return [
        {
            "id": i,
            "run_at": f"{d}T17:00:00",
            "period": "sprint",
            "period_end": d,
            "project_name": "Acme Portal",
            "item_count": n,
        }
        for i, (d, n) in enumerate(rows)
    ]


class TestBreakdown:
    def test_breakdown_counts_travel_not_a_chart(self):
        # The bar and its key are drawn from these pairs by one `countedSegments`
        # call, so they cannot disagree about which colour meant which person.
        assert island(export.build_report_html(_report()))["report"]["breakdown"] == [["Ada", 1]]

    def test_breakdown_falls_back_to_status(self):
        rep = DeliveryReport(
            period_label="p",
            period_end="2026-07-13",
            delivered_items=(
                DeliveredItem(key="A-1", title="x", status="Done", source="jira"),
                DeliveredItem(key="A-2", title="y", status="Closed", source="jira"),
            ),
        )
        breakdown = island(export.build_report_html(rep))["report"]["breakdown"]
        assert sorted(breakdown) == [["Closed", 1], ["Done", 1]]


class TestTrend:
    def test_trend_from_history(self):
        history = _history(("2026-07-13", 7), ("2026-06-29", 5), ("2026-06-15", 9))
        trend = island(export.build_report_html(_report(), history=history))["report"]["trend"]
        assert trend["title"] == "Delivery volume trend"
        assert trend["points"][0] == ["2026-06-15", 9]

    def test_other_project_history_excluded(self):
        history = _history(("2026-06-29", 5))
        history.append(
            {
                "id": 9,
                "run_at": "2026-06-01T17:00:00",
                "period": "sprint",
                "period_end": "2026-06-01",
                "project_name": "Other Project",
                "item_count": 40,
            }
        )
        trend = island(export.build_report_html(_report(), history=history))["report"]["trend"]
        assert [day for day, _ in trend["points"]] == ["2026-06-29", "2026-07-13"]

    def test_no_history_no_trend(self):
        assert island(export.build_report_html(_report()))["report"]["trend"] is None

    def test_self_contained_with_history(self):
        html = export.build_report_html(_report(), history=_history(("2026-07-13", 7), ("2026-06-29", 5)))
        assert 'src="http' not in html and "<link" not in html


class TestSupportingSignalsMarkdown:
    def _signals_report(self):
        from dataclasses import replace

        from yeaboi.agent.state import SupportingSignal

        return replace(
            _report(),
            supporting_signals=(
                SupportingSignal(
                    kind="pull_requests", source="github", count=12, samples=("Fix auth (#41)", "SSO (#44)")
                ),
                SupportingSignal(kind="doc_updates", source="confluence", count=3, samples=("Runbook",)),
            ),
        )

    def test_signals_section_rendered(self):
        md = export.build_report_markdown(self._signals_report())
        assert "### Supporting signals" in md
        assert "Corroborated by 12 merged PRs and 3 doc updates" in md
        assert "- **Pull requests · GitHub:** 12" in md
        assert "  - Fix auth (#41)" in md
        assert "- **Doc updates · Confluence:** 3" in md
        # Placement: after metrics, before the executive summary.
        assert md.index("By the numbers") < md.index("### Supporting signals") < md.index("Executive summary")

    def test_no_signals_no_section(self):
        assert "Supporting signals" not in export.build_report_markdown(_report())
