"""Guards on the committed duck sprites.

The mascot layers are generated by ``scripts/gen_duck_sprites.py`` and committed,
because Pillow lives only in the ``charts`` extra and neither ``make web`` nor
``pip install yeaboi`` may depend on it. Committed generated binaries need a
guard, and these are the three failures that would actually happen:

* a layer goes missing, so the duck loses its sunglasses in production only;
* a layer is regenerated at a different size, so the composite shears — the
  three are stacked with ``position: absolute; inset: 0`` and nothing at runtime
  would complain;
* someone drops the full-resolution art back in, quietly adding ~265 KB of
  base64 to every board *and* to each of the ten exported report files.

Dimensions are read straight out of the PNG header rather than through Pillow,
so this runs in the ordinary pytest lane with no extra installed.
"""

from __future__ import annotations

import struct
from pathlib import Path

import pytest

SPRITE_DIR = Path(__file__).resolve().parents[2] / "frontend" / "src" / "assets" / "duck"
LAYERS = ("base", "wing", "glasses")

# The three layers are inlined as data: URIs into every self-contained page.
# base64 costs a third on top, so this ceiling is ~13 KB on the wire. The
# current total is ~5.4 KB; the headroom is for a re-cut, not for the 199 KB
# original.
MAX_TOTAL_BYTES = 10 * 1024


def _png_size(path: Path) -> tuple[int, int]:
    """Width and height from a PNG's IHDR chunk.

    The header is fixed-layout: an 8-byte signature, a 4-byte length, the
    ``IHDR`` tag, then two big-endian uint32s.
    """
    header = path.read_bytes()[:24]
    assert header[:8] == b"\x89PNG\r\n\x1a\n", f"{path.name} is not a PNG"
    width, height = struct.unpack(">II", header[16:24])
    return width, height


@pytest.fixture(scope="module")
def sprites() -> dict[str, Path]:
    return {layer: SPRITE_DIR / f"{layer}.png" for layer in LAYERS}


def test_every_layer_is_present(sprites: dict[str, Path]) -> None:
    missing = [name for name, path in sprites.items() if not path.exists()]
    assert not missing, f"missing duck layers: {missing} — run scripts/gen_duck_sprites.py"


def test_layers_share_one_geometry(sprites: dict[str, Path]) -> None:
    """All three must be pixel-identical in size, or the composite shears.

    They are stacked with ``inset: 0``, so a layer even one pixel off puts the
    sunglasses on the duck's forehead — and it would look merely *odd* rather
    than broken, which is exactly the kind of thing that ships.
    """
    sizes = {name: _png_size(path) for name, path in sprites.items()}
    assert len(set(sizes.values())) == 1, f"duck layers disagree on size: {sizes}"


def test_sprite_is_a_2x_asset(sprites: dict[str, Path]) -> None:
    """128px wide, twice the 64px the rig draws it at."""
    width, _ = _png_size(sprites["base"])
    assert width == 128, f"expected a 128px 2x sprite, got {width}px"


def test_total_stays_inlinable(sprites: dict[str, Path]) -> None:
    total = sum(path.stat().st_size for path in sprites.values())
    assert total <= MAX_TOTAL_BYTES, (
        f"duck sprites total {total / 1024:.1f} KB, over the {MAX_TOTAL_BYTES / 1024:.0f} KB budget. "
        "These are inlined as data: URIs into every page including all ten exports — "
        "re-run scripts/gen_duck_sprites.py rather than committing the source art."
    )
