"""Tests for the shared mode vocabulary and the chrome builder.

``build_chrome`` was lifted out of ``html_theme.export_page`` verbatim so the
live boards and the share gate could draw the same masthead from the same
shape. Several assertions here are about *bytes* rather than behaviour, because
the exports are compared byte-for-byte by the wire-shape guard and an
innocent-looking tidy-up here rewrites ten committed fixtures.
"""

from __future__ import annotations

import json

from yeaboi.web.brand import (
    GATE_BRANDED_MODES,
    MODE_LABELS,
    MODE_WORDMARKS,
    accent_mode,
    build_chrome,
    is_chrome,
)


class TestModeVocabulary:
    def test_every_mode_has_a_label_and_a_wordmark(self):
        assert set(MODE_LABELS) == set(MODE_WORDMARKS)

    def test_wordmarks_are_short_enough_for_the_display_face(self):
        # The face is a grid of block glyphs at roughly three columns a letter,
        # and the shadow face is six rows tall. "Delivery Report" fits nowhere.
        for mode, word in MODE_WORDMARKS.items():
            assert len(word) <= 8, f"{mode}: {word!r} is too long to set"

    def test_wordmarks_are_settable_in_the_display_face(self):
        """A word the glyph table cannot set falls back to the compact face.

        The fallback exists so a new export never renders nothing, but a mode in
        this table is not a surprise — it should be checked here rather than
        discovered as a quietly smaller masthead.
        """
        from yeaboi.ui.shared._ansi_font import SHADOW_GLYPHS

        for mode, word in MODE_WORDMARKS.items():
            missing = {ch for ch in word.upper() if ch not in SHADOW_GLYPHS}
            assert not missing, f"{mode}: {word!r} has no shadow glyph for {missing}"


class TestAccentMode:
    def test_a_mode_with_its_own_accent_keeps_it(self):
        for mode in ("retro", "poker", "standup", "reporting", "planning", "performance", "analysis"):
            assert accent_mode(mode) == mode

    def test_roadmap_borrows_plannings_accent(self):
        assert accent_mode("roadmap") == "planning"

    def test_anonymize_borrows_analysiss_accent(self):
        assert accent_mode("anonymize") == "analysis"

    def test_unknown_modes_get_no_accent(self):
        assert accent_mode("nonsense") == ""
        assert accent_mode("") == ""

    def test_result_is_always_attribute_safe(self):
        """Callers interpolate this into html_attrs, so it is the allowlist."""
        for hostile in ('" onload="alert(1)', "<script>", "retro'", "../.."):
            assert accent_mode(hostile) == ""

    def test_every_accent_mode_is_declared_in_the_stylesheet(self):
        """Two-way: an accent named here with no CSS renders the base accent."""
        from pathlib import Path

        tokens = Path(__file__).resolve().parents[2] / "frontend" / "src" / "design" / "tokens.css"
        css = tokens.read_text(encoding="utf-8")
        for mode in set(MODE_LABELS) | set(MODE_WORDMARKS):
            accent = accent_mode(mode)
            assert accent, f"{mode} resolves to no accent"
            assert f'[data-mode="{accent}"]' in css, f"no accent block for {accent}"


class TestGateBranding:
    def test_performance_stays_anonymous(self):
        """The one mode whose *name* is the disclosure.

        "Somebody's 1:1 or six-month review is behind this door" tells a
        stranger holding the tunnel URL something real about a named colleague.
        "A retro" does not.
        """
        assert "performance" not in GATE_BRANDED_MODES

    def test_every_other_mode_may_name_itself(self):
        assert GATE_BRANDED_MODES == set(MODE_LABELS) - {"performance"}


class TestBuildChrome:
    def test_carries_the_five_always_present_keys(self):
        chrome = build_chrome(mode="retro", title="Sprint Retro", wordmark="retro")
        assert is_chrome(chrome)
        assert chrome["mode"] == "retro"
        assert chrome["frame"] == "yeaboi — retro"
        assert chrome["wordmark"] == "retro"
        assert chrome["title"] == "Sprint Retro"

    def test_footer_defaults_to_the_standard_credit(self):
        assert build_chrome(mode="retro", title="T", wordmark="r")["footer"] == "Generated by yeaboi.ai"

    def test_footer_can_be_overridden(self):
        chrome = build_chrome(mode="x", title="T", wordmark="w", footer="Anonymized with yeaboi.ai")
        assert chrome["footer"] == "Anonymized with yeaboi.ai"

    def test_optional_keys_are_omitted_rather_than_emitted_empty(self):
        """Load-bearing: an absent key and an empty one are different bytes."""
        chrome = build_chrome(mode="retro", title="T", wordmark="r")
        for key in ("subtitle", "facts", "badges", "nav"):
            assert key not in chrome

    def test_facts_drop_empty_values(self):
        chrome = build_chrome(mode="x", title="T", wordmark="w", facts=[("SPRINT", "42"), ("SCOPE", "")])
        assert chrome["facts"] == [["SPRINT", "42"]]

    def test_facts_passed_but_all_empty_still_emit_the_key(self):
        """The asymmetry the fixtures pin — see the comment in build_chrome."""
        chrome = build_chrome(mode="x", title="T", wordmark="w", facts=[("SPRINT", "")])
        assert chrome["facts"] == []

    def test_nav_and_facts_become_lists_not_tuples(self):
        # They cross the wire as JSON, where a tuple would round-trip as a list
        # anyway — building lists keeps the payload and the fixture identical.
        chrome = build_chrome(
            mode="x", title="T", wordmark="w", facts=[("A", "1")], nav=[("s", "Section")], badges=["Beta"]
        )
        assert chrome["facts"] == [["A", "1"]]
        assert chrome["nav"] == [["s", "Section"]]
        assert chrome["badges"] == ["Beta"]

    def test_payload_is_json_serialisable(self):
        chrome = build_chrome(
            mode="standup", title="Daily Standup", wordmark="standup", subtitle="2026-07-31", facts=[("SPRINT", "42")]
        )
        assert json.loads(json.dumps(chrome)) == chrome


class TestExportPageStillDelegates:
    def test_export_page_builds_the_same_chrome(self):
        """The lift must be faithful — this is the assertion that says so."""
        from tests._pages import island
        from yeaboi.html_theme import export_page

        page = export_page(
            mode="standup",
            title="Daily Standup",
            wordmark="standup",
            report={"kind": "standup"},
            subtitle="2026-07-31",
            facts=[("SPRINT", "42"), ("EMPTY", "")],
            badges=["Beta"],
            nav=[("overview", "Overview")],
        )
        assert island(page)["chrome"] == build_chrome(
            mode="standup",
            title="Daily Standup",
            wordmark="standup",
            subtitle="2026-07-31",
            facts=[("SPRINT", "42"), ("EMPTY", "")],
            badges=["Beta"],
            nav=[("overview", "Overview")],
        )
