"""Pin the live snapshot shapes the TypeScript boards are written against.

``types/board.ts`` is hand-written, because a state shape carries meaning a
codegen cannot express — which fields are per-viewer, which one deliberately
does not bump ``revision``, which is a command rather than a value. The cost of
hand-writing it is that nothing stops the server from quietly dropping a field
the bundle still reads, and the symptom of that is a board that renders
``undefined`` to a teammate on a tunnel while every test on both sides passes.

So this drives a **real board through a real round** and writes the snapshots to
``frontend/src/test/fixtures/``. ``wire.ts`` then asserts each one ``satisfies``
its interface, and ``npm run typecheck`` fails if the server stopped sending
something the board promises.

The slide deck and every static export are here too, for the same reason with
the failure delayed rather than softened: those are *files*. A dropped field
renders as a blank slide on a projector, or an empty section in a report someone
opens months later — with no server, no log, and no way to tell it apart from a
report that genuinely had nothing to say.

Two directions, only one of them guarded, and deliberately so:

* A **removed or renamed** field fails the TypeScript build — the fixture no
  longer has what the interface requires.
* An **added** field does not, because TypeScript excess-property-checks only
  fresh object literals and an imported JSON module is not one.

That is the useful direction: adding a field breaks nothing, removing one breaks
a board. The check here (regenerate, compare, fail on difference) is the same
shape as the committed-bundle staleness check in ``make web-check`` — the
fixture is a build artifact under review, not a hand-written expectation that
can invent its own contract.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from yeaboi.agent.state import DeliveredItem, DeliveryReport, SupportingSignal
from yeaboi.poker.board import PokerBoard
from yeaboi.reporting.presentation import deck_payload
from yeaboi.reporting.style import DeckStyle
from yeaboi.retro.board import RetroBoard
from yeaboi.sharing.access import invite_payload

FIXTURES = Path(__file__).resolve().parents[2] / "frontend" / "src" / "test" / "fixtures"

#: An export page's own credit line, which carries the day it was written.
_STAMPED_FOOTER = re.compile(r"Generated by yeaboi\.ai • \d{4}-\d{2}-\d{2}")

#: A bare wall-clock reading, e.g. the plan export's "EXPORTED" fact. A value
#: that is *exactly* this is a clock reading by definition, and pinning it is
#: what stops the fixture rewriting itself every minute.
_STAMP = re.compile(r"\d{4}-\d{2}-\d{2}(?: \d{2}:\d{2}(?::\d{2})?)?")

pytestmark = pytest.mark.skipif(
    not FIXTURES.parent.is_dir(), reason="frontend sources are not part of an installed wheel"
)


def _retro_snapshot() -> dict:
    """A retro mid-ceremony: cards from two people, a reaction, presence, a timer."""
    board = RetroBoard("wire-retro", project_name="yeaboi", sprint_name="Sprint 42")
    board.heartbeat("pid-a", name="Ada", avatar="🦊")
    board.heartbeat("pid-b", name="Grace", avatar="🐙")
    mine = board.add_card(grid="went_well", text="Shipped the tunnel", author="Ada", origin="web", pid="pid-a")
    board.add_card(grid="action_items", text="Alert on staging", author="Grace", origin="web", pid="pid-b")
    # A carried-over item exercises the `status` field, which is `''` on every
    # authoring-grid card and so would otherwise never appear in the fixture.
    board.add_card(grid="action_items", text="From last sprint", author="Ada", origin="carryover", pid="pid-a")
    assert mine is not None
    board.toggle_reaction(mine.id, "👍", "pid-b")
    board.start_timer(300)
    board.set_broadcast_theme("forest")
    # Per-viewer: `mine` must be true for Ada's own card, which is the field the
    # edit and delete controls hang off.
    return board.state_snapshot(viewer_pid="pid-a")


def _poker_snapshots() -> dict[str, dict]:
    """A poker round in each phase, plus the peek projection.

    Three snapshots rather than one, because the poker payload is genuinely
    phase-shaped: vote secrecy means ``votes[].value`` does not exist at all
    while voting, and ``duel`` is null until the floor opens. A single fixture
    would pin whichever phase it happened to capture and leave the others
    unguarded.
    """
    tickets = [
        {
            "key": "YB-1",
            "summary": "Long-poll the board",
            "description_text": "The tunnel buffers SSE.",
            "acceptance_text": "Updates land in under a second.",
            "type": "Story",
            "state": "To Do",
            "assignee": "Ada",
            "url": "https://example.invalid/browse/YB-1",
            "story_points": None,
            "source": "jira",
        },
        {"key": "YB-2", "summary": "Quantise the duck", "story_points": 3},
    ]
    board = PokerBoard("wire-poker", project_name="yeaboi", source="jira", tickets=tickets)
    board.heartbeat("pid-a", name="Ada", avatar="🦊")
    board.heartbeat("pid-b", name="Grace", avatar="🐙")
    board.cast_vote("pid-a", "3")
    board.cast_vote("pid-b", "13")
    board.start_timer(120)

    voting = board.state_snapshot(viewer_pid="pid-a")

    board.reveal()
    board.set_ai_note("Two calls to an unfamiliar API.", suggested=5.0, confidence="medium", evidence=["No SDK yet."])
    revealed = board.state_snapshot(viewer_pid="pid-a")

    opened, error = board.open_duel(90)
    assert opened, error
    # Viewed as the low voter, so `mine_role` is exercised as something other
    # than the empty string a bystander sees.
    duel = board.state_snapshot(viewer_pid="pid-a")

    peek = board.ticket_view(1)
    assert peek is not None

    return {"poker.voting": voting, "poker.revealed": revealed, "poker.duel": duel, "ticket.peek": peek}


def _delivery_report() -> DeliveryReport:
    """One report with every section populated.

    Shared by the deck fixture and the HTML export fixture, which read the same
    artifact through two renderers — so a field that disappears breaks both, and
    the diff says which renderers were relying on it.

    Two delivered items, one of them unassigned, because ``assignee`` is the
    optional field in that row and one item can only pin it present or absent.
    """
    return DeliveryReport(
        period_label="Last month (~2 sprints)",
        period_start="2026-06-15",
        period_end="2026-07-13",
        project_name="Acme Portal",
        sprint_names=("Sprint 11", "Sprint 12"),
        headline="Two sprints of strong delivery.",
        executive_summary="We shipped SSO. Checkout got materially faster for everyone.",
        themes=(("Security", ("SSO", "MFA")), ("Performance", ("Faster checkout",))),
        highlights=("SSO live", "2x faster checkout"),
        metrics=(("Items delivered", "12"), ("Story points", "48")),
        delivered_items=(
            DeliveredItem(key="A-1", title="Ship SSO", status="Done", assignee="Ada"),
            DeliveredItem(key="A-2", title="Cache the ticket peek", status="Done"),
        ),
        supporting_signals=(SupportingSignal(kind="pull_requests", source="github", count=24),),
        emoji_theme=(("headline", "🚀"), ("summary", "📋"), ("metrics", "📊"), ("themes", "🧩")),
        warnings=("Jira was reachable for 12 of 14 days.",),
    )


def _deck_snapshot() -> dict:
    """A slide deck payload with one slide of every kind.

    Not a live board, but the same contract and the same failure mode: an
    exported deck is a file, so a field the renderer reads and the exporter
    stopped sending shows up as a blank slide on someone's projector months
    later, with nothing in any log. The style is deliberately non-default —
    every knob at its default resolves to a value the deck would have anyway,
    which pins nothing.
    """
    style = DeckStyle(heading_color="accent2", font_scale="large", slide_numbers=True, footer_text="ACME Corp")
    return deck_payload(_delivery_report(), theme="aurora", style=style)


def _export_snapshots() -> dict[str, dict]:
    """The boot payload of every migrated static export, straight out of its page.

    Here for the same reason the deck is, and with more surface to lose: these
    are *files*. Nothing else checks that ``ExportReport`` in ``export/boot.ts``
    still describes what Python writes — the exporters' own tests assert against
    hand-written expectations, so a field renamed on both sides at once passes
    every one of them and renders an empty section on a report somebody opens
    six months later, with no server and no log to look at.

    Read out of the rendered page rather than from a payload builder, because
    the page is the artifact. A field lost between the builder and
    ``export_page`` would be invisible to a snapshot of the builder alone.

    Built from frozen artifacts rather than from a live board, unlike the board
    fixtures above — for these exporters the artifact *is* the input contract.
    Every one of them is a persisted, fully-defaulted dataclass, and constructing
    one describes nothing that does not exist.

    Each fixture deliberately carries the *optional* fields too — a skipped
    poker ticket, an AI-authored retro card, an empty retro column, a trend with
    two points. An interface's optionality is only pinned by a fixture that has
    the thing, and by another that does not.

    **Pinned against the environment.** The standup exporter linkifies bare
    ticket keys found in prose against ``get_jira_base_url()``, so a fixture
    naming a key that has no evidence link renders one way on a machine with
    JIRA_BASE_URL set and another way without it — and rewrites itself on every
    run in whichever process saw the other. The snapshot is a committed artifact,
    so it is pinned here rather than left to whatever the suite happens to have
    loaded by this point.
    """
    import os
    from unittest.mock import patch

    from tests._pages import island
    from yeaboi.agent.state import (
        ActivityEvidence,
        AnonymizedOutput,
        MemberUpdate,
        OneOnOnePrep,
        PokerReport,
        PokerTicketResult,
        PokerVote,
        PracticeSignal,
        RetroCard,
        RetroReport,
        RoadmapAnalysis,
        RoadmapProject,
        StandupReport,
    )
    from yeaboi.anonymize.export import build_anonymized_html
    from yeaboi.html_exporter import build_export_html
    from yeaboi.performance.export import build_prep_html
    from yeaboi.poker.export import build_poker_html
    from yeaboi.reporting.export import build_report_html
    from yeaboi.retro.export import build_retro_html
    from yeaboi.roadmap.export import build_roadmap_html
    from yeaboi.standup.export import build_standup_html

    poker = PokerReport(
        date="2026-07-13",
        session_id="wire-poker",
        project_name="yeaboi",
        source="jira",
        scope_label="Sprint 42",
        tickets=(
            PokerTicketResult(
                key="YB-1",
                url="https://example.invalid/browse/YB-1",
                summary="Long-poll the board",
                initial_points=3.0,
                final_points=5.0,
                estimated=True,
                votes=(PokerVote("Ada", "🦊", "3"), PokerVote("Grace", "🐙", "13")),
                ai_note="Two calls to an unfamiliar API.",
                duel_transcript="Ada (voted 3) — turn 1:\nThe endpoint already exists.",
                duel_low="Ada (3)",
                duel_high="Grace (13)",
            ),
            # Skipped, so `final` is null on exactly one ticket. A fixture with
            # only the estimated kind would leave that null unpinned.
            PokerTicketResult(key="YB-2", summary="Quantise the duck", initial_points=3.0),
        ),
        participants=("Ada", "Grace"),
        generated_at="2026-07-13T10:00:00+00:00",
    )

    retro = RetroReport(
        date="2026-07-10",
        session_id="wire-retro",
        sprint_name="Sprint 42",
        cards=(
            RetroCard(grid="went_well", text="Shipped the tunnel", author="Ada", origin="web"),
            RetroCard(grid="action_items", text="Alert on staging", author="AI", origin="ai"),
        ),
        participants=("Ada", "Grace"),
        carried_action_items=(RetroCard(grid="action_items", text="From last sprint", status="done"),),
    )
    # Two runs, so the trend is a populated object rather than the null that
    # would leave `Trend`'s own shape unguarded.
    history = [
        {"retro_date": "2026-07-10", "card_count": 2},
        {"retro_date": "2026-06-26", "card_count": 5},
    ]

    roadmap = RoadmapAnalysis(
        source_type="notion",
        source_label="H2 roadmap",
        summary="Two projects, both security.",
        projects=(
            RoadmapProject(
                name="SSO rollout",
                description="Ship SSO for all tenants.",
                size="large",
                rationale="Blocks three enterprise deals.",
                priority=1,
                themes=("Security",),
                quarter="Q3 2026",
            ),
        ),
        warnings=("Quarter inferred from headings.",),
        generated_at="2026-07-13",
    )

    prep = OneOnOnePrep(
        engineer="Ada",
        date="2026-07-13",
        talking_points=("Sprint 42 scope",),
        feedback=("Clear PR descriptions",),
        goals=("Lead the SSO rollout",),
        gaps=("Little exposure to on-call",),
        improvements=("Pair on the alerting runbook",),
        carried_action_items=("Book the runbook session",),
        activity_summary="Shipped SSO behind a flag.",
        warnings=("Jira was reachable for 12 of 14 days.",),
    )

    # Three members, because standup's payload is where the optional fields
    # cluster: one with everything, one blocked and self-reporting, one with
    # nothing at all.
    #
    # **Every ticket key in the prose also has an evidence link.** That is not
    # decoration: `_ticket_key_map` has a prefix-gated fallback that mints a
    # `<jira base>/browse/<key>` URL for a bare key whose prefix it has seen, and
    # the base comes from the environment. A key mentioned without evidence
    # would therefore gain an `href` on a machine with Jira configured and lose
    # it in CI, and the fixture would rewrite itself depending on whose laptop
    # ran it. That fallback's behaviour is covered in `test_standup_export.py`,
    # where it belongs; this fixture pins a *shape*, so it stays deterministic.
    standup = StandupReport(
        date="2026-07-13",
        session_id="wire-standup",
        sprint_name="Sprint 42",
        sprint_day=7,
        sprint_total_days=10,
        confidence_pct=68,
        confidence_label="At risk",
        confidence_delta=-9,
        confidence_trend="declining",
        confidence_rationale="Two of five stories have not moved.",
        team_summary="Ada shipped the SSO flow. Grace is waiting on a review.",
        member_updates=(
            MemberUpdate(
                name="Ada",
                summary="Shipped YB-1 behind a flag.",
                source="inferred",
                ticketing_summary="YB-1 moved to Done.",
                ticketing_links=(
                    ("YB-1", "https://example.invalid/browse/YB-1"),
                    ("YB-2", "https://example.invalid/browse/YB-2"),
                ),
                ticketing_activity_count=4,
                ticketing_evidence=(
                    ActivityEvidence(
                        kind="issue",
                        key="YB-1",
                        title="SSO login flow",
                        url="https://example.invalid/browse/YB-1",
                        status="Done",
                        timestamp="2026-07-13T09:00:00",
                    ),
                    ActivityEvidence(
                        kind="wip",
                        key="YB-2",
                        title="MFA enrolment",
                        url="https://example.invalid/browse/YB-2",
                        status="In Progress",
                    ),
                ),
                code_summary="Merged three pull requests.",
                code_links=(("Enable SSO", "https://example.invalid/pull/91"),),
                code_activity_count=3,
                code_evidence=(
                    ActivityEvidence(
                        kind="pr",
                        key="#91",
                        title="Enable SSO",
                        url="https://example.invalid/pull/91",
                        repository="acme/web",
                        status="merged",
                        timestamp="2026-07-13T14:32:00",
                        children=(
                            ActivityEvidence(
                                kind="commit",
                                key="0a1b2c3d",
                                title="Wire the SSO callback",
                                url="https://example.invalid/commit/0a1b2c3d",
                                repository="acme/web",
                                timestamp="2026-07-13T13:10:00",
                            ),
                            ActivityEvidence(
                                kind="commit",
                                key="4e5f6071",
                                title="Add the SAML config",
                                url="https://example.invalid/commit/4e5f6071",
                                repository="acme/web",
                                timestamp="2026-07-13T12:40:00",
                            ),
                        ),
                    ),
                    ActivityEvidence(
                        kind="commit",
                        key="78e4201d",
                        title="Fix login redirect",
                        url="https://example.invalid/commit/78e4201d",
                        repository="acme/web",
                        timestamp="2026-07-13T11:05:00",
                    ),
                ),
                documentation_summary="No documentation activity detected.",
                progress_note="Still on YB-2 from the last standup.",
                outlook="Likely to close YB-2 today.",
                # Two members carry practices and one does not, so the payload's
                # optionality is pinned from both sides.
                practices=(
                    PracticeSignal(
                        rule="untracked-work",
                        title="Untracked work",
                        detail=(
                            "#91 'Enable SSO' carries no ticket reference in the branch, title, "
                            "or description. Link a ticket (or raise one) so the work counts "
                            "toward sprint scope."
                        ),
                        evidence=(("#91", "https://example.invalid/pull/91"),),
                    ),
                    PracticeSignal(
                        rule="commit-messages",
                        title="Thin commit messages",
                        detail="3 commits have subjects that name no outcome ('fix', 'wip', 'update').",
                        evidence=(("78e4201d", "https://example.invalid/commit/78e4201d"),),
                        repeat=True,
                    ),
                ),
            ),
            MemberUpdate(
                name="Grace",
                summary="Waiting on review.",
                source="combined",
                blockers="Nobody has picked up the MFA review.",
                self_report="Paired with Ada on auth.",
                practices=(
                    PracticeSignal(
                        rule="wip-sprawl",
                        title="Spread thin",
                        detail="4 tickets in progress at once (YB-2, YB-5, YB-7, YB-9).",
                        evidence=(("YB-2", "https://example.invalid/browse/YB-2"),),
                    ),
                ),
            ),
            MemberUpdate(name="Quiet", summary="No activity detected.", source="inferred"),
        ),
        activity_counts=(("github", 6), ("jira", 5)),
        activity_window="last 24 hours",
        category_coverage=(("ticketing", "covered"), ("documentation", "not_configured")),
        skipped_sources=(("notion", "NOTION_ROOT_PAGE_ID not set"),),
        warnings=("Jira was reachable for 12 of 14 days.",),
        practice_rollup=(("untracked-work", 1), ("wip-sprawl", 1), ("commit-messages", 1)),
    )
    standup_history = [
        {"standup_date": "2026-07-13", "confidence_pct": 68, "status": "success"},
        {"standup_date": "2026-07-12", "confidence_pct": 77, "status": "success"},
    ]

    masked = AnonymizedOutput(
        anonymized_text="# Retro\n\n- **PERSON_1** shipped `TICKET_1`.\n",
        source_mode="retro",
        generated_at="2026-07-13",
        warnings=("2 names could not be matched.",),
    )

    # See the docstring: the standup exporter reads a Jira base URL to linkify
    # bare ticket keys in prose, so every snapshot is taken with it pinned to a
    # fixed value. Patched at the environment rather than at the getter so any
    # other exporter that grows the same dependency is covered too.
    with patch.dict(os.environ, {"JIRA_BASE_URL": "https://example.invalid"}):
        return {
            "export.poker": island(build_poker_html(poker)),
            "export.retro": island(build_retro_html(retro, history=history)),
            "export.reporting": island(build_report_html(_delivery_report())),
            "export.roadmap": island(build_roadmap_html(roadmap)),
            "export.performance": island(build_prep_html(prep)),
            "export.anonymize": island(build_anonymized_html(masked, title="Retro")),
            "export.standup": island(build_standup_html(standup, history=standup_history)),
            "export.plan": island(build_export_html(_plan_state())),
            "export.profile": island(_team_profile_page()),
        }


def _invite_snapshot() -> dict:
    """What ``GET /api/invite`` answers with, on both boards.

    Built by the same :func:`invite_payload` the two handlers call, so this pins
    the endpoint rather than a re-description of it.

    The headers are the host's own — a loopback-bound board is what their browser
    reaches — and the ``public_url`` is the tunnel the TUI handed the server. That
    combination is the case that matters: it is the one where deriving the answer
    from the request would put ``127.0.0.1`` on a clipboard bound for a chat
    window.
    """
    return invite_payload(
        {"Host": "127.0.0.1:5173"},
        "127.0.0.1:5173",
        "K3P9-2QXA",
        "https://abc-def.trycloudflare.com/",
    )


def _boot_snapshots() -> dict[str, dict]:
    """The boot islands: two boards and the share gate.

    A different direction from every other fixture here: the rest are ``/api``
    *responses*, read after the board is running. These are what the document
    is built with, once, at server start — and until now nothing checked their
    shape at all. A dropped field there does not fail a request; it renders a
    board with no masthead, and only for whoever opens the tunnel link.

    The gate is the case that fails most quietly of the three. ``gate/main.tsx``
    spreads every prop conditionally (``boot?.wordmark ? {…} : {}``) so the
    document still renders without an island — which means renaming a field in
    TypeScript typechecks, passes both suites, and ships the *neutral* gate to
    every share. Python pins its key set on its own side; this is what ties the
    two together.
    """
    from yeaboi.poker.page import board_config as poker_config
    from yeaboi.retro.page import board_config as retro_config
    from yeaboi.sharing.gate import gate_boot

    return {
        "retro.boot": retro_config(sprint_name="Sprint 42", project_name="yeaboi"),
        "poker.boot": poker_config(project_name="yeaboi", scope_label="Sprint 42"),
        "gate.boot": gate_boot("standup"),
    }


def _editable_snapshot() -> dict[str, dict]:
    """One editable shared document, after a correction of every shape.

    The response direction for the edit surface. It matters more than most
    fixtures here: a dropped field on this frame does not fail a request, it
    renders a document whose history panel is missing the thing somebody is
    looking for, and only for whoever opened the tunnel link.

    Ids and timestamps are supplied rather than generated so the fixture is
    stable without needing a `_normalise` rule — the same discipline the poker
    snapshots use, and one fewer place for a rule to go stale.
    """
    from yeaboi.agent.state import MemberUpdate, StandupReport
    from yeaboi.artifacts.edits import Edit
    from yeaboi.sharing.documents import editable_share

    report = StandupReport(
        date="2026-01-01",
        team_summary="The team shipped auth.",
        member_updates=(MemberUpdate(name="Ada", summary="Landed login.", blockers="staging db"),),
    )
    share = editable_share(report, kind="standup", ref="standup:1")
    at = "2026-01-01T00:00:00+00:00"
    share.document.apply(
        Edit(
            edit_id="edit0001",
            op="set",
            path="member_updates[name=Ada].blockers",
            value="unblocked",
            author="Grace",
            avatar="🦊",
            pid="pid-1",
            at=at,
        )
    )
    share.document.apply(
        Edit(
            edit_id="edit0002",
            op="note",
            path="member_updates[name=Ada]",
            value="was on call all week",
            author="Grace",
            avatar="🦊",
            pid="pid-1",
            at=at,
        )
    )
    share.document.apply(
        Edit(
            edit_id="edit0003",
            op="field",
            label="Risk owner",
            value="Grace",
            author="Ada",
            avatar="🐙",
            pid="pid-2",
            at=at,
        )
    )
    share.document.heartbeat("pid-2", name="Ada", avatar="🐙", editing="team_summary")
    return {"editable": share.snapshot("pid-1")}


def _fixtures() -> dict[str, dict]:
    return {
        "deck": _deck_snapshot(),
        "retro": _retro_snapshot(),
        "invite": _invite_snapshot(),
        **_boot_snapshots(),
        **_poker_snapshots(),
        **_export_snapshots(),
        **_editable_snapshot(),
    }


def _normalise(payload: dict) -> dict:
    """Pin the values that differ between two identical runs.

    Clocks move, and card ids are random hex. Committing either would make this
    test rewrite its own fixtures every run, and a fixture that always changes
    reports nothing when the thing it watches finally does.

    Pinned to a constant of the same kind rather than deleted: the guard reads
    *types*, so a number has to stay a number and a null has to stay a null. A
    dropped field would read as "the server stopped sending this", which is
    exactly the signal being protected.
    """
    frozen = json.loads(json.dumps(payload))
    counter = 0

    def walk(node: object) -> object:
        nonlocal counter
        if isinstance(node, dict):
            out: dict = {}
            for key, value in node.items():
                if key in ("now_epoch", "end_epoch") and isinstance(value, (int, float)):
                    out[key] = 0
                elif key == "created_at" and isinstance(value, str):
                    out[key] = "2026-01-01T00:00:00+00:00"
                elif key == "generated" and isinstance(value, str):
                    # The deck's export date. Unpinned it would rewrite this
                    # fixture at midnight, which is the one way to teach
                    # everyone to ignore the diff.
                    out[key] = "2026-01-01"
                elif key == "footer" and isinstance(value, str) and _STAMPED_FOOTER.fullmatch(value):
                    # Same, for the exports, whose footer ends in today's date.
                    # Matched rather than keyed on the name: the deck's *style*
                    # also has a `footer`, and that one is text the host typed.
                    out[key] = "Generated by yeaboi.ai • 2026-01-01"
                elif key == "id" and isinstance(value, str):
                    # Card ids only — `reaction_events[].id` is an int and is a
                    # monotonic counter, so it is already stable.
                    counter += 1
                    out[key] = f"card{counter:04d}"
                else:
                    out[key] = walk(value)
            return out
        if isinstance(node, list):
            return [walk(item) for item in node]
        if isinstance(node, str) and _STAMP.fullmatch(node):
            # Anywhere, not under a known key: the plan export's clock reading
            # rides inside a `["EXPORTED", "2026-07-30 20:34"]` *fact pair*, so
            # there is no key to match on — and unpinned it rewrote the fixture
            # every minute, which is the one way to teach everyone to ignore
            # the diff. Values that are exactly a stamp are stamps.
            return "2026-01-01"
        return node

    return walk(frozen)  # type: ignore[return-value]


def _write(name: str, payload: dict) -> str:
    text = json.dumps(_normalise(payload), indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    (FIXTURES / f"{name}.json").write_text(text, encoding="utf-8")
    return text


class TestWireFixtures:
    def test_committed_fixtures_match_the_live_snapshots(self):
        """Regenerate and compare. A difference means the wire shape moved.

        The fix is never to edit the JSON: run this test, commit what it wrote,
        and then make ``types/board.ts`` agree with it — in that order, so the
        TypeScript follows the server rather than the other way round.
        """
        FIXTURES.mkdir(parents=True, exist_ok=True)
        stale: list[str] = []
        for name, payload in _fixtures().items():
            path = FIXTURES / f"{name}.json"
            before = path.read_text(encoding="utf-8") if path.exists() else ""
            after = _write(name, payload)
            if before != after:
                stale.append(name)
        assert not stale, (
            f"wire fixtures regenerated: {', '.join(stale)}. The snapshot shape changed — "
            "commit frontend/src/test/fixtures/ and check types/board.ts still describes it."
        )

    def test_voting_snapshot_carries_no_vote_values(self):
        """The property the fixture exists to make legible, asserted directly.

        A `satisfies` check would happily accept a `value` on every seat; only
        this says the field must be *absent* while the round is open. Vote
        secrecy is the one poker invariant a rendering bug cannot recover from.
        """
        voting = _poker_snapshots()["poker.voting"]
        assert voting["phase"] == "voting"
        assert voting["votes"], "fixture must have seats, or this asserts nothing"
        for seat in voting["votes"]:
            assert "value" not in seat
            assert set(seat) == {"name", "avatar", "voted"}
        assert voting["distribution"] == {}
        assert voting["median"] is None and voting["suggestion"] is None
        # …and the viewer still sees their own, which is what makes the deck
        # able to show a selected card without leaking anyone else's.
        assert voting["mine_value"] == "3"

    def test_peek_projection_omits_round_internals(self):
        peek = _poker_snapshots()["ticket.peek"]
        for internal in ("accepted_votes", "ai_note", "duel_transcript", "initial_points", "source"):
            assert internal not in peek


def _plan_state() -> dict:
    """A complete plan: every checkpoint's artifact, and every optional field.

    Deliberately end-to-end rather than partial. The partial shapes are what
    `Plan.test.tsx` covers; what this pins is that no field the renderer reads
    stopped being written — and a field can only be pinned by a fixture that
    has it.
    """
    from yeaboi.agent.state import (
        AcceptanceCriterion,
        Discipline,
        Feature,
        Priority,
        ProjectAnalysis,
        Sprint,
        StoryPointValue,
        Task,
        TaskLabel,
        UserStory,
    )

    return {
        "project_analysis": ProjectAnalysis(
            project_name="Acme Portal",
            project_description="A self-service portal.",
            project_type="greenfield",
            goals=("Cut support tickets",),
            end_users=("Tenant administrators",),
            target_state="Every tenant self-serves.",
            tech_stack=("TypeScript",),
            integrations=("Okta",),
            constraints=("No downtime",),
            sprint_length_weeks=2,
            risks=("SAML is unfamiliar",),
            out_of_scope=("Mobile app",),
            assumptions=("Okta stays",),
            target_sprints=3,
        ),
        "team_size": 4,
        "velocity_per_sprint": 40,
        "net_velocity_per_sprint": 30,
        "sprint_length_weeks": 2,
        "capacity_bank_holiday_days": 2,
        "jira_epic_key": "ACME-100",
        "analysis_profile_id": "jira-acme-web",
        "features": (
            Feature(id="F-1", title="Single sign-on", description="Bring your own IdP.", priority=Priority.CRITICAL),
        ),
        "stories": (
            UserStory(
                id="S-1",
                feature_id="F-1",
                persona="tenant admin",
                goal="sign in with Okta",
                benefit="I manage one password",
                acceptance_criteria=(
                    AcceptanceCriterion(given="a configured tenant", when="they log in", then="they reach Okta"),
                ),
                story_points=StoryPointValue(8),
                priority=Priority.CRITICAL,
                title="Okta sign-in",
                discipline=Discipline.BACKEND,
                points_rationale="Unfamiliar identity provider.",
                points_confidence="low",
            ),
        ),
        "tasks": (
            Task(
                id="T-1",
                story_id="S-1",
                title="Wire the handshake",
                description="Add the ACS endpoint.",
                label=TaskLabel.CODE,
                test_plan="Round-trip against the dev tenant.",
                ai_prompt="Write the assertion validator.",
            ),
        ),
        "sprints": (Sprint(id="SP-1", name="Sprint 1", goal="SSO end to end", capacity_points=30, story_ids=("S-1",)),),
    }


def _team_profile_page() -> str:
    """A team profile exercising every block kind the exporter can emit.

    The other exports pin one shape each; this one pins a *vocabulary*. Its
    sections are generated, so what has to stay true is that every `Block`
    member `boot.ts` declares still has a producer and still looks the way the
    renderer's switch expects — a block kind that quietly stops being emitted
    is a section that renders as nothing.

    Nine of the ten kinds are here. `image` is the exception: it is a rendered
    velocity chart, so its bytes depend on whether the optional charts extra is
    installed and on the matplotlib version — a fixture of it would either skip
    or churn. Its two fields are pinned by `Profile.test.tsx` instead.
    """
    from yeaboi.team_profile import (
        AiAdoptionSignal,
        DailyScopeSnapshot,
        DoDSignal,
        ScopeChangeEvent,
        SprintScopeTimeline,
        StoryPointCalibration,
        TeamProfile,
    )
    from yeaboi.team_profile_exporter import build_team_profile_html

    profile = TeamProfile(
        team_id="jira-ACME",
        source="jira",
        project_key="ACME",
        sample_sprints=4,
        sample_stories=37,
        velocity_avg=28.0,
        velocity_stddev=6.0,
        sprint_completion_rate=76.0,
        ai_adoption=AiAdoptionSignal(
            scanned_commits=120,
            ai_commits=31,
            scanned_prs=40,
            ai_prs=12,
            footprint_pct=26.9,
            per_tool=(("claude-code", 18), ("copilot", 13)),
            per_activity=(("commit", 31), ("pull request", 12)),
            per_author=(("Ada Okonjo", 19), ("Bo Chen", 12)),
            sources_scanned=("github",),
            repos_scanned=("acme/api", "acme/web"),
        ),
        dod_signal=DoDSignal(
            stories_with_testing_mention_pct=64.0,
            stories_with_pr_link_pct=88.0,
            common_checklist_items=("tests pass", "reviewed"),
        ),
        point_calibrations=(
            StoryPointCalibration(
                point_value=5,
                avg_cycle_time_days=4.0,
                sample_count=12,
                common_patterns=("one endpoint, one screen",),
                typical_task_count=3.0,
                overshoot_pct=18.0,
            ),
        ),
    )

    timeline = SprintScopeTimeline(
        sprint_name="Sprint 4",
        committed_pts=30.0,
        final_pts=36.0,
        delivered_pts=27.0,
        scope_change_total=6.0,
        daily_snapshots=(
            DailyScopeSnapshot(date="2026-07-06", total_scope_pts=30.0, stories_in_sprint=(("ACME-1", 30.0),)),
            DailyScopeSnapshot(date="2026-07-09", total_scope_pts=36.0, stories_in_sprint=(("ACME-1", 36.0),)),
        ),
        change_events=(
            ScopeChangeEvent(
                issue_key="ACME-9",
                change_type="added",
                delta_pts=6.0,
                summary="Audit log export",
            ),
        ),
    )

    examples = {
        "analysis_depth": "deep",
        # prose + bullets
        "narrative": {
            "executive_summary": "Delivery is steady; scope discipline is the gap.",
            "sections": {"velocity": "Holding at 28 points.", "workflow": "DoD is emerging."},
        },
        # cards
        "insights": {
            "start": [
                {
                    "title": "Lock scope after planning",
                    "detail": "Six points arrived mid-sprint.",
                    "evidence": "Sprint 4",
                    "link": "https://jira.example.com/browse/ACME-9",
                }
            ]
        },
        "ai_adoption": {
            "activity_coverage": {"status": "partial", "completed": 118, "eligible": 120},
            "selected_users": ["Ada Okonjo", "Bo Chen"],
            "matched_identities": {"Ada Okonjo": "ada"},
            "coverage": ["Two archived repositories were not scanned."],
            "samples": [
                {
                    "tool": "claude-code",
                    "title": "Add audit log export",
                    "url": "https://github.com/acme/api/commit/abc123",
                    "source": "github",
                },
                {"tool": "other_ai", "title": "Refactor the seat store", "key": "def456"},
            ],
            "member_practices": {
                "min_sample": 5,
                "file_data": {"with_file_data": 96, "total": 120},
                "members": [
                    {
                        "member": "Ada Okonjo",
                        "commits": 71,
                        "prs": 24,
                        "tests_num": 40,
                        "tests_den": 60,
                        "tests_rate": 66.7,
                        "docs_num": 9,
                        "docs_den": 60,
                        "docs_rate": 15.0,
                        "ticket_num": 20,
                        "ticket_den": 24,
                        "ticket_rate": 83.3,
                        "desc_num": 2,
                        "desc_den": 3,
                    }
                ],
                "team": {"member": "Team", "commits": 120, "prs": 40},
            },
        },
        # bar + kv + callout (the bottleneck)
        "task_decomposition": {
            "stories_with_tasks": 22,
            "total_stories": 37,
            "total_tasks": 88,
            "avg_tasks_per_story": 4.0,
            "task_completion_rate": 71.0,
            "type_distribution": {"backend": 55.0, "frontend": 30.0, "qa": 15.0},
            "bottlenecks": [("qa", 42, 12)],
            "common_tasks": [("Add integration test", 9)],
            "task_assignees": {"Ada Okonjo": 40},
        },
        # table with person cells and toned readings
        "contributor_stats": [
            {
                "name": "Ada Okonjo",
                "delivery_pts": 62,
                "stories_completed": 18,
                "spill_rate": 6,
                "avg_cycle_time": 3.5,
                "sprints_active": 4,
                "top_discipline": "backend",
                "top_work_type": "feature/api",
                "per_sprint": 15.5,
            },
            {
                "name": "Bo Chen",
                "delivery_pts": 30,
                "stories_completed": 11,
                "spill_rate": 28,
                "avg_cycle_time": 9.0,
                "sprints_active": 4,
                "top_discipline": "frontend",
                "per_sprint": 7.5,
            },
            {"name": "Kit Ferrer", "delivery_pts": 20, "stories_completed": 8, "per_sprint": 5.0},
        ],
        # table + cards (incomplete) + trend (the scope timeline)
        "sprint_details": [
            {"name": "Sprint 3", "points": 26, "planned": 12, "completed": 11, "rate": 92, "done": True},
            {
                "name": "Sprint 4",
                "points": 30,
                "planned": 14,
                "completed": 9,
                "rate": 64,
                "done": False,
                "has_shadow": True,
                "incomplete": [
                    {"issue_key": "ACME-12", "summary": "Tenant switcher", "points": 5},
                    {"issue_key": "ACME-13", "summary": "Audit filters", "shadow": True},
                ],
            },
        ],
        "scope_changes": {
            "totals": {
                "added_mid_sprint": 6,
                "re_estimated": 3,
                "total_stories": 37,
                "avg_committed_velocity": 30.0,
                "avg_delivered_velocity": 27.0,
            },
            "timelines": [timeline],
            "carry_over_chains": [{"issue_key": "ACME-2", "sprints": ["Sprint 1", "Sprint 2", "Sprint 3"]}],
            "per_sprint": [{"name": "Sprint 4", "scope_churn": 0.4}, {"name": "Sprint 3", "scope_churn": 0.35}],
        },
        # callout list (shadow) with linked runs
        "shadow_spillover": [
            {
                "issue_key": "ACME-13",
                "issue_url": "https://jira.example.com/browse/ACME-13",
                "title": "Audit filters",
                "from_sprint": "Sprint 3",
                "to_sprint": "Sprint 4",
            },
            {"issue_key": "ACME-14", "title": "Rate limiter", "from_sprint": "Sprint 3", "to_sprint": "Sprint 4"},
        ],
        # bullets under the calibration table, with a linked example
        "confidence_levels": {5: "high"},
        "calibration_5pt": [
            {
                "issue_key": "ACME-7",
                "issue_url": "https://jira.example.com/browse/ACME-7",
                "summary": "Add the ACS endpoint",
                "detail": "four days, three tasks",
            }
        ],
        # table with a linked, annotated example cell
        "dod_testing": [
            {
                "issue_key": "ACME-5",
                "issue_url": "https://jira.example.com/browse/ACME-5",
                "summary": "Session expiry",
            }
        ],
        # table with toned status cells, plus its notes
        "proposed_dod": {
            "summary": "A definition of done is emerging, not established.",
            "health": "moderate",
            "items": [
                {
                    "practice": "Tests",
                    "status": "established",
                    "signals": "64% of stories",
                    "recommendation": "Keep it.",
                },
                {
                    "practice": "Deploy note",
                    "status": "missing",
                    "signals": "no evidence",
                    "recommendation": "Add a deploy step.",
                },
            ],
            "ordering": ["review", "test", "deploy"],
            "custom_steps": [{"title": "Demo to support", "pct": 40}],
        },
        # bar + table + bullets
        "repositories": {
            "top_repos": [
                {"repo": "acme/api", "stories": 21, "pct": 57.0},
                {"repo": "acme/web", "stories": 16, "pct": 43.0},
            ],
            "repo_avg_cycle_time": {"acme/api": 4.0, "acme/web": 18.0},
            "spillover_repos": [{"repo": "acme/web", "spill_rate": 44, "spills": 7}],
            "by_pts": {"5": ["acme/api"], "8": ["acme/web"]},
        },
        # kv rows carrying a toned trend cell
        "velocity_trend": {"trend": "improving", "slope": 1.8, "first_velocity": 24, "last_velocity": 30},
        "recurring_count": 9,
        "delivery_count": 28,
        "recurring": [{"issue_key": "ACME-99", "summary": "Weekly data refresh"}],
        "team_size": 3,
        "team_members": ["Ada Okonjo", "Bo Chen", "Kit Ferrer"],
        "spillover_correlation": {"by_size": {"5": 12.0, "8": 34.0}, "by_discipline": {"frontend": 28.0}},
        # bullets under a kv, with a linked topic example
        "ac_patterns": {
            "stories_with_ac_pct": 72,
            "median_ac": 3,
            "specificity": {"label": "mixed", "precise_pct": 55},
            "themes": {"permissions": 40},
            "theme_examples": {
                "permissions": {
                    "issue_key": "ACME-3",
                    "issue_url": "https://jira.example.com/browse/ACME-3",
                    "summary": "Role gates on the audit view",
                }
            },
            "by_discipline": {"backend": {"avg_ac": 3.0}, "frontend": {"avg_ac": 2.0}},
        },
        "seasonal": {},
        "additional_patterns": {
            "estimation_bias": {
                "sample_size": 20,
                "accurate_pct": 55.0,
                "underestimated_pct": 30.0,
                "overestimated_pct": 15.0,
                "worst_overestimate_sizes": [8],
            },
            "seasonal": {"monthly_avg": {"June": 30.0}, "low_months": {"August": 18.0}, "high_months": {}},
        },
        "workflow_style": {"workflow": ["To Do", "In Progress", "Done"], "style": "minimal", "dod_columns": {}},
        "naming_conventions": {
            "title_prefixes": [("feat", 40)],
            "label_distribution": [("api", 30)],
            "stories_with_labels_pct": 62,
            "epic_naming_style": "noun phrase",
            "epic_examples": ["Tenant self-service"],
            "template_sections": [("Context", 1), ("Acceptance", 1)],
        },
        "story_structure": {
            "subtask_ordering": ["design", "build", "test"],
            "skipped_types": [{"type": "spike", "present_pct": 4}],
            "avg_epic_completion": 68,
            "lingering_epics": [{"epic_title": "Reporting", "completed": 3, "total": 9, "rate": 33}],
            "epic_sprint_spread": [{"epic": "Reporting", "stories": 9, "sprints": 4}],
        },
        "point_descriptions": {"5": "One endpoint and the screen that calls it."},
        "discipline_calibration": {
            "backend": [{"points": 5, "avg_cycle_days": 4.0, "variance": 1.0, "samples": 9, "spill_pct": 8.0}],
            "frontend": [{"points": 5, "avg_cycle_days": 7.0, "variance": 3.0, "samples": 6, "spill_pct": 30.0}],
        },
    }

    return build_team_profile_html(
        profile,
        examples=examples,
        sprint_names=["Sprint 3", "Sprint 4"],
        markdown_name="team-profile-20260731-090000.md",
    )
