"""Unit tests for the Retro Markdown + HTML exporters (incl. escaping)."""

from yeaboi.agent.state import RetroCard, RetroReport
from yeaboi.retro.export import build_retro_html, build_retro_markdown, export_retro


def _report():
    return RetroReport(
        date="2026-07-10",
        session_id="sess-1",
        project_name="Demo",
        sprint_name="Sprint 5",
        cards=(
            RetroCard(grid="went_well", text="fast deploys", author="Sam", origin="web"),
            RetroCard(
                grid="didnt_go_well",
                text="flaky tests",
                author="Rae",
                origin="web",
                reactions=(("👍", 3), ("🔥", 1)),
            ),
            RetroCard(grid="action_items", text="add retry guard", author="AI", origin="ai"),
        ),
        participants=("Sam", "Rae"),
    )


class TestMarkdown:
    def test_contains_headings_and_cards(self):
        md = build_retro_markdown(_report())
        assert "# Sprint Retro — Sprint 5" in md
        assert "## What went well" in md
        assert "fast deploys" in md
        assert "add retry guard" in md and "_(AI)_" in md

    def test_empty_grid_shows_placeholder(self):
        md = build_retro_markdown(RetroReport(date="2026-07-10"))
        assert "_No cards._" in md

    def test_reaction_counts_shown(self):
        md = build_retro_markdown(_report())
        assert "👍 3" in md and "🔥 1" in md

    def test_card_grids_are_tables(self):
        md = build_retro_markdown(_report())
        # Went well / didn't go well render as native tables with author + reactions.
        assert "| Card | By | Reactions |" in md
        assert "| fast deploys | Sam | — |" in md
        assert "| flaky tests | Rae | 👍 3  🔥 1 |" in md

    def test_action_items_are_checkboxes(self):
        md = build_retro_markdown(_report())
        assert "- [ ] add retry guard _(AI)_" in md

    def test_branded_footer(self):
        md = build_retro_markdown(_report())
        assert "🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)" in md


class TestHtml:
    def test_self_contained_and_has_cards(self):
        html = build_retro_html(_report())
        assert "<!DOCTYPE html>" in html and "<style>" in html
        assert "fast deploys" in html
        assert "Sam" in html
        assert "👍 3" in html  # reaction counts rendered

    def test_escapes_card_text(self):
        rep = RetroReport(
            date="2026-07-10",
            cards=(RetroCard(grid="demos", text="<script>alert(1)</script>", author="<b>x</b>"),),
        )
        html = build_retro_html(rep)
        assert "<script>alert(1)</script>" not in html
        assert "&lt;script&gt;" in html
        assert "<b>x</b>" not in html


def _report_with_carried():
    return RetroReport(
        date="2026-07-10",
        carried_action_items=(
            RetroCard(grid="action_items", text="ship the docs", status="done"),
            RetroCard(grid="action_items", text="keep <b>going</b>", status="carried_over"),
        ),
    )


class TestCarriedSection:
    def test_markdown_lists_carried_with_status_labels(self):
        md = build_retro_markdown(_report_with_carried())
        assert "Last sprint's action items — progress" in md
        assert "**[Done]** ship the docs" in md
        assert "**[Carried Over]** keep" in md

    def test_html_lists_carried_and_escapes(self):
        html = build_retro_html(_report_with_carried())
        assert "Last sprint" in html and "progress" in html
        assert "[Done]" in html and "[Carried Over]" in html
        # Untrusted carried text is escaped.
        assert "keep <b>going</b>" not in html
        assert "&lt;b&gt;going&lt;/b&gt;" in html

    def test_no_carried_section_when_empty(self):
        md = build_retro_markdown(RetroReport(date="2026-07-10"))
        assert "Last sprint's action items — progress" not in md


class TestExportWrites:
    def test_writes_md_and_html(self, tmp_path, monkeypatch):
        # Redirect the export dir into tmp_path.
        target = tmp_path / "demo"

        def _fake_dir(key):
            target.mkdir(parents=True, exist_ok=True)
            return target

        monkeypatch.setattr("yeaboi.paths.get_retro_export_dir", _fake_dir)
        paths = export_retro(_report(), project_name="Demo")
        assert paths["markdown"].exists() and paths["html"].exists()
        assert paths["markdown"].read_text().startswith("# Sprint Retro")


class TestSharedDesignSystem:
    def test_retro_html_uses_shared_theme(self):
        html = build_retro_html(_report())
        assert 'data-theme="midnight"' in html
        assert "yeaboi-export-theme" in html  # theme switcher present
        assert 'src="http' not in html and "<link" not in html  # self-contained


def _history(*rows):
    """Newest-first rows mirroring RetroStore.get_history output."""
    return [
        {"id": i, "run_at": f"{d}T18:00:00", "retro_date": d, "project_name": "Demo", "card_count": n}
        for i, (d, n) in enumerate(rows)
    ]


class TestVisuals:
    def test_participant_and_card_avatars(self):
        html = build_retro_html(_report())
        # class attribute, not the bare token — ".avatar" also lives in the stylesheet.
        assert html.count('class="avatar"') >= 3  # Sam + Rae participants, plus card authors
        assert ">S</span>" in html and ">R</span>" in html

    def test_avatar_name_escaped(self):
        rep = RetroReport(date="2026-07-10", cards=(RetroCard(grid="demos", text="x", author="<b>Eve</b>"),))
        html = build_retro_html(rep)
        assert "<b>Eve</b>" not in html

    def test_column_bar_counts_in_board_order(self):
        html = build_retro_html(_report())
        assert 'class="seg-track"' in html
        assert "What went well 1" in html
        assert "Action items 1" in html
        # Empty column never appears in the legend.
        assert "Demos 0" not in html and "Demos 1" not in html

    def test_no_cards_no_column_bar(self):
        html = build_retro_html(RetroReport(date="2026-07-10"))
        assert 'class="seg-track"' not in html

    def test_empty_columns_become_footnotes(self):
        html = build_retro_html(_report())  # demos has no cards
        assert "class='card-footnote'>Demos — no cards.</p>" in html
        assert "<h3>Demos</h3>" not in html
        assert "<h3>What went well</h3>" in html

    def test_all_empty_board_all_footnotes_no_grid(self):
        html = build_retro_html(RetroReport(date="2026-07-10"))
        assert "member-grid" not in html.split("</style>")[1]
        assert html.count("card-footnote") >= 4

    def test_sparkline_from_history(self):
        history = _history(("2026-07-10", 3), ("2026-06-26", 8), ("2026-06-12", 6))
        html = build_retro_html(_report(), history=history)
        assert 'class="spark-wrap"' in html
        assert "Card volume trend" in html
        assert "2026-06-12" in html  # oldest label rendered

    def test_no_history_no_sparkline(self):
        html = build_retro_html(_report())
        assert 'class="spark-wrap"' not in html

    def test_future_history_rows_excluded(self):
        # Re-exporting an old retro must not show retros held after it.
        history = _history(("2026-08-01", 9), ("2026-06-26", 8))
        html = build_retro_html(_report(), history=history)
        # Only 2026-06-26 + the report's own date remain → 2 points → chart renders,
        # but the future date never appears.
        assert "2026-08-01" not in html

    def test_export_writes_forward_history(self, tmp_path, monkeypatch):
        target = tmp_path / "demo"

        def _fake_dir(key):
            target.mkdir(parents=True, exist_ok=True)
            return target

        monkeypatch.setattr("yeaboi.paths.get_retro_export_dir", _fake_dir)
        history = _history(("2026-07-10", 3), ("2026-06-26", 8))
        paths = export_retro(_report(), project_name="Demo", history=history)
        assert 'class="spark-wrap"' in paths["html"].read_text()

    def test_self_contained_with_history(self):
        html = build_retro_html(_report(), history=_history(("2026-07-10", 3), ("2026-06-26", 8)))
        assert 'src="http' not in html and "<link" not in html
