"""Unit tests for reporting/export — Markdown, HTML, and file writing."""

from yeaboi.agent.state import DeliveredItem, DeliveryReport
from yeaboi.reporting import export


def _report():
    return DeliveryReport(
        period_label="Last sprint",
        period_start="2026-06-29",
        period_end="2026-07-13",
        project_name="Acme Portal",
        sprint_names=("Sprint 12",),
        headline="Shipped SSO.",
        executive_summary="We delivered single sign-on.",
        themes=(("Security", ("SSO login", "MFA rollout")),),
        highlights=("SSO live for all users",),
        metrics=(("Items delivered", "7"), ("Contributors", "3")),
        delivered_items=(
            DeliveredItem(
                key="ACME-1", title="SSO <script>alert(1)</script>", status="Done", source="jira", assignee="Ada"
            ),
        ),
        emoji_theme=(("headline", "🚀"), ("metrics", "📊")),
        warnings=("test warning",),
        generated_at="2026-07-13",
    )


class TestMarkdown:
    def test_contains_sections(self):
        md = export.build_report_markdown(_report())
        assert "# 🚀 Delivery Report — Acme Portal" in md
        assert "Last sprint" in md
        assert "By the numbers" in md
        assert "Security" in md
        assert "ACME-1" in md
        assert "test warning" in md

    def test_empty_report_renders(self):
        md = export.build_report_markdown(DeliveryReport(period_label="Last month (~2 sprints)"))
        assert "Delivery Report" in md

    def test_chart_embedded_with_charts_dir(self, tmp_path):
        import pytest

        pytest.importorskip("matplotlib")
        md = export.build_report_markdown(_report(), charts_dir=tmp_path)
        assert f"![Delivered items]({tmp_path / 'delivered.png'})" in md
        assert (tmp_path / "delivered.png").exists()

    def test_no_charts_dir_no_image(self):
        md = export.build_report_markdown(_report())
        assert "![Delivered items]" not in md

    def test_metrics_and_items_are_tables(self):
        md = export.build_report_markdown(_report())
        assert "| Metric | Value |" in md
        assert "| Items delivered | **7** |" in md
        assert "| Key | Title | Status | By |" in md
        assert "| `ACME-1` |" in md and "| Ada |" in md

    def test_branded_footer(self):
        md = export.build_report_markdown(_report())
        assert "🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)" in md

    def test_delivered_counts_by_person_then_status(self):
        by_person = export._delivered_counts(_report())
        assert by_person == [("Ada", 1)]
        unassigned = DeliveryReport(
            delivered_items=(
                DeliveredItem(key="A-1", title="x", status="Done", source="jira"),
                DeliveredItem(key="A-2", title="y", status="Closed", source="jira"),
            )
        )
        assert sorted(export._delivered_counts(unassigned)) == [("Closed", 1), ("Done", 1)]


class TestHtml:
    def test_self_contained_and_escaped(self):
        html = export.build_report_html(_report())
        assert html.lstrip().startswith("<!DOCTYPE html>")
        assert "<style>" in html  # inline CSS, no external stylesheet
        # Untrusted ticket title must be escaped, never live markup.
        assert "<script>alert(1)</script>" not in html
        assert "&lt;script&gt;" in html
        assert "ACME-1" in html

    def test_metrics_cards_present(self):
        html = export.build_report_html(_report())
        assert "By the numbers" in html
        assert "Items delivered" in html


class TestExportReport:
    def test_writes_three_files(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.get_reporting_export_dir", lambda key: tmp_path)
        paths = export.export_report(_report(), theme="aurora")
        assert set(paths) == {"markdown", "html", "slides"}
        for p in paths.values():
            assert p.exists() and p.read_text(encoding="utf-8")
        assert paths["slides"].name.endswith("-slides.html")

    def test_chart_written_for_markdown_html_uses_inline_bar(self, tmp_path, monkeypatch):
        import pytest

        pytest.importorskip("matplotlib")
        monkeypatch.setattr("yeaboi.paths.get_reporting_export_dir", lambda key: tmp_path)
        paths = export.export_report(_report(), theme="aurora")
        # Markdown links the chart relatively (it lives beside the .md, and
        # flows to Notion/Confluence via export_targets)…
        assert "![Delivered items](delivered.png)" in paths["markdown"].read_text(encoding="utf-8")
        assert (tmp_path / "delivered.png").exists()
        # …while the HTML draws a theme-aware inline segment bar instead of the
        # theme-blind PNG (recolors with the page's theme switcher).
        html = paths["html"].read_text(encoding="utf-8")
        assert "data:image/png;base64," not in html
        assert 'class="seg-track"' in html


class TestSharedDesignSystem:
    def test_report_html_uses_shared_theme(self):
        html = export.build_report_html(_report())
        assert 'data-theme="midnight"' in html
        assert "yeaboi-export-theme" in html  # theme switcher present
        assert 'src="http' not in html and "<link" not in html  # self-contained


def _history(*rows):
    """Newest-first rows mirroring ReportingStore.get_history output."""
    return [
        {
            "id": i,
            "run_at": f"{d}T17:00:00",
            "period": "sprint",
            "period_end": d,
            "project_name": "Acme Portal",
            "item_count": n,
        }
        for i, (d, n) in enumerate(rows)
    ]


class TestVisuals:
    def test_delivered_breakdown_segment_bar(self):
        html = export.build_report_html(_report())
        # class attribute, not the bare token — ".seg-track" also lives in the stylesheet.
        assert 'class="seg-track"' in html
        assert "Ada 1" in html  # counted legend (by-person counts here)

    def test_assignee_avatar_in_table(self):
        html = export.build_report_html(_report())
        assert 'class="avatar"' in html
        assert ">A</span>" in html

    def test_avatar_name_escaped(self):
        rep = _report()
        hostile = DeliveryReport(
            period_label="p",
            period_end="2026-07-13",
            delivered_items=(DeliveredItem(key="X-1", title="t", status="Done", assignee="<b>Eve</b>"),),
        )
        html = export.build_report_html(hostile)
        assert "<b>Eve</b>" not in html
        assert rep is not None  # keep the fixture exercised

    def test_theme_and_highlight_bullets_split(self):
        rep = DeliveryReport(
            period_label="p",
            period_end="2026-07-13",
            highlights=("Shipped SSO. Landed MFA; docs refreshed.",),
        )
        html = export.build_report_html(rep)
        assert "<li>Shipped SSO.</li>" in html
        assert "<li>Landed MFA</li>" in html
        assert "<li>docs refreshed.</li>" in html
        assert "class='analysis-section'" in html

    def test_sparkline_from_history(self):
        history = _history(("2026-07-13", 7), ("2026-06-29", 5), ("2026-06-15", 9))
        html = export.build_report_html(_report(), history=history)
        assert 'class="spark-wrap"' in html
        assert "Delivery volume trend" in html
        assert "2026-06-15" in html

    def test_other_project_history_excluded(self):
        history = _history(("2026-06-29", 5))
        history.append(
            {
                "id": 9,
                "run_at": "2026-06-01T17:00:00",
                "period": "sprint",
                "period_end": "2026-06-01",
                "project_name": "Other Project",
                "item_count": 40,
            }
        )
        html = export.build_report_html(_report(), history=history)
        assert "2026-06-01" not in html

    def test_no_history_no_sparkline(self):
        assert 'class="spark-wrap"' not in export.build_report_html(_report())

    def test_self_contained_with_history(self):
        html = export.build_report_html(_report(), history=_history(("2026-07-13", 7), ("2026-06-29", 5)))
        assert 'src="http' not in html and "<link" not in html
