"""Unit tests for Performance rendering, export, and delivery."""

import pytest

from tests._pages import assert_self_contained, island
from yeaboi.agent.state import (
    ActivityEvidence,
    EvidenceGroup,
    OneOnOnePrep,
    OneOnOneRecord,
    SixMonthReview,
)
from yeaboi.performance import delivery, export, render


class TestRender:
    """The plaintext surface. The styled one lives in ui/shared/_performance_rows.py."""

    def test_prep_lines(self):
        prep = OneOnOnePrep(
            engineer="Ada",
            date="2026-07-12",
            talking_points=("tp",),
            feedback=("fb",),
            carried_action_items=("carry",),
            warnings=("w",),
        )
        lines = render.format_prep_lines(prep)
        text = "\n".join(lines)
        assert "Ada" in text and "tp" in text and "carry" in text and "w" in text

    def test_completion_lines(self):
        rec = OneOnOneRecord(engineer="Ada", date="2026-07-12", email_summary="Hi Ada", action_items=("do x",))
        text = "\n".join(render.format_completion_lines(rec))
        assert "Hi Ada" in text and "do x" in text

    def test_review_lines(self):
        rev = SixMonthReview(engineer="Ada", strengths=("s",), overall="great", period_start="a", period_end="b")
        text = "\n".join(render.format_review_lines(rev))
        assert "great" in text and "s" in text


class TestMarkdownLayout:
    def test_prep_uses_tasks_numbers_and_quote(self):
        prep = OneOnOnePrep(
            engineer="Ada",
            date="2026-07-12",
            activity_summary="shipped auth\nfixed CI",
            talking_points=("first", "second"),
            carried_action_items=("carry over",),
        )
        md = export.build_prep_markdown(prep)
        # Carried actions are checkable tasks; talking points numbered;
        # activity is a single multi-line blockquote; branded footer present.
        assert "- [ ] carry over" in md
        assert "1. first" in md and "2. second" in md
        assert "> shipped auth\n> fixed CI" in md
        assert "🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)" in md

    def test_completion_action_items_are_tasks(self):
        rec = OneOnOneRecord(engineer="Ada", date="2026-07-12", action_items=("do x",))
        md = export.build_completion_markdown(rec)
        assert "- [ ] do x" in md

    def test_review_goals_numbered(self):
        rev = SixMonthReview(engineer="Ada", overall="great work", goals=("grow", "lead"))
        md = export.build_review_markdown(rev)
        assert "> great work" in md
        assert "1. grow" in md and "2. lead" in md


class TestExport:
    @pytest.fixture(autouse=True)
    def _tmp_export(self, monkeypatch, tmp_path):
        def _dir(engineer_key):
            d = tmp_path / engineer_key
            d.mkdir(parents=True, exist_ok=True)
            return d

        monkeypatch.setattr("yeaboi.paths.get_performance_export_dir", _dir)

    def test_export_prep_writes_md_and_html(self, tmp_path):
        prep = OneOnOnePrep(engineer="Ada", date="2026-07-12", talking_points=("point",))
        paths = export.export_artifact(prep, engineer="Ada", kind="prep")
        assert paths["markdown"].exists() and paths["html"].exists()
        assert "point" in paths["markdown"].read_text()
        assert "<html" in paths["html"].read_text().lower()

    def test_export_review_writes(self, tmp_path):
        rev = SixMonthReview(engineer="Ada", period_end="2026-07-12", strengths=("deep",))
        paths = export.export_artifact(rev, engineer="Ada", kind="review")
        assert "deep" in paths["markdown"].read_text()

    def test_unknown_kind_raises(self):
        with pytest.raises(ValueError):
            export.export_artifact(object(), engineer="Ada", kind="bogus")

    def test_hostile_engineer_name_never_reaches_the_parser_as_markup(self):
        rec = OneOnOneRecord(engineer="<script>", date="2026-07-12", email_summary="hi")
        html = export.build_completion_html(rec)
        # Two <script> elements are legitimate: the JSON island (not executable)
        # and the bundle. A third would mean the name opened one.
        assert html.count("<script") == 2
        assert island(html)["report"]["engineer"] == "<script>"


class TestDelivery:
    def test_skips_when_smtp_unconfigured(self, monkeypatch):
        monkeypatch.setattr("yeaboi.config.get_smtp_host", lambda: "")
        monkeypatch.setattr("yeaboi.config.get_standup_email_recipients", lambda: [])
        rec = OneOnOneRecord(engineer="Ada", date="2026-07-12", email_summary="hi")
        assert delivery.send_completion_email(rec) is False

    def test_sends_via_smtp(self, monkeypatch):
        sent = {}

        class _FakeSMTP:
            def __init__(self, host, port, timeout=20):
                sent["host"] = host

            def __enter__(self):
                return self

            def __exit__(self, *a):
                return False

            def ehlo(self):
                pass

            def has_extn(self, x):
                return False

            def login(self, u, p):
                sent["login"] = u

            def send_message(self, msg):
                sent["to"] = msg["To"]

        monkeypatch.setattr("yeaboi.config.get_smtp_host", lambda: "smtp.example.com")
        monkeypatch.setattr("yeaboi.config.get_smtp_port", lambda: 587)
        monkeypatch.setattr("yeaboi.config.get_smtp_user", lambda: "me@example.com")
        monkeypatch.setattr("yeaboi.config.get_smtp_password", lambda: "pw")
        monkeypatch.setattr("yeaboi.config.get_smtp_sender", lambda: "me@example.com")
        monkeypatch.setattr("yeaboi.config.get_standup_email_recipients", lambda: ["boss@example.com"])
        monkeypatch.setattr("smtplib.SMTP", _FakeSMTP)

        rec = OneOnOneRecord(engineer="Ada", date="2026-07-12", email_subject="1:1", email_summary="hi")
        assert delivery.send_completion_email(rec) is True
        assert sent["to"] == "boss@example.com"


class TestSharedDesignSystem:
    def test_prep_html_is_self_contained_and_wears_the_mode_accent(self):
        html = export.build_prep_html(OneOnOnePrep(engineer="Ada", date="2026-07-12", talking_points=("point",)))
        assert 'data-mode="performance"' in html
        assert_self_contained(html)


class TestPayload:
    """All three artifacts render through one component, so all three build one shape.

    That is the change worth guarding: `build_prep_html`, `build_completion_html`
    and `build_review_html` used to be three copies of the same assembly that
    differed only in section titles, and each drifted from its Markdown twin
    independently. What varies now is data — a wordmark, a subtitle, a list of
    `(title, items)` — and these tests read it as data.
    """

    def test_every_artifact_names_its_engineer_and_its_kind(self):
        pages = {
            "prep": export.build_prep_html(OneOnOnePrep(engineer="Ada Lovelace", date="2026-07-27")),
            "summary": export.build_completion_html(OneOnOneRecord(engineer="Ada Lovelace", date="2026-07-27")),
            "review": export.build_review_html(SixMonthReview(engineer="Ada Lovelace")),
        }
        for wordmark, html in pages.items():
            boot = island(html)
            assert boot["chrome"]["wordmark"] == wordmark
            assert boot["chrome"]["title"].endswith("Ada Lovelace")
            # An artifact grounded in nothing carries no eyebrows at all — the
            # name is in the title and in the body's avatar row, and a third copy
            # as a header fact is noise, not emphasis.
            assert "facts" not in boot["chrome"]
            assert boot["report"]["kind"] == "performance"
            assert boot["report"]["engineer"] == "Ada Lovelace"

    def test_the_header_says_what_the_document_was_built_out_of(self):
        # What the eyebrows add is the one thing the title cannot say.
        prep = OneOnOnePrep(
            engineer="Ada Lovelace",
            evidence_sources=("standup", "analysis"),
            evidence_items=(
                EvidenceGroup(
                    source="code",
                    label="Code activity",
                    items=(ActivityEvidence(kind="pr", key="#91"), ActivityEvidence(kind="pr", key="#92")),
                ),
            ),
        )
        facts = dict(tuple(f) for f in island(export.build_prep_html(prep))["chrome"]["facts"])
        assert facts["SOURCES"] == "Standup, Team analysis"
        assert facts["EVIDENCE"] == "2 items"

    def test_a_table_of_contents_appears_only_when_it_earns_itself(self):
        # Below three entries it is a second copy of the headings.
        short = OneOnOnePrep(engineer="Ada", goals=("a",))
        assert "nav" not in island(export.build_prep_html(short))["chrome"]

        long = OneOnOnePrep(engineer="Ada", goals=("a",), gaps=("b",), improvements=("c",))
        nav = island(export.build_prep_html(long))["chrome"]["nav"]
        assert [entry[0] for entry in nav] == ["goals-to-align-on", "gaps-observed", "areas-to-improve"]

    def test_every_nav_entry_points_at_a_section_that_exists(self):
        # Two implementations of one slug rule is how a nav link ends up pointing
        # at nothing, so the exporter owns the id and the component reads it.
        prep = OneOnOnePrep(engineer="Ada", goals=("a",), gaps=("b",), improvements=("c",))
        boot = island(export.build_prep_html(prep))
        ids = {section["id"] for section in boot["report"]["sections"]}
        assert {entry[0] for entry in boot["chrome"]["nav"]} <= ids

    def test_prep_sections_are_titled_bullet_runs_in_order(self):
        prep = OneOnOnePrep(
            engineer="Ada",
            date="2026-07-27",
            activity_summary="shipped auth",
            talking_points=("tp",),
            goals=("goal",),
            carried_action_items=("carry",),
        )
        report = island(export.build_prep_html(prep))["report"]
        assert report["lead"] == {"title": "Sprint work", "text": "shipped auth"}
        assert report["sections"] == [
            {"id": "carried-over-action-items", "title": "Carried-over action items", "items": ["carry"]},
            {"id": "talking-points", "title": "Talking points", "items": ["tp"]},
            {"id": "goals-to-align-on", "title": "Goals to align on", "items": ["goal"]},
        ]

    def test_a_section_that_is_empty_for_no_known_reason_is_dropped(self):
        # Nothing to draw and nothing to say about why: a row whose only possible
        # rendering is absence.
        report = island(export.build_prep_html(OneOnOnePrep(engineer="Ada", date="2026-07-27")))["report"]
        assert report["sections"] == []
        assert "lead" not in report

    def test_a_section_that_is_empty_for_a_known_reason_rides_and_says_why(self):
        # "The model found no gaps" and "nobody ever looked" are different facts,
        # and dropping the row made them the same silence.
        prep = OneOnOnePrep(
            engineer="Ada",
            section_states=(("gaps", "not_configured", "No saved team analysis covers this engineer."),),
        )
        report = island(export.build_prep_html(prep))["report"]
        assert report["sections"] == [
            {
                "id": "gaps-observed",
                "title": "Gaps observed",
                "items": [],
                "state": "not_configured",
                "reason": "No saved team analysis covers this engineer.",
            }
        ]

    def test_a_populated_section_carries_no_state(self):
        # It explains itself; "covered" beside a list of findings is noise.
        prep = OneOnOnePrep(engineer="Ada", gaps=("thin on deploys",), section_states=(("gaps", "covered", ""),))
        (section,) = island(export.build_prep_html(prep))["report"]["sections"]
        assert "state" not in section

    def test_review_framework_rides_as_a_footnote(self):
        review = SixMonthReview(engineer="Ada", framework_used="Dreyfus", strengths=("clear writer",))
        report = island(export.build_review_html(review))["report"]
        assert report["footnote"] == "Framework: Dreyfus"
        assert report["sections"][0] == {"id": "strengths", "title": "Strengths", "items": ["clear writer"]}

    def test_completion_subject_is_a_section_not_a_second_prose_slot(self):
        record = OneOnOneRecord(
            engineer="Ada",
            date="2026-07-12",
            email_subject="1:1 recap",
            email_summary="We agreed on the plan.",
            action_items=("book the spike",),
        )
        report = island(export.build_completion_html(record))["report"]
        assert report["lead"] == {"title": "Summary email", "text": "We agreed on the plan."}
        assert report["sections"][0] == {"id": "subject", "title": "Subject", "items": ["1:1 recap"]}


class TestTheEmailBodyStillComesFromHere:
    """``delivery.py`` is why the plaintext builders survive.

    The styled renderer replaced them on every other surface, and a later reader
    could reasonably take these for dead code — this is the test that says
    otherwise, by sending a 1:1 the model wrote no summary for.
    """

    def test_a_summary_with_no_model_prose_falls_back_to_the_plaintext_rendering(self, monkeypatch):
        captured = {}

        class _FakeSMTP:
            def __init__(self, host, port, timeout=20):
                pass

            def __enter__(self):
                return self

            def __exit__(self, *a):
                return False

            def ehlo(self):
                pass

            def has_extn(self, x):
                return False

            def login(self, u, p):
                pass

            def send_message(self, msg):
                captured["body"] = msg.get_content()

        monkeypatch.setattr("yeaboi.config.get_smtp_host", lambda: "smtp.example.com")
        monkeypatch.setattr("yeaboi.config.get_smtp_port", lambda: 587)
        monkeypatch.setattr("yeaboi.config.get_smtp_user", lambda: "")
        monkeypatch.setattr("yeaboi.config.get_smtp_password", lambda: "")
        monkeypatch.setattr("yeaboi.config.get_smtp_sender", lambda: "me@example.com")
        monkeypatch.setattr("yeaboi.config.get_standup_email_recipients", lambda: ["boss@example.com"])
        monkeypatch.setattr("smtplib.SMTP", _FakeSMTP)

        record = OneOnOneRecord(
            engineer="Ada",
            date="2026-07-12",
            email_subject="1:1",
            email_summary="",
            action_items=("Write the runbook",),
        )
        assert delivery.send_completion_email(record) is True
        assert captured["body"].strip() == "\n".join(render.format_completion_lines(record)).strip()
        assert "Write the runbook" in captured["body"]
