"""Unit tests for standup automation/service-hook detection (standup/automation.py)."""

from yeaboi.standup.automation import (
    VALID_AUTOMATION_HANDLING,
    _fingerprint,
    notice_lines,
    parse_custom_markers,
    partition_automated,
)


def _review(
    author="Dev Person",
    body="",
    title="reviewed code on PR #1: fix",
    repo="repo-a",
    ts="2026-07-27T09:00:00",
    key="rc-1",
    **over,
):
    item = {
        "source": "azure-devops",
        "author": author,
        "kind": "review",
        "title": title,
        "body": body,
        "timestamp": ts,
        "key": key,
        "repository": repo,
        "url": "https://dev.azure.com/x",
    }
    item.update(over)
    return item


def _wiz_body(repo: str, n: int) -> str:
    # Near-identical scanner template: only path/line/PR number vary.
    return (
        f"Security finding: publicly exposed storage container detected in {repo}/infra/main.tf "
        f"line {n}. Severity: High. Review the attached policy before merging pull request {n}."
    )


class TestWizIncident:
    """The motivating case: 18 near-identical review comments across 6 repos, posted as the human."""

    def _items(self, body_fn=_wiz_body):
        repos = ["infra", "onboarding", "credit-risk", "security", "pricing", "automation"]
        items = []
        for i in range(18):
            repo = repos[i % 6]
            items.append(_review(body=body_fn(repo, i), repo=repo, ts=f"2026-07-27T09:00:{i:02d}", key=f"rc-{i}"))
        return items

    def test_burst_cross_repo_excludes_all(self):
        genuine = _review(body="I think we should extract this into a helper — see my inline suggestion.", key="real")
        kept, clusters = partition_automated([genuine, *self._items()])
        assert kept == [genuine]
        assert sum(c.count for c in clusters) == 18
        assert {c.reason for c in clusters} == {"burst-cross-repo"}
        assert clusters[0].author == "Dev Person"
        assert len(clusters[0].repositories) == 6

    def test_signed_bodies_hit_wiz_marker(self):
        items = self._items(lambda repo, n: f"Reported by Wiz: exposed bucket in {repo} (finding {n}).")
        kept, clusters = partition_automated(items)
        assert kept == []
        assert all(c.reason == "marker:wiz" for c in clusters)

    def test_handling_values(self):
        assert VALID_AUTOMATION_HANDLING == ("exclude", "off")


class TestMarkers:
    def test_boilerplate_marker(self):
        item = _review(body="This comment was auto-generated by the compliance pipeline.")
        kept, clusters = partition_automated([item])
        assert kept == []
        assert clusters[0].reason == "boilerplate"

    def test_scanner_names_are_attribution_shaped(self):
        # "wizard"/"fortify the tests" must NOT match — bare product words are excluded by design.
        for body in ("walk through the setup wizard flow", "let's fortify the tests here", "nice fix"):
            kept, clusters = partition_automated([_review(body=body)])
            assert clusters == [], body
            assert len(kept) == 1

    def test_kind_guard_commits_never_flagged(self):
        commit = _review(kind="commit", title="fix wiz.io finding in storage module", body="Reported by Wiz scan")
        kept, clusters = partition_automated([commit])
        assert kept == [commit]
        assert clusters == []

    def test_scanner_named_pr_title_never_flags_a_human_review(self):
        # Fetchers synthesize review titles from the PR title, so a genuine
        # human review of a PR *about* scanner work must keep its credit —
        # markers scan the body only.
        review = _review(title="approved PR #12: fix snyk findings and add semgrep rules", body="LGTM, nice cleanup!")
        kept, clusters = partition_automated([review])
        assert kept == [review]
        assert clusters == []

    def test_custom_marker_matches_bare_word(self):
        markers = parse_custom_markers("wiz, acme-scanner")
        assert [m[0] for m in markers] == ["wiz", "acme-scanner"]
        item = _review(body="Wiz found an issue in this file.")
        kept, clusters = partition_automated([item], custom_markers=markers)
        assert kept == []
        assert clusters[0].reason == "marker:wiz"

    def test_parse_custom_markers_empty(self):
        assert parse_custom_markers("") == ()
        assert parse_custom_markers("  , ,") == ()

    def test_bot_author(self):
        by_type = _review(author_type="bot", body="x")
        by_suffix = _review(author="acme-scan[bot]", body="y")
        kept, clusters = partition_automated([by_type, by_suffix])
        assert kept == []
        assert all(c.reason == "bot-author" for c in clusters)


class TestBurstHeuristic:
    def test_fingerprint_normalizes_variants(self):
        a = _fingerprint(
            _review(
                body="High severity finding 12 detected in src/app/main.py — details at https://scan.example/a1b2c3d4e5f6789"
            )
        )
        b = _fingerprint(
            _review(
                body="High severity finding 99 detected in lib/core/util.py — details at https://scan.example/deadbeefcafe123"
            )
        )
        assert a and a == b

    def test_short_repeats_never_cluster(self):
        # Distinct timestamps so only the template rule could apply — and it must not (under 40 chars).
        items = [_review(body="lgtm", repo=f"r{i}", key=f"k{i}", ts=f"2026-07-27T09:{i:02d}:00") for i in range(12)]
        kept, clusters = partition_automated(items)
        assert len(kept) == 12
        assert clusters == []

    def test_below_thresholds_kept(self):
        # 4 similar comments across 4 repos: under K=5.
        items = [
            _review(body=_wiz_body("x", 1), repo=f"r{i}", ts=f"2026-07-27T09:0{i}:00", key=f"k{i}") for i in range(4)
        ]
        kept, clusters = partition_automated(items)
        assert len(kept) == 4 and clusters == []
        # 6 similar comments in ONE repo: under the single-repo floor of 10.
        items = [
            _review(body=_wiz_body("solo", 1), repo="solo", ts=f"2026-07-27T09:0{i}:00", key=f"s{i}") for i in range(6)
        ]
        kept, clusters = partition_automated(items)
        assert len(kept) == 6 and clusters == []

    def test_single_repo_template_spam(self):
        items = [
            _review(body=_wiz_body("solo", i), repo="solo", ts=f"2026-07-27T09:00:{i:02d}", key=f"s{i}")
            for i in range(10)
        ]
        kept, clusters = partition_automated(items)
        assert kept == []
        assert clusters[0].reason == "burst-template"

    def test_same_second_across_repos(self):
        # Distinct bodies (no template match) but one identity posting in 3 repos in the same second.
        items = [
            _review(
                body=f"unique comment body number {i} with enough length to be plausible text",
                repo=f"r{i}",
                ts="2026-07-27T09:00:00",
                key=f"k{i}",
            )
            for i in range(3)
        ]
        kept, clusters = partition_automated(items)
        assert kept == []
        assert clusters[0].reason == "burst-same-second"

    def test_order_preserved_for_kept(self):
        auto = _review(body="This comment was auto-generated by scanning.", key="a")
        first = _review(body="real comment one with actual human substance", key="f", ts="2026-07-27T08:00:00")
        second = _review(body="another genuine remark from a human reviewer", key="s", ts="2026-07-27T10:00:00")
        kept, _ = partition_automated([first, auto, second])
        assert [i["key"] for i in kept] == ["f", "s"]


class TestNoticeLines:
    def test_marker_notice_copy(self):
        _, clusters = partition_automated([_review(body="Reported by Wiz: finding.")])
        line, tail = notice_lines(clusters)
        assert "Excluded 1 review item(s) posted under 'Dev Person'" in line
        assert "matched 'wiz'" in line
        # The how-to-tune instructions live in the single shared tail line, not
        # in every cluster line — the notice recurs daily, the manual must not.
        assert "automation_markers" not in line
        assert "automation_markers" in tail and "automation_handling" in tail

    def test_burst_notice_copy(self):
        items = [
            _review(body=_wiz_body(f"r{i % 6}", i), repo=f"r{i % 6}", ts=f"2026-07-27T09:00:{i:02d}", key=f"k{i}")
            for i in range(18)
        ]
        _, clusters = partition_automated(items)
        line, tail = notice_lines(clusters)
        assert line.startswith("Excluded 18 near-identical review item(s) posted under 'Dev Person'")
        assert "across 6 repositories" in line
        assert "'off'" in tail

    def test_tune_tail_appears_once_for_many_clusters(self):
        _, marker = partition_automated([_review(body="Reported by Wiz: finding.")])
        _, burst = partition_automated(
            [
                _review(body=_wiz_body(f"r{i % 6}", i), repo=f"r{i % 6}", ts=f"2026-07-27T09:00:{i:02d}", key=f"k{i}")
                for i in range(18)
            ]
        )
        lines = notice_lines([*marker, *burst])
        assert len(lines) == 3
        assert sum("automation_handling" in line for line in lines) == 1

    def test_no_clusters_no_tail(self):
        assert notice_lines([]) == []
