"""Pin the live snapshot shapes the TypeScript boards are written against.

``types/board.ts`` is hand-written, because a state shape carries meaning a
codegen cannot express — which fields are per-viewer, which one deliberately
does not bump ``revision``, which is a command rather than a value. The cost of
hand-writing it is that nothing stops the server from quietly dropping a field
the bundle still reads, and the symptom of that is a board that renders
``undefined`` to a teammate on a tunnel while every test on both sides passes.

So this drives a **real board through a real round** and writes the snapshots to
``frontend/src/test/fixtures/``. ``wire.ts`` then asserts each one ``satisfies``
its interface, and ``npm run typecheck`` fails if the server stopped sending
something the board promises.

The slide deck and the six static exports are here too, for the same reason with
the failure delayed rather than softened: those are *files*. A dropped field
renders as a blank slide on a projector, or an empty section in a report someone
opens months later — with no server, no log, and no way to tell it apart from a
report that genuinely had nothing to say.

Two directions, only one of them guarded, and deliberately so:

* A **removed or renamed** field fails the TypeScript build — the fixture no
  longer has what the interface requires.
* An **added** field does not, because TypeScript excess-property-checks only
  fresh object literals and an imported JSON module is not one.

That is the useful direction: adding a field breaks nothing, removing one breaks
a board. The check here (regenerate, compare, fail on difference) is the same
shape as the committed-bundle staleness check in ``make web-check`` — the
fixture is a build artifact under review, not a hand-written expectation that
can invent its own contract.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from yeaboi.agent.state import DeliveredItem, DeliveryReport, SupportingSignal
from yeaboi.poker.board import PokerBoard
from yeaboi.reporting.presentation import deck_payload
from yeaboi.reporting.style import DeckStyle
from yeaboi.retro.board import RetroBoard

FIXTURES = Path(__file__).resolve().parents[2] / "frontend" / "src" / "test" / "fixtures"

#: An export page's own credit line, which carries the day it was written.
_STAMPED_FOOTER = re.compile(r"Generated by yeaboi\.ai • \d{4}-\d{2}-\d{2}")

pytestmark = pytest.mark.skipif(
    not FIXTURES.parent.is_dir(), reason="frontend sources are not part of an installed wheel"
)


def _retro_snapshot() -> dict:
    """A retro mid-ceremony: cards from two people, a reaction, presence, a timer."""
    board = RetroBoard("wire-retro", project_name="yeaboi", sprint_name="Sprint 42")
    board.heartbeat("pid-a", name="Ada", avatar="🦊")
    board.heartbeat("pid-b", name="Grace", avatar="🐙")
    mine = board.add_card(grid="went_well", text="Shipped the tunnel", author="Ada", origin="web", pid="pid-a")
    board.add_card(grid="action_items", text="Alert on staging", author="Grace", origin="web", pid="pid-b")
    # A carried-over item exercises the `status` field, which is `''` on every
    # authoring-grid card and so would otherwise never appear in the fixture.
    board.add_card(grid="action_items", text="From last sprint", author="Ada", origin="carryover", pid="pid-a")
    assert mine is not None
    board.toggle_reaction(mine.id, "👍", "pid-b")
    board.start_timer(300)
    board.set_broadcast_theme("forest")
    # Per-viewer: `mine` must be true for Ada's own card, which is the field the
    # edit and delete controls hang off.
    return board.state_snapshot(viewer_pid="pid-a")


def _poker_snapshots() -> dict[str, dict]:
    """A poker round in each phase, plus the peek projection.

    Three snapshots rather than one, because the poker payload is genuinely
    phase-shaped: vote secrecy means ``votes[].value`` does not exist at all
    while voting, and ``duel`` is null until the floor opens. A single fixture
    would pin whichever phase it happened to capture and leave the others
    unguarded.
    """
    tickets = [
        {
            "key": "YB-1",
            "summary": "Long-poll the board",
            "description_text": "The tunnel buffers SSE.",
            "acceptance_text": "Updates land in under a second.",
            "type": "Story",
            "state": "To Do",
            "assignee": "Ada",
            "url": "https://example.invalid/browse/YB-1",
            "story_points": None,
            "source": "jira",
        },
        {"key": "YB-2", "summary": "Quantise the duck", "story_points": 3},
    ]
    board = PokerBoard("wire-poker", project_name="yeaboi", source="jira", tickets=tickets)
    board.heartbeat("pid-a", name="Ada", avatar="🦊")
    board.heartbeat("pid-b", name="Grace", avatar="🐙")
    board.cast_vote("pid-a", "3")
    board.cast_vote("pid-b", "13")
    board.start_timer(120)

    voting = board.state_snapshot(viewer_pid="pid-a")

    board.reveal()
    board.set_ai_note("Two calls to an unfamiliar API.", suggested=5.0, confidence="medium", evidence=["No SDK yet."])
    revealed = board.state_snapshot(viewer_pid="pid-a")

    opened, error = board.open_duel(90)
    assert opened, error
    # Viewed as the low voter, so `mine_role` is exercised as something other
    # than the empty string a bystander sees.
    duel = board.state_snapshot(viewer_pid="pid-a")

    peek = board.ticket_view(1)
    assert peek is not None

    return {"poker.voting": voting, "poker.revealed": revealed, "poker.duel": duel, "ticket.peek": peek}


def _delivery_report() -> DeliveryReport:
    """One report with every section populated.

    Shared by the deck fixture and the HTML export fixture, which read the same
    artifact through two renderers — so a field that disappears breaks both, and
    the diff says which renderers were relying on it.

    Two delivered items, one of them unassigned, because ``assignee`` is the
    optional field in that row and one item can only pin it present or absent.
    """
    return DeliveryReport(
        period_label="Last month (~2 sprints)",
        period_start="2026-06-15",
        period_end="2026-07-13",
        project_name="Acme Portal",
        sprint_names=("Sprint 11", "Sprint 12"),
        headline="Two sprints of strong delivery.",
        executive_summary="We shipped SSO. Checkout got materially faster for everyone.",
        themes=(("Security", ("SSO", "MFA")), ("Performance", ("Faster checkout",))),
        highlights=("SSO live", "2x faster checkout"),
        metrics=(("Items delivered", "12"), ("Story points", "48")),
        delivered_items=(
            DeliveredItem(key="A-1", title="Ship SSO", status="Done", assignee="Ada"),
            DeliveredItem(key="A-2", title="Cache the ticket peek", status="Done"),
        ),
        supporting_signals=(SupportingSignal(kind="pull_requests", source="github", count=24),),
        emoji_theme=(("headline", "🚀"), ("summary", "📋"), ("metrics", "📊"), ("themes", "🧩")),
        warnings=("Jira was reachable for 12 of 14 days.",),
    )


def _deck_snapshot() -> dict:
    """A slide deck payload with one slide of every kind.

    Not a live board, but the same contract and the same failure mode: an
    exported deck is a file, so a field the renderer reads and the exporter
    stopped sending shows up as a blank slide on someone's projector months
    later, with nothing in any log. The style is deliberately non-default —
    every knob at its default resolves to a value the deck would have anyway,
    which pins nothing.
    """
    style = DeckStyle(heading_color="accent2", font_scale="large", slide_numbers=True, footer_text="ACME Corp")
    return deck_payload(_delivery_report(), theme="aurora", style=style)


def _export_snapshots() -> dict[str, dict]:
    """The boot payload of every migrated static export, straight out of its page.

    Here for the same reason the deck is, and with more surface to lose: these
    are *files*. Nothing else checks that ``ExportReport`` in ``export/boot.ts``
    still describes what Python writes — the exporters' own tests assert against
    hand-written expectations, so a field renamed on both sides at once passes
    every one of them and renders an empty section on a report somebody opens
    six months later, with no server and no log to look at.

    Read out of the rendered page rather than from a payload builder, because
    the page is the artifact. A field lost between the builder and
    ``export_page`` would be invisible to a snapshot of the builder alone.

    Built from frozen artifacts rather than from a live board, unlike the board
    fixtures above — for these exporters the artifact *is* the input contract.
    Every one of them is a persisted, fully-defaulted dataclass, and constructing
    one describes nothing that does not exist.

    Each fixture deliberately carries the *optional* fields too — a skipped
    poker ticket, an AI-authored retro card, an empty retro column, a trend with
    two points. An interface's optionality is only pinned by a fixture that has
    the thing, and by another that does not.
    """
    from tests._pages import island
    from yeaboi.agent.state import (
        AnonymizedOutput,
        OneOnOnePrep,
        PokerReport,
        PokerTicketResult,
        PokerVote,
        RetroCard,
        RetroReport,
        RoadmapAnalysis,
        RoadmapProject,
    )
    from yeaboi.anonymize.export import build_anonymized_html
    from yeaboi.performance.export import build_prep_html
    from yeaboi.poker.export import build_poker_html
    from yeaboi.reporting.export import build_report_html
    from yeaboi.retro.export import build_retro_html
    from yeaboi.roadmap.export import build_roadmap_html

    poker = PokerReport(
        date="2026-07-13",
        session_id="wire-poker",
        project_name="yeaboi",
        source="jira",
        scope_label="Sprint 42",
        tickets=(
            PokerTicketResult(
                key="YB-1",
                url="https://example.invalid/browse/YB-1",
                summary="Long-poll the board",
                initial_points=3.0,
                final_points=5.0,
                estimated=True,
                votes=(PokerVote("Ada", "🦊", "3"), PokerVote("Grace", "🐙", "13")),
                ai_note="Two calls to an unfamiliar API.",
                duel_transcript="Ada (voted 3) — turn 1:\nThe endpoint already exists.",
                duel_low="Ada (3)",
                duel_high="Grace (13)",
            ),
            # Skipped, so `final` is null on exactly one ticket. A fixture with
            # only the estimated kind would leave that null unpinned.
            PokerTicketResult(key="YB-2", summary="Quantise the duck", initial_points=3.0),
        ),
        participants=("Ada", "Grace"),
        generated_at="2026-07-13T10:00:00+00:00",
    )

    retro = RetroReport(
        date="2026-07-10",
        session_id="wire-retro",
        sprint_name="Sprint 42",
        cards=(
            RetroCard(grid="went_well", text="Shipped the tunnel", author="Ada", origin="web"),
            RetroCard(grid="action_items", text="Alert on staging", author="AI", origin="ai"),
        ),
        participants=("Ada", "Grace"),
        carried_action_items=(RetroCard(grid="action_items", text="From last sprint", status="done"),),
    )
    # Two runs, so the trend is a populated object rather than the null that
    # would leave `Trend`'s own shape unguarded.
    history = [
        {"retro_date": "2026-07-10", "card_count": 2},
        {"retro_date": "2026-06-26", "card_count": 5},
    ]

    roadmap = RoadmapAnalysis(
        source_type="notion",
        source_label="H2 roadmap",
        summary="Two projects, both security.",
        projects=(
            RoadmapProject(
                name="SSO rollout",
                description="Ship SSO for all tenants.",
                size="large",
                rationale="Blocks three enterprise deals.",
                priority=1,
                themes=("Security",),
                quarter="Q3 2026",
            ),
        ),
        warnings=("Quarter inferred from headings.",),
        generated_at="2026-07-13",
    )

    prep = OneOnOnePrep(
        engineer="Ada",
        date="2026-07-13",
        talking_points=("Sprint 42 scope",),
        feedback=("Clear PR descriptions",),
        goals=("Lead the SSO rollout",),
        gaps=("Little exposure to on-call",),
        improvements=("Pair on the alerting runbook",),
        carried_action_items=("Book the runbook session",),
        activity_summary="Shipped SSO behind a flag.",
        warnings=("Jira was reachable for 12 of 14 days.",),
    )

    masked = AnonymizedOutput(
        anonymized_text="# Retro\n\n- **PERSON_1** shipped `TICKET_1`.\n",
        source_mode="retro",
        generated_at="2026-07-13",
        warnings=("2 names could not be matched.",),
    )

    return {
        "export.poker": island(build_poker_html(poker)),
        "export.retro": island(build_retro_html(retro, history=history)),
        "export.reporting": island(build_report_html(_delivery_report())),
        "export.roadmap": island(build_roadmap_html(roadmap)),
        "export.performance": island(build_prep_html(prep)),
        "export.anonymize": island(build_anonymized_html(masked, title="Retro")),
    }


def _fixtures() -> dict[str, dict]:
    return {
        "deck": _deck_snapshot(),
        "retro": _retro_snapshot(),
        **_poker_snapshots(),
        **_export_snapshots(),
    }


def _normalise(payload: dict) -> dict:
    """Pin the values that differ between two identical runs.

    Clocks move, and card ids are random hex. Committing either would make this
    test rewrite its own fixtures every run, and a fixture that always changes
    reports nothing when the thing it watches finally does.

    Pinned to a constant of the same kind rather than deleted: the guard reads
    *types*, so a number has to stay a number and a null has to stay a null. A
    dropped field would read as "the server stopped sending this", which is
    exactly the signal being protected.
    """
    frozen = json.loads(json.dumps(payload))
    counter = 0

    def walk(node: object) -> object:
        nonlocal counter
        if isinstance(node, dict):
            out: dict = {}
            for key, value in node.items():
                if key in ("now_epoch", "end_epoch") and isinstance(value, (int, float)):
                    out[key] = 0
                elif key == "created_at" and isinstance(value, str):
                    out[key] = "2026-01-01T00:00:00+00:00"
                elif key == "generated" and isinstance(value, str):
                    # The deck's export date. Unpinned it would rewrite this
                    # fixture at midnight, which is the one way to teach
                    # everyone to ignore the diff.
                    out[key] = "2026-01-01"
                elif key == "footer" and isinstance(value, str) and _STAMPED_FOOTER.fullmatch(value):
                    # Same, for the exports, whose footer ends in today's date.
                    # Matched rather than keyed on the name: the deck's *style*
                    # also has a `footer`, and that one is text the host typed.
                    out[key] = "Generated by yeaboi.ai • 2026-01-01"
                elif key == "id" and isinstance(value, str):
                    # Card ids only — `reaction_events[].id` is an int and is a
                    # monotonic counter, so it is already stable.
                    counter += 1
                    out[key] = f"card{counter:04d}"
                else:
                    out[key] = walk(value)
            return out
        if isinstance(node, list):
            return [walk(item) for item in node]
        return node

    return walk(frozen)  # type: ignore[return-value]


def _write(name: str, payload: dict) -> str:
    text = json.dumps(_normalise(payload), indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    (FIXTURES / f"{name}.json").write_text(text, encoding="utf-8")
    return text


class TestWireFixtures:
    def test_committed_fixtures_match_the_live_snapshots(self):
        """Regenerate and compare. A difference means the wire shape moved.

        The fix is never to edit the JSON: run this test, commit what it wrote,
        and then make ``types/board.ts`` agree with it — in that order, so the
        TypeScript follows the server rather than the other way round.
        """
        FIXTURES.mkdir(parents=True, exist_ok=True)
        stale: list[str] = []
        for name, payload in _fixtures().items():
            path = FIXTURES / f"{name}.json"
            before = path.read_text(encoding="utf-8") if path.exists() else ""
            after = _write(name, payload)
            if before != after:
                stale.append(name)
        assert not stale, (
            f"wire fixtures regenerated: {', '.join(stale)}. The snapshot shape changed — "
            "commit frontend/src/test/fixtures/ and check types/board.ts still describes it."
        )

    def test_voting_snapshot_carries_no_vote_values(self):
        """The property the fixture exists to make legible, asserted directly.

        A `satisfies` check would happily accept a `value` on every seat; only
        this says the field must be *absent* while the round is open. Vote
        secrecy is the one poker invariant a rendering bug cannot recover from.
        """
        voting = _poker_snapshots()["poker.voting"]
        assert voting["phase"] == "voting"
        assert voting["votes"], "fixture must have seats, or this asserts nothing"
        for seat in voting["votes"]:
            assert "value" not in seat
            assert set(seat) == {"name", "avatar", "voted"}
        assert voting["distribution"] == {}
        assert voting["median"] is None and voting["suggestion"] is None
        # …and the viewer still sees their own, which is what makes the deck
        # able to show a selected card without leaking anyone else's.
        assert voting["mine_value"] == "3"

    def test_peek_projection_omits_round_internals(self):
        peek = _poker_snapshots()["ticket.peek"]
        for internal in ("accepted_votes", "ai_note", "duel_transcript", "initial_points", "source"):
            assert internal not in peek
