"""Unit tests for Daily Standup Markdown + HTML export."""

from tests._pages import markup
from yeaboi.agent.state import MemberUpdate, StandupReport
from yeaboi.standup import export
from yeaboi.standup.export import (
    _leftover_links,
    _linkify,
    _linkify_md,
    _team_summary_html,
    _ticket_key_map,
    build_standup_html,
    build_standup_markdown,
    export_standup,
)


def _report(**over) -> StandupReport:
    base = dict(
        date="2026-07-10",
        session_id="demo",
        sprint_name="Sprint 5",
        sprint_day=3,
        sprint_total_days=10,
        confidence_pct=82,
        confidence_label="At risk",
        confidence_rationale="behind ideal burn",
        team_summary="steady progress",
        member_updates=(
            MemberUpdate(name="Alice", summary="login page", source="inferred"),
            MemberUpdate(
                name="Bob",
                summary="paired on auth",
                blockers="waiting on review",
                source="combined",
                self_report="paired with Alice on auth",
            ),
        ),
        activity_counts=(("github", 2), ("jira", 1)),
        warnings=("Jira: authentication failed — check token",),
    )
    base.update(over)
    return StandupReport(**base)


class TestMarkdown:
    def test_contains_key_sections(self):
        md = build_standup_markdown(_report())
        assert "# Daily Standup — 2026-07-10" in md
        assert "day 3 of 10" in md
        assert "**Confidence:** At risk (82%)" in md
        assert "## ⚠ Notices" in md
        assert "Jira: authentication failed" in md
        assert "## Team Summary" in md
        # Member updates render as per-member sections with labeled bullets.
        assert "### Alice" in md
        assert "### Bob (you)" in md
        assert "login page" in md
        assert "- **Blocker:** waiting on review" in md
        assert "> ✍ paired with Alice on auth" in md
        assert "github: 2, jira: 1" in md
        # Branded footer with a real link.
        assert "🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)" in md

    def test_empty_report(self):
        md = build_standup_markdown(StandupReport(date="2026-07-10"))
        assert "# Daily Standup" in md
        assert "_No individual updates._" in md

    def test_images_in_screenshots_section(self):
        md = build_standup_markdown(_report(images=("/tmp/shot1.png", "/tmp/shot2.png")))
        # Screenshots follow the member sections in their own section.
        assert "## Screenshots" in md
        assert "![Screenshot](/tmp/shot1.png)" in md
        assert "![Screenshot](/tmp/shot2.png)" in md

    def test_pipe_in_member_content_passes_through(self):
        # No table anymore — pipes need no escaping and survive verbatim.
        rep = _report(member_updates=(MemberUpdate(name="Alice", summary="a | b", source="inferred"),))
        md = build_standup_markdown(rep)
        assert "a | b" in md

    def test_category_bullets_with_links(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="tickets and code",
                    ticketing_summary="moved PSOT-1 to review",
                    ticketing_links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                    code_summary="opened a PR",
                    code_links=(("fix login", "https://github.com/o/r/pull/9"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        # Ticket key becomes an inline markdown link inside the bullet text.
        assert "- **Ticketing:** moved [PSOT-1](https://x.atlassian.net/browse/PSOT-1) to review" in md
        # Non-ticket-shaped link labels stay as explicit refs on the bullet.
        assert "- **Code:** opened a PR — [fix login](https://github.com/o/r/pull/9)" in md

    def test_team_summary_bullets_bold_names(self):
        rep = _report(team_summary="Alice shipped the login page. Bob is blocked on review.")
        md = build_standup_markdown(rep)
        assert "- **Alice** shipped the login page." in md
        assert "- **Bob** is blocked on review." in md


class TestMemberLinks:
    def test_markdown_ticket_key_linked_inline(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="moved PSOT-1 to review",
                    links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        # The key text itself is the link — no separate Links line needed.
        assert "moved [PSOT-1](https://x.atlassian.net/browse/PSOT-1) to review" in md
        assert "**Links:**" not in md

    def test_markdown_legacy_links_bullet_for_unmentioned_refs(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="general work",
                    links=(("fix login", "https://github.com/o/r/pull/9"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        assert "- **Links:** [fix login](https://github.com/o/r/pull/9)" in md

    def test_html_links_are_anchors_and_escaped(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="work",
                    links=(("<b>PSOT-1</b>", "https://x.atlassian.net/browse/PSOT-1?a=1&b=2"),),
                ),
            )
        )
        html = build_standup_html(rep)
        assert "<a href='https://x.atlassian.net/browse/PSOT-1?a=1&amp;b=2'" in html
        assert "&lt;b&gt;PSOT-1&lt;/b&gt;" in html  # label escaped, not injected

    def test_no_links_no_section(self):
        md = build_standup_markdown(_report())
        assert "**Links:**" not in md


class TestLinkify:
    URL = "https://x.atlassian.net/browse/PSOT-1"

    def test_mapped_key_becomes_anchor(self):
        html = _linkify("moved PSOT-1 to review", {"PSOT-1": self.URL})
        assert f"<a href='{self.URL}' target='_blank' rel='noopener'>PSOT-1</a>" in html

    def test_unknown_key_untouched(self):
        html = _linkify("moved PSOT-2 to review", {"PSOT-1": self.URL})
        assert "<a" not in html
        assert "PSOT-2" in html

    def test_escapes_once_no_double_escape(self):
        html = _linkify("a & b <script> PSOT-1", {"PSOT-1": self.URL})
        assert "a &amp; b" in html
        assert "&amp;amp;" not in html
        assert "&lt;script&gt;" in html

    def test_href_is_attribute_escaped(self):
        html = _linkify("PSOT-1", {"PSOT-1": "https://x/browse/PSOT-1?a=1&b='c'"})
        assert "href='https://x/browse/PSOT-1?a=1&amp;b=&#x27;c&#x27;'" in html

    def test_longer_key_never_half_matches(self):
        m = {"PSOT-1": "https://x/1", "PSOT-12": "https://x/12"}
        html = _linkify("closed PSOT-12", m)
        assert "href='https://x/12'" in html
        assert "https://x/1'" not in html

    def test_markdown_flavor(self):
        assert _linkify_md("moved PSOT-1", {"PSOT-1": self.URL}) == f"moved [PSOT-1]({self.URL})"

    def test_key_map_from_link_evidence(self):
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_links=(("PSOT-1", self.URL),)),)
        )
        assert _ticket_key_map(rep) == {"PSOT-1": self.URL}

    def test_fallback_prefix_gated(self, monkeypatch):
        monkeypatch.setenv("JIRA_BASE_URL", "https://x.atlassian.net")
        rep = _report(
            team_summary="PSOT-99 landed; encoded as UTF-8 with SHA-256 digests per ISO-8601.",
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_links=(("PSOT-1", self.URL),)),),
        )
        key_map = _ticket_key_map(rep)
        assert key_map["PSOT-99"] == "https://x.atlassian.net/browse/PSOT-99"
        # Prefix gate: regex-shaped non-tickets never become links.
        assert "UTF-8" not in key_map and "SHA-256" not in key_map and "ISO-8601" not in key_map

    def test_no_fallback_without_base_url(self, monkeypatch):
        monkeypatch.delenv("JIRA_BASE_URL", raising=False)
        rep = _report(
            team_summary="PSOT-99 landed.",
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_links=(("PSOT-1", self.URL),)),),
        )
        assert "PSOT-99" not in _ticket_key_map(rep)

    def test_no_evidence_no_guessing(self, monkeypatch):
        monkeypatch.setenv("JIRA_BASE_URL", "https://x.atlassian.net")
        rep = _report(team_summary="PSOT-99 landed.")
        assert _ticket_key_map(rep) == {}

    def test_leftover_links(self):
        links = (("PSOT-1", "https://x/1"), ("fix login", "https://x/pr/9"))
        # PSOT-1 is mentioned inline → only the PR title is left over.
        assert _leftover_links("moved PSOT-1", links) == [("fix login", "https://x/pr/9")]
        # Nothing mentioned → both are left over.
        assert _leftover_links("quiet day", links) == list(links)


class TestTeamSummaryHtml:
    def test_bullets_bold_names_and_link_tickets(self):
        html = _team_summary_html(
            "Alice shipped PSOT-1. Bob is blocked on the auth migration.",
            {"PSOT-1": "https://x/browse/PSOT-1"},
            ["Alice Smith", "Bob"],
        )
        assert html.count("<li>") == 2
        assert "<strong>Alice</strong>" in html
        assert "<strong>Bob</strong>" in html
        assert ">PSOT-1</a>" in html

    def test_single_sentence_stays_paragraph(self):
        html = _team_summary_html("Steady progress across the board.", {}, ["Alice"])
        assert "<ul>" not in html
        assert "<p>Steady progress across the board.</p>" in html

    def test_full_name_not_double_bolded(self):
        html = _team_summary_html("Alice Smith shipped it.", {}, ["Alice Smith"])
        assert "<strong>Alice Smith</strong>" in html
        assert "<strong><strong>" not in html

    def test_xss_member_name_bolded_safely(self):
        html = _team_summary_html("<i>Eve</i> shipped it.", {}, ["<i>Eve</i>"])
        assert "<i>" not in html
        assert "<strong>&lt;i&gt;Eve&lt;/i&gt;</strong>" in html

    def test_rendered_in_full_page(self):
        rep = _report(team_summary="Alice shipped the login page. Bob is blocked.")
        html = build_standup_html(rep)
        assert "<strong>Alice</strong>" in html
        assert html.count("<li>Alice") <= 1  # sanity: bullets, not duplication


class TestHtml:
    def test_selfcontained_and_escaped(self):
        rep = _report(team_summary="<script>alert(1)</script>")
        html = build_standup_html(rep)
        assert html.startswith("<!DOCTYPE html>")
        assert "<style>" in html  # inline CSS, self-contained
        assert "card story-card" in html  # member cards replaced the data table
        assert "At risk" in html
        assert "Jira: authentication failed" in html
        # user content is escaped, not injected
        assert "<script>alert(1)</script>" not in html
        assert "&lt;script&gt;" in html

    def test_empty_report(self):
        html = build_standup_html(StandupReport(date="2026-07-10"))
        assert "No individual updates." in html

    def test_overview_stat_tiles(self):
        html = build_standup_html(_report())
        assert "3 / 10" in html  # sprint day tile
        assert "Sprint day" in html
        assert "82%" in html  # confidence tile
        assert ">Members</div>" in html
        assert ">Activity items</div>" in html  # 2 + 1 = 3 items examined
        assert ">3</div>" in html

    def test_nav_links_present_sections(self):
        html = build_standup_html(_report())
        assert 'href="#overview"' in html
        assert 'href="#summary"' in html
        assert 'href="#updates"' in html
        assert 'href="#details"' in html
        assert 'href="#screenshots"' not in html  # no images in the base report

    def test_ticket_key_linked_inline_no_link_line(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="moved PSOT-1 to review",
                    ticketing_summary="PSOT-1 now in review",
                    ticketing_links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                ),
            )
        )
        html = build_standup_html(rep)
        assert ">PSOT-1</a>" in html
        assert "🔗" not in html  # no separate link lines anywhere

    def test_blocked_member_card(self):
        html = build_standup_html(_report())
        assert "card story-card critical" in html  # Bob has a blocker
        assert "badge-danger" in html
        assert ">Blocker</span> waiting on review" in html
        assert ">BLOCKED<" in html.upper() or ">blocked</span>" in html  # blocked chip

    def test_activity_count_chips_only_when_nonzero(self):
        rep = _report(
            member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_activity_count=3, code_activity_count=0),)
        )
        html = markup(build_standup_html(rep))
        assert ">3 tickets</span>" in html
        assert "0 code" not in html

    def test_activity_count_chip_singular(self):
        rep = _report(member_updates=(MemberUpdate(name="Alice", summary="x", ticketing_activity_count=1),))
        html = build_standup_html(rep)
        assert ">1 ticket</span>" in html
        assert "1 tickets" not in html

    def test_self_report_ticket_key_linked(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    self_report="will pick up PSOT-14 next",
                    ticketing_links=(("PSOT-14", "https://x.atlassian.net/browse/PSOT-14"),),
                ),
            )
        )
        html = build_standup_html(rep)
        assert "will pick up <a href='https://x.atlassian.net/browse/PSOT-14'" in html

    def test_self_report_quote_and_you_chip(self):
        html = build_standup_html(_report())
        assert "class='quote'" in html
        assert "paired with Alice on auth" in html
        assert ">you</span>" in html

    def test_category_sections_render(self):
        # Adaptive grid: a category earns its column with activity or links.
        html = build_standup_html(
            _report(
                member_updates=(
                    MemberUpdate(
                        name="Alice",
                        summary="busy day",
                        ticketing_summary="Moved PSOT-1.",
                        ticketing_activity_count=1,
                        code_summary="Merged a PR.",
                        code_activity_count=1,
                        documentation_summary="Updated the runbook.",
                        documentation_activity_count=1,
                    ),
                ),
            )
        )
        assert ">Ticketing</h3>" in html
        assert ">Code</h3>" in html
        assert ">Documentation</h3>" in html

    def test_images_base64_embedded(self, tmp_path):
        img = tmp_path / "shot.png"
        img.write_bytes(b"\x89PNG fake")
        html = build_standup_html(_report(images=(str(img),)))
        assert "Screenshots" in html
        assert "data:image/png;base64," in html

    def test_missing_image_skipped(self):
        # markup(): the inlined bundle carries the duck sprites as data URIs, so
        # a check against the whole document reads those instead of the report.
        html = markup(build_standup_html(_report(images=("/nope/gone.png",))))
        assert "data:image" not in html


class TestExportWrites:
    def test_writes_md_and_html(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        paths = export_standup(_report(), project_name="My Demo Project")
        assert paths["markdown"].exists() and paths["markdown"].suffix == ".md"
        assert paths["html"].exists() and paths["html"].suffix == ".html"
        # slug of project name is used for the subdir
        assert paths["markdown"].parent.name == "my-demo-project"
        assert "Daily Standup" in paths["markdown"].read_text()
        assert paths["html"].read_text().startswith("<!DOCTYPE html>")

    def test_rerun_same_day_overwrites(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        export_standup(_report(confidence_pct=50), project_name="Demo")
        paths = export_standup(_report(confidence_pct=90), project_name="Demo")
        # one dated file per day, latest wins
        files = list(paths["markdown"].parent.glob("standup-2026-07-10.*"))
        assert len(files) == 2  # .md + .html
        assert "(90%)" in paths["markdown"].read_text()

    def test_slug_helper(self):
        assert export._slug("My Project!!") == "my-project"
        assert export._slug("") == "standup"

    def test_images_localized_into_export_dir(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        img = tmp_path / "shot.png"
        img.write_bytes(b"png")
        paths = export_standup(_report(images=(str(img),)), project_name="Demo")
        md = paths["markdown"].read_text()
        assert "![Screenshot](images/shot.png)" in md
        assert (paths["markdown"].parent / "images" / "shot.png").exists()


class TestSkippedSourcesLine:
    def test_markdown_lists_skipped_sources(self):
        md = build_standup_markdown(_report(skipped_sources=(("github", "STANDUP_GITHUB_REPO not set"),)))
        assert "Sources skipped — github (STANDUP_GITHUB_REPO not set)" in md

    def test_html_lists_skipped_sources_in_details(self):
        html = build_standup_html(_report(skipped_sources=(("notion", "NOTION_ROOT_PAGE_ID not set"),)))
        assert "Sources skipped" in html
        assert "NOTION_ROOT_PAGE_ID not set" in html
        assert "ac-list" in html  # rendered inside the Details list

    def test_plaintext_lists_skipped_sources(self):
        from yeaboi.standup.render import format_standup_plaintext

        text = format_standup_plaintext(_report(skipped_sources=(("confluence", "CONFLUENCE_SPACE_KEY not set"),)))
        assert "Sources skipped — confluence (CONFLUENCE_SPACE_KEY not set)" in text

    def test_no_skipped_sources_no_line(self):
        from yeaboi.standup.render import format_standup_plaintext

        assert "Sources skipped" not in format_standup_plaintext(_report())


class TestSharedDesignSystem:
    def test_standup_html_uses_shared_theme(self):
        html = build_standup_html(_report())
        assert 'data-theme="midnight"' in html
        assert "yeaboi-export-theme" in html  # theme switcher present
        assert 'src="http' not in html and "<link" not in html  # self-contained


def _history(*rows):
    """Store-shaped history rows, newest-first like StandupStore.get_history."""
    out = []
    for day, pct, *rest in rows:
        out.append(
            {
                "id": len(out),
                "run_at": f"{day}T10:00:00",
                "standup_date": day,
                "sprint_day": 1,
                "confidence_pct": pct,
                "status": rest[0] if rest else "success",
            }
        )
    return out


class TestVisuals:
    def test_sparkline_present_with_history(self):
        html = build_standup_html(
            _report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70), ("2026-07-08", 65))
        )
        # class attribute, not the bare token — ".spark-wrap" also lives in the stylesheet
        assert 'class="spark-wrap"' in html and "<svg" in html
        assert "Confidence trend" in html

    def test_sparkline_absent_without_trend(self):
        assert 'class="spark-wrap"' not in build_standup_html(_report())
        assert 'class="spark-wrap"' not in build_standup_html(_report(), history=_history(("2026-07-10", 82)))

    def test_sparkline_oldest_date_on_left(self):
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-01", 50)))
        labels = html.split('class="spark-labels"')[1]
        first = labels.split("<span>")[1].split("</span>")[0]
        assert first == "2026-07-01"

    def test_sparkline_skips_failed_and_dedupes_and_ignores_future(self):
        history = _history(
            ("2026-07-12", 90),  # after report.date → ignored
            ("2026-07-10", 82),
            ("2026-07-10", 40),  # older rerun of same day → deduped
            ("2026-07-09", 0, "failed"),  # failed → skipped
            ("2026-07-08", 60),
        )
        html = build_standup_html(_report(), history=history)
        points = html.split('points="')[1].split('"')[0].split()
        assert len(points) == 2  # 07-08 and 07-10 only
        assert "2026-07-12" not in html.split('class="spark-labels"')[1].split("</div>")[0]

    def test_sparkline_end_dot_uses_confidence_color(self):
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70)))
        circle = html.split("<circle")[1].split("/>")[0]
        assert 'fill="var(--warn)"' in circle  # "At risk"

    def test_sprint_tile_progress_bar(self):
        html = build_standup_html(_report())
        # The bar follows the "Sprint day" label inside the same tile.
        after_label = html.split("Sprint day</div>")[1][:200]
        assert 'class="capacity-bar"' in after_label
        html_no_days = build_standup_html(_report(sprint_total_days=0, sprint_day=0))
        assert 'class="capacity-bar"' not in html_no_days.split("<footer")[0].split('<div class="container">')[1]

    def test_team_activity_bars(self):
        rep = _report(
            member_updates=(
                MemberUpdate(name="Alice", summary="x", ticketing_activity_count=3, code_activity_count=2),
                MemberUpdate(name="Bob", summary="y", documentation_activity_count=1),
                MemberUpdate(name="Zed", summary="quiet"),  # all-zero → no bar row
            )
        )
        html = build_standup_html(rep)
        assert "Team activity" in html
        assert html.count("class='bar-row'") == 2  # class attr — ".bar-row" also lives in the stylesheet
        assert 'class="seg-track"' in html
        assert "Tickets" in html and "Code" in html and "Docs" in html  # legend
        block = html.split("Team activity")[1].split("</div></div>")[0]
        assert "Zed" not in block

    def test_team_activity_absent_when_no_counts(self):
        assert "Team activity" not in build_standup_html(_report())

    def test_source_bar_with_counted_legend(self):
        html = build_standup_html(_report())
        details = html.split('id="details"')[1]
        assert "seg-track" in details
        assert "github 2" in details and "jira 1" in details

    def test_source_bar_folds_overflow_into_other(self):
        counts = tuple((f"src{i}", 10 - i) for i in range(9))
        html = build_standup_html(_report(activity_counts=counts))
        details = html.split('id="details"')[1]
        assert "other" in details
        assert "var(--muted)" in details.split("legend")[0]  # the folded segment

    def test_coverage_dots(self):
        rep = _report(category_coverage=(("ticketing", "covered"), ("documentation", "not_configured")))
        html = build_standup_html(rep)
        li = html.split("Coverage — ")[1].split("</li>")[0]
        assert "class='dot' style='background:var(--ok)'" in li
        assert "class='dot' style='background:var(--low)'" in li
        assert "covered" in li and "not configured" in li  # status words stay as text

    def test_member_avatars(self):
        rep = _report(member_updates=(MemberUpdate(name="Alice Johnson", summary="x"),))
        html = build_standup_html(rep)
        assert 'class="avatar"' in html
        assert ">AJ</span>" in html

    def test_avatar_xss_name_safe(self):
        rep = _report(member_updates=(MemberUpdate(name="<img src=x>", summary="x"),))
        html = build_standup_html(rep)
        assert "<img src=x>" not in html

    def test_theme_vars_inside_svg(self):
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70)))
        svg = html.split("<svg")[1].split("</svg>")[0]
        assert "var(--accent)" in svg

    def test_self_contained_with_history(self):
        html = build_standup_html(_report(), history=_history(("2026-07-10", 82), ("2026-07-09", 70)))
        assert 'src="http' not in html and "<link" not in html


class TestDayOverDayExport:
    def _rep(self, **over):
        base = dict(
            confidence_delta=-8,
            confidence_trend="declining",
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="login page",
                    progress_note="Still on PSOT-9 from the last standup.",
                    outlook="Likely to wrap up PSOT-9 today.",
                    ticketing_links=(("PSOT-9", "https://acme.atlassian.net/browse/PSOT-9"),),
                ),
            ),
        )
        base.update(over)
        return _report(**base)

    def test_markdown_progress_and_outlook_bullets(self):
        md = build_standup_markdown(self._rep())
        assert "- **Since last standup:** Still on [PSOT-9]" in md
        assert "- **Outlook:** Likely to wrap up [PSOT-9]" in md

    def test_markdown_confidence_trend_suffix(self):
        md = build_standup_markdown(self._rep())
        assert "(▼ 8 vs last standup)" in md
        md_up = build_standup_markdown(self._rep(confidence_delta=6, confidence_trend="improving"))
        assert "(▲ +6 vs last standup)" in md_up

    def test_markdown_no_trend_no_suffix(self):
        md = build_standup_markdown(self._rep(confidence_delta=0, confidence_trend=""))
        assert "vs last standup" not in md

    def test_html_progress_note_and_outlook_render_linkified(self):
        html = build_standup_html(self._rep())
        assert "Since last standup:" in html
        assert ">Outlook</span>" in html
        # Ticket keys inside both prose fields become inline links.
        assert html.count("https://acme.atlassian.net/browse/PSOT-9") >= 2

    def test_html_trend_chip(self):
        html = build_standup_html(self._rep())
        assert "▼ 8 vs last standup" in html
        html_up = build_standup_html(self._rep(confidence_delta=6, confidence_trend="improving"))
        assert "▲ +6 vs last standup" in html_up

    def test_html_no_trend_no_chip(self):
        html = build_standup_html(self._rep(confidence_delta=0, confidence_trend=""))
        assert "vs last standup" not in html

    def test_html_escapes_hostile_fields(self):
        rep = self._rep(
            member_updates=(MemberUpdate(name="Alice", summary="x", progress_note="<b>bold</b>", outlook="<i>it</i>"),),
        )
        html = build_standup_html(rep)
        assert "<b>bold</b>" not in html
        assert "<i>it</i>" not in html

    def test_empty_fields_render_nothing(self):
        html = build_standup_html(_report())
        assert "Since last standup" not in html
        assert ">Outlook</span>" not in html


class TestCardReadability:
    """Sentence-split bullets, link chips, and the adaptive category grid."""

    def test_summary_splits_into_bullets(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary=(
                        "PSOT-1593 was moved to In Progress. Several sub-tasks remain in To Do; "
                        "the access-key work is In Progress."
                    ),
                    ticketing_activity_count=3,
                ),
            ),
        )
        html = build_standup_html(rep)
        assert "<li>PSOT-1593 was moved to In Progress.</li>" in html
        assert "<li>Several sub-tasks remain in To Do</li>" in html
        assert "<li>the access-key work is In Progress.</li>" in html

    def test_leftover_links_render_as_chip_row(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="Moved PSOT-1 forward.",
                    ticketing_links=(
                        ("PSOT-2", "https://j/browse/PSOT-2"),
                        ("PSOT-3", "https://j/browse/PSOT-3"),
                    ),
                    ticketing_activity_count=3,
                ),
            ),
        )
        html = build_standup_html(rep)
        assert "class='chip-row'" in html
        assert "<a class='badge' href='https://j/browse/PSOT-2' target='_blank' rel='noopener'>PSOT-2</a>" in html
        # The old cramped dot-separated link bullet is gone from category blocks.
        assert "</a> · <a" not in html.split("class='analysis-grid member-grid'")[1].split("</div></div>")[0]

    def test_empty_category_becomes_footnote_not_column(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="Moved PSOT-1 forward.",
                    ticketing_activity_count=2,
                    documentation_summary="No documentation activity detected in the selected sources.",
                    documentation_activity_count=0,
                ),
            ),
        )
        html = build_standup_html(rep)
        assert "<h3>Ticketing</h3>" in html
        assert "<h3>Documentation</h3>" not in html
        assert (
            "<p class='card-footnote'>Documentation — No documentation activity detected "
            "in the selected sources.</p>" in html
        )

    def test_not_configured_wording_survives_in_footnote(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="Moved PSOT-1 forward.",
                    ticketing_activity_count=1,
                    documentation_summary="Documentation sources are not configured for this standup.",
                    documentation_activity_count=0,
                ),
            ),
        )
        html = build_standup_html(rep)
        assert "Documentation — Documentation sources are not configured" in html

    def test_all_quiet_member_has_no_grid(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Quiet",
                    summary="No activity detected.",
                    ticketing_summary="No ticketing activity detected.",
                    code_summary="No code activity detected in the selected repositories.",
                    documentation_summary="No documentation activity detected in the selected sources.",
                ),
            ),
        )
        html = build_standup_html(rep)
        card = html.split("Quiet")[1]
        assert "member-grid" not in card.split("</div></div>")[0]
        assert card.count("card-footnote") >= 3

    def test_links_only_category_still_gets_column(self):
        # Evidence links with no prose (legacy-ish shape) must not vanish.
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    code_links=(("PR 42", "https://g/pull/42"),),
                ),
            ),
        )
        html = build_standup_html(rep)
        assert "<h3>Code</h3>" in html
        assert "<a class='badge' href='https://g/pull/42' target='_blank' rel='noopener'>PR 42</a>" in html

    def test_bullets_still_linkify_ticket_keys(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="x",
                    ticketing_summary="PSOT-9 moved to review; PSOT-14 pulled in.",
                    ticketing_links=(("PSOT-9", "https://j/browse/PSOT-9"),),
                    ticketing_activity_count=2,
                ),
            ),
        )
        html = build_standup_html(rep)
        assert (
            "<a href='https://j/browse/PSOT-9' target='_blank' rel='noopener'>PSOT-9</a> moved to review</li>" in html
        )
