"""Tests for the shared export design system (html_theme)."""

from yeaboi.html_theme import (
    EXPORT_CSS,
    chip,
    html_page,
    notice_block,
    section,
    stat_bar,
    stat_tile,
)

THEMES = ("midnight", "light", "solarized", "synthwave", "forest")


def _page(**overrides) -> str:
    kwargs = {"title": "My Report", "body": "<p>hello</p>"}
    kwargs.update(overrides)
    return html_page(**kwargs)


class TestHtmlPage:
    def test_basic_structure(self):
        page = _page(subtitle="A subtitle", meta=["Exported: today"], badges=["Stories"])
        assert page.startswith("<!DOCTYPE html>")
        assert "<title>My Report</title>" in page
        assert "<h1>My Report</h1>" in page  # heading defaults to title
        assert "A subtitle" in page
        assert "Exported: today" in page
        assert "Stories" in page
        assert "<p>hello</p>" in page
        assert "Generated by yeaboi.ai" in page

    def test_self_contained(self):
        page = _page()
        assert "<style>" in page
        assert 'src="http' not in page
        assert 'href="http' not in page
        assert "<link" not in page
        assert "cdn" not in page.lower()

    def test_all_theme_palettes_present(self):
        for theme in THEMES:
            assert f'[data-theme="{theme}"]' in EXPORT_CSS

    def test_compat_aliases_present(self):
        for alias in ("--surface", "--border", "--text-muted", "--tag-bg", "--accent-dark"):
            assert f"{alias}:" in EXPORT_CSS.replace(" ", "")

    def test_heading_override(self):
        page = _page(heading="Custom Heading")
        assert "<h1>Custom Heading</h1>" in page
        assert "<title>My Report</title>" in page

    def test_nav_links(self):
        page = _page(nav=[("stories", "Stories"), ("tasks", "Tasks")])
        assert '<a href="#stories">Stories</a>' in page
        assert '<a href="#tasks">Tasks</a>' in page
        assert 'class="toc"' in page

    def test_no_nav_when_empty(self):
        assert 'class="toc"' not in _page()

    def test_escapes_untrusted_fields(self):
        evil = "<script>alert(1)</script>"
        page = _page(
            title=evil,
            heading=evil,
            subtitle=evil,
            meta=[evil],
            badges=[evil],
            nav=[(evil, evil)],
            footer_note=evil,
        )
        assert "<script>alert(1)</script>" not in page
        assert "&lt;script&gt;alert(1)&lt;/script&gt;" in page

    def test_theme_toggle_present_by_default(self):
        page = _page()
        assert "yeaboi-export-theme" in page
        assert "__yeaboiCycleTheme" in page
        assert 'class="theme-btn"' in page

    def test_theme_toggle_disabled(self):
        page = _page(theme_toggle=False)
        assert "<script>" not in page
        assert 'class="theme-btn"' not in page

    def test_theme_script_is_constant(self):
        """No caller data may ever be interpolated into the inline script."""

        def script_of(page: str) -> str:
            start = page.index("<script>")
            return page[start : page.index("</script>") + 9]

        a = script_of(_page())
        b = script_of(_page(title='"];alert(1);//', badges=["x" * 50]))
        assert a == b

    def test_print_styles_present(self):
        assert "@media print" in EXPORT_CSS


class TestPrimitives:
    def test_chip_neutral(self):
        assert chip("hello") == '<span class="badge badge-tag">hello</span>'

    def test_chip_kind(self):
        assert chip("OK", "ok") == '<span class="badge badge-ok">OK</span>'

    def test_chip_escapes(self):
        assert "<b>" not in chip("<b>x</b>")

    def test_section(self):
        out = section("stories", "User Stories", "<div>body</div>")
        assert '<section id="stories">' in out
        assert "<h2>User Stories</h2>" in out
        assert "<div>body</div>" in out

    def test_section_escapes_title(self):
        assert "<i>" not in section("s", "<i>t</i>", "")

    def test_stat_tile(self):
        out = stat_tile("42", "Stories")
        assert '<div class="num">42</div>' in out
        assert '<div class="lbl">Stories</div>' in out

    def test_stat_bar_clamps(self):
        assert "width:100%" in stat_bar(250)
        assert "width:0%" in stat_bar(-5)
        assert "width:60%" in stat_bar(60.7)

    def test_stat_bar_rejects_bad_token(self):
        out = stat_bar(50, color_var="red;} body{display:none")
        assert "var(--accent)" in out
        assert "display:none" not in out

    def test_stat_bar_custom_token(self):
        assert "var(--warn)" in stat_bar(50, color_var="--warn")

    def test_notice_block(self):
        out = notice_block("Notices", ["one", "two"])
        assert "⚠ Notices" in out
        assert "<li>one</li>" in out
        assert "<li>two</li>" in out

    def test_notice_block_empty(self):
        assert notice_block("Notices", []) == ""

    def test_notice_block_escapes(self):
        assert "<img" not in notice_block("t", ["<img src=x>"])
