"""Export a RoadmapAnalysis to Markdown + self-contained HTML.

Mirrors the standup / retro / reporting exporters (standup/export.py,
reporting/export.py): readable artifacts written under
``~/.yeaboi/exports/roadmap/<roadmap>/`` so an analyzed roadmap persists as a
shareable document, not just a saved row. Two files per run — a Markdown summary
and a self-contained HTML report (using the shared design system
``html_theme``). Re-exporting the same roadmap overwrites so the latest
wins.

Every project ``name`` / ``description`` came from an LLM reading an *untrusted*
roadmap document, so the HTML escapes every field with ``html.escape`` — the same
defense the other exporters use. The TUI **Export** button re-writes on demand.

# See docs: "Roadmap Intake" — Export
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import RoadmapAnalysis, RoadmapProject
from yeaboi.artifacts.render import annotations_markdown, edit_map, row_anchor, with_annotations

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "roadmap"


def _size_label(project: RoadmapProject) -> str:
    """Human-facing size label ('Large' / 'Small')."""
    return "Large" if getattr(project, "size", "") == "large" else "Small"


def _title(analysis: RoadmapAnalysis) -> str:
    label = (analysis.source_label or "").strip()
    return f"Roadmap — {label}" if label else "Roadmap analysis"


def _meta(project: RoadmapProject) -> str:
    """Return 'Q3 2026 · Theme A, Theme B' (either part optional)."""
    return " · ".join(x for x in (project.quarter, ", ".join(project.themes)) if x)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_roadmap_markdown(analysis: RoadmapAnalysis) -> str:
    """Return the roadmap analysis as a Markdown document."""
    when = (analysis.generated_at or "")[:10]
    lines: list[str] = [f"# {_title(analysis)}", ""]
    src = " · ".join(x for x in (analysis.source_type, analysis.source_locator) if x)
    if src:
        lines += [f"**Source:** {src}  "]
    if when:
        lines += [f"**Analyzed:** {when}"]
    lines += [""]
    if analysis.summary:
        lines += [f"> {analysis.summary}", ""]

    if analysis.projects:
        lines += ["## Recommended projects", ""]
        for i, project in enumerate(analysis.projects):
            index = project.priority or (i + 1)
            lines += [f"### {index}. {project.name}  ·  {_size_label(project)}", ""]
            meta = _meta(project)
            if meta:
                lines += [f"_{meta}_", ""]
            if project.description:
                lines += [project.description, ""]
            if project.rationale:
                lines += [f"**Why now:** {project.rationale}", ""]
    else:
        lines += ["_No projects were extracted from the roadmap._", ""]

    if analysis.warnings:
        lines += ["## ⚠ Notices", ""]
        lines += [f"- {w}" for w in analysis.warnings]
        lines += [""]

    lines += annotations_markdown(analysis.annotations)
    lines += ["---", ""]
    lines += [f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {datetime.now().strftime('%Y-%m-%d %H:%M')}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def roadmap_export_args(analysis: RoadmapAnalysis, *, editable: bool = False) -> dict[str, object]:
    """Return the chrome + payload keyword arguments for one roadmap document.

    The size / quarter mix is not computed here. It is a fact *about* the
    project list, and deriving it server-side meant counting into a dict and
    then assembling a bar and a legend that could disagree about which colour
    meant which size; the bundle derives both from one pass.

    No trend sparkline by design: roadmap runs are ad-hoc ingestions, so a
    run-over-run series has no meaningful cadence.
    """
    from yeaboi.web.brand import accent_mode

    args = dict(
        # Planning's accent: a roadmap analysis is the front half of planning,
        # and roadmap intake has no accent of its own in the TUI either. Looked
        # up rather than spelled, so this file is not a second place the
        # mapping lives — `web.brand._BORROWED_ACCENTS` is the first.
        mode=accent_mode("roadmap"),
        title=_title(analysis),
        wordmark="roadmap",
        facts=[
            ("SOURCE", analysis.source_type or ""),
            ("FROM", analysis.source_locator or ""),
            ("ANALYZED", (analysis.generated_at or "")[:10]),
        ],
        report={
            "kind": "roadmap",
            "summary": analysis.summary or "",
            "projects": [
                {
                    "index": project.priority or (i + 1),
                    "name": project.name,
                    "size": getattr(project, "size", ""),
                    "quarter": project.quarter or "",
                    "themes": list(project.themes),
                    "description": project.description or "",
                    "rationale": project.rationale or "",
                    **(
                        {
                            "anchor": row_anchor("projects", "name", project.name),
                            "edit": edit_map(
                                row_anchor("projects", "name", project.name),
                                project,
                                ("description", "rationale", "quarter"),
                            ),
                        }
                        if editable
                        else {}
                    ),
                }
                for i, project in enumerate(analysis.projects)
            ],
            "warnings": list(analysis.warnings or []),
            **({"edit": edit_map("", analysis, ("summary",))} if editable else {}),
        },
        footer=f"Generated by yeaboi.ai • {datetime.now().strftime('%Y-%m-%d')}",
    )
    return with_annotations(args, analysis)


def build_roadmap_html(analysis: RoadmapAnalysis, *, markdown_name: str = "", document_title: str = "") -> str:
    """Return the roadmap analysis as a self-contained HTML document.

    See :func:`yeaboi.standup.export.standup_export_args` for why the payload
    half is a separate function.
    """
    from yeaboi.html_theme import export_page

    return export_page(
        **roadmap_export_args(analysis),  # type: ignore[arg-type]
        markdown_name=markdown_name,
        document_title=document_title,
    )


# ---------------------------------------------------------------------------
# Write helper
# ---------------------------------------------------------------------------


def export_roadmap(analysis: RoadmapAnalysis, *, name: str = "") -> dict[str, Path]:
    """Write the analysis as Markdown + HTML under the roadmap export dir.

    Returns ``{"markdown": Path, "html": Path}``. ``name`` (the roadmap's friendly
    label) picks the sub-directory; re-exporting overwrites so the latest wins.
    """
    from yeaboi.paths import get_roadmap_export_dir

    key = _slug(name or analysis.source_label or "roadmap")
    out_dir = get_roadmap_export_dir(key)
    stem = f"roadmap-{key}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(build_roadmap_markdown(analysis), encoding="utf-8")
    html_path.write_text(build_roadmap_html(analysis, markdown_name=md_path.name), encoding="utf-8")
    logger.info("Roadmap exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
