"""Export a RoadmapAnalysis to Markdown + self-contained HTML.

Mirrors the standup / retro / reporting exporters (standup/export.py,
reporting/export.py): readable artifacts written under
``~/.yeaboi/exports/roadmap/<roadmap>/`` so an analyzed roadmap persists as a
shareable document, not just a saved row. Two files per run — a Markdown summary
and a self-contained HTML report (using the shared design system
``html_theme``). Re-exporting the same roadmap overwrites so the latest
wins.

Every project ``name`` / ``description`` came from an LLM reading an *untrusted*
roadmap document, so the HTML escapes every field with ``html.escape`` — the same
defense the other exporters use. The TUI **Export** button re-writes on demand.

# See docs: "Roadmap Intake" — Export
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import RoadmapAnalysis, RoadmapProject
from yeaboi.html_theme import escape as _e

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "roadmap"


def _size_label(project: RoadmapProject) -> str:
    """Human-facing size label ('Large' / 'Small')."""
    return "Large" if getattr(project, "size", "") == "large" else "Small"


def _title(analysis: RoadmapAnalysis) -> str:
    label = (analysis.source_label or "").strip()
    return f"Roadmap — {label}" if label else "Roadmap analysis"


def _meta(project: RoadmapProject) -> str:
    """Return 'Q3 2026 · Theme A, Theme B' (either part optional)."""
    return " · ".join(x for x in (project.quarter, ", ".join(project.themes)) if x)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_roadmap_markdown(analysis: RoadmapAnalysis) -> str:
    """Return the roadmap analysis as a Markdown document."""
    when = (analysis.generated_at or "")[:10]
    lines: list[str] = [f"# {_title(analysis)}", ""]
    src = " · ".join(x for x in (analysis.source_type, analysis.source_locator) if x)
    if src:
        lines += [f"**Source:** {src}  "]
    if when:
        lines += [f"**Analyzed:** {when}"]
    lines += [""]
    if analysis.summary:
        lines += [f"> {analysis.summary}", ""]

    if analysis.projects:
        lines += ["## Recommended projects", ""]
        for i, project in enumerate(analysis.projects):
            index = project.priority or (i + 1)
            lines += [f"### {index}. {project.name}  ·  {_size_label(project)}", ""]
            meta = _meta(project)
            if meta:
                lines += [f"_{meta}_", ""]
            if project.description:
                lines += [project.description, ""]
            if project.rationale:
                lines += [f"**Why now:** {project.rationale}", ""]
    else:
        lines += ["_No projects were extracted from the roadmap._", ""]

    if analysis.warnings:
        lines += ["## ⚠ Notices", ""]
        lines += [f"- {w}" for w in analysis.warnings]
        lines += [""]

    lines += ["---", ""]
    lines += [f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {datetime.now().strftime('%Y-%m-%d %H:%M')}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def build_roadmap_html(analysis: RoadmapAnalysis) -> str:
    """Return the roadmap analysis as a self-contained HTML document (shared design system).

    No trend sparkline by design: roadmap runs are ad-hoc ingestions, so a
    run-over-run series has no meaningful cadence.
    """
    from yeaboi.html_theme import chip, counted_segment_bar, html_page, notice_block, prose_bullets

    when = (analysis.generated_at or "")[:10]
    meta = [x for x in (analysis.source_type, analysis.source_locator) if x]
    if when:
        meta.append(f"analyzed {when}")

    parts: list[str] = []
    if analysis.summary:
        parts.append(f"<blockquote><strong>{_e(analysis.summary)}</strong></blockquote>")

    if analysis.projects:
        parts.append("<h2>Recommended projects</h2>")
        # At-a-glance mix: projects by size (and by quarter when present).
        size_counts: dict[str, int] = {}
        quarter_counts: dict[str, int] = {}
        for project in analysis.projects:
            size_counts[_size_label(project)] = size_counts.get(_size_label(project), 0) + 1
            if project.quarter:
                quarter_counts[project.quarter] = quarter_counts.get(project.quarter, 0) + 1
        breakdown = counted_segment_bar(sorted(size_counts.items()), title="Projects by size")
        if breakdown:
            parts.append(f"<div style='margin-bottom:.6rem'>{breakdown}</div>")
        if len(quarter_counts) > 1:
            by_quarter = counted_segment_bar(sorted(quarter_counts.items()), title="Projects by quarter")
            parts.append(f"<div style='margin-bottom:.6rem'>{by_quarter}</div>")

        for i, project in enumerate(analysis.projects):
            index = project.priority or (i + 1)
            badge_kind = "warn" if getattr(project, "size", "") == "large" else "ok"
            card: list[str] = [
                f"<div class='card-header'><div class='card-title'><strong>{index}. {_e(project.name)}</strong>"
                f"</div><div class='card-meta'>{chip(_size_label(project), badge_kind)}"
            ]
            # Quarter + themes as a chip row in the header meta.
            if project.quarter:
                card.append(chip(project.quarter))
            card.extend(chip(theme) for theme in project.themes)
            card.append("</div></div>")
            if project.description:
                lis = "".join(f"<li>{_e(fragment)}</li>" for fragment in prose_bullets(project.description))
                if lis:
                    card.append(f"<div class='analysis-section'><ul>{lis}</ul></div>")
            if project.rationale:
                card.append(
                    f"<p style='margin-top:.4rem'><span class='badge'>Why now</span> {_e(project.rationale)}</p>"
                )
            parts.append(f"<div class='card story-card'>{''.join(card)}</div>")
    else:
        parts.append("<p><em>No projects were extracted from the roadmap.</em></p>")

    parts.append(notice_block("Notices", analysis.warnings or []))

    return html_page(
        title=_title(analysis),
        body="".join(parts),
        meta=meta,
        footer_note=f"Generated by yeaboi.ai • {datetime.now().strftime('%Y-%m-%d')}",
    )


# ---------------------------------------------------------------------------
# Write helper
# ---------------------------------------------------------------------------


def export_roadmap(analysis: RoadmapAnalysis, *, name: str = "") -> dict[str, Path]:
    """Write the analysis as Markdown + HTML under the roadmap export dir.

    Returns ``{"markdown": Path, "html": Path}``. ``name`` (the roadmap's friendly
    label) picks the sub-directory; re-exporting overwrites so the latest wins.
    """
    from yeaboi.paths import get_roadmap_export_dir

    key = _slug(name or analysis.source_label or "roadmap")
    out_dir = get_roadmap_export_dir(key)
    stem = f"roadmap-{key}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(build_roadmap_markdown(analysis), encoding="utf-8")
    html_path.write_text(build_roadmap_html(analysis), encoding="utf-8")
    logger.info("Roadmap exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
