"""Export Performance artifacts to Markdown + self-contained HTML.

Mirrors standup/export.py: readable artifacts written under
``~/.scrum-agent/exports/performance/<engineer>/`` so a 1:1 prep, a 1:1 summary,
or a 6-month review persists as a shareable document, not just in the logs. The
HTML uses the shared design system (``html_theme``) for a consistent look.
Every engine run auto-exports; the TUI Export button re-writes on demand.

# See docs: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import OneOnOnePrep, OneOnOneRecord, SixMonthReview
from yeaboi.html_theme import escape as _e
from yeaboi.html_theme import html_page, notice_block

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the per-engineer export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "engineer"


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def _md_section(title: str, items: tuple[str, ...], style: str = "bullets") -> list[str]:
    """A ``## title`` section; ``style`` picks bullets, ``numbered``, or ``tasks``.

    Numbered lists and checkbox task lists give published docs (Notion /
    Confluence) native variety — checkboxes become checkable task items.
    """
    if not items:
        return []
    if style == "numbered":
        body = [f"{i}. {it}" for i, it in enumerate(items, start=1)]
    elif style == "tasks":
        body = [f"- [ ] {it}" for it in items]
    else:
        body = [f"- {it}" for it in items]
    return [f"## {title}", ""] + body + [""]


def _md_footer() -> list[str]:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    return ["---", "", f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {ts}_", ""]


def build_prep_markdown(prep: OneOnOnePrep) -> str:
    lines = [f"# 1:1 Prep — {prep.engineer}", "", f"_Prepared {prep.date}_", ""]
    if prep.activity_summary:
        # Quoted per line so multi-line summaries stay one blockquote.
        lines += ["## Sprint work", "", *(f"> {ln}" for ln in prep.activity_summary.splitlines()), ""]
    lines += _md_section("Carried-over action items", prep.carried_action_items, style="tasks")
    lines += _md_section("Talking points", prep.talking_points, style="numbered")
    lines += _md_section("Feedback to give", prep.feedback)
    lines += _md_section("Goals to align on", prep.goals)
    lines += _md_section("Gaps observed", prep.gaps)
    lines += _md_section("Areas to improve", prep.improvements)
    lines += _md_section("⚠ Notices", prep.warnings)
    return "\n".join(lines + _md_footer())


def build_completion_markdown(record: OneOnOneRecord) -> str:
    lines = [f"# 1:1 Summary — {record.engineer}", "", f"_{record.date}_", ""]
    if record.email_subject:
        lines += [f"**Subject:** {record.email_subject}", ""]
    if record.email_summary:
        lines += ["## Summary email", "", record.email_summary, ""]
    lines += _md_section("Action items", record.action_items, style="tasks")
    lines += _md_section("Highlights", record.highlights)
    lines += _md_section("⚠ Notices", record.warnings)
    return "\n".join(lines + _md_footer())


def build_review_markdown(review: SixMonthReview) -> str:
    lines = [
        f"# 6-Month Performance Review — {review.engineer}",
        "",
        f"_Period: {review.period_start} to {review.period_end}_",
        "",
    ]
    if review.overall:
        # Quoted per line so multi-line assessments stay one blockquote.
        lines += ["## Overall", "", *(f"> {ln}" for ln in review.overall.splitlines()), ""]
    lines += _md_section("Strengths", review.strengths)
    lines += _md_section("Achievements", review.achievements)
    lines += _md_section("Areas for improvement", review.areas_for_improvement)
    lines += _md_section("Goals for next period", review.goals, style="numbered")
    if review.framework_used:
        lines += [f"_Framework: {review.framework_used}_", ""]
    lines += _md_section("⚠ Notices", review.warnings)
    return "\n".join(lines + _md_footer())


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def _html_section(title: str, items: tuple[str, ...]) -> str:
    if not items:
        return ""
    from yeaboi.html_theme import prose_bullets

    lis: list[str] = []
    for item in items:
        # Long packed items split into scannable fragments; short ones stay whole.
        fragments = prose_bullets(item) if len(item) > 160 else [item]
        lis.extend(f"<li>{_e(fragment)}</li>" for fragment in fragments or [item])
    return f"<h2>{_e(title)}</h2><div class='analysis-section'><ul>{''.join(lis)}</ul></div>"


def _engineer_row(name: str) -> str:
    """Identity row with the initials avatar (html_page escapes its heading, so it lives in the body)."""
    if not name:
        return ""
    from yeaboi.html_theme import avatar

    return (
        f"<p style='display:inline-flex;align-items:center;gap:.45rem;font-size:1.05rem'>"
        f"{avatar(name)}<strong>{_e(name)}</strong></p>"
    )


def _html_doc(title: str, body: str, *, subtitle: str = "") -> str:
    return html_page(
        title=title,
        subtitle=subtitle,
        body=body,
        footer_note=f"Generated by yeaboi.ai • {datetime.now().strftime('%Y-%m-%d')}",
    )


def build_prep_html(prep: OneOnOnePrep) -> str:

    parts = [_engineer_row(prep.engineer)]
    if prep.activity_summary:
        parts.append(f"<h2>Sprint work</h2><p>{_e(prep.activity_summary)}</p>")
    parts.append(_html_section("Carried-over action items", prep.carried_action_items))
    parts.append(_html_section("Talking points", prep.talking_points))
    parts.append(_html_section("Feedback to give", prep.feedback))
    parts.append(_html_section("Goals to align on", prep.goals))
    parts.append(_html_section("Gaps observed", prep.gaps))
    parts.append(_html_section("Areas to improve", prep.improvements))
    parts.append(notice_block("Notices", prep.warnings))
    return _html_doc(f"1:1 Prep — {prep.engineer}", "".join(parts), subtitle=f"Prepared {prep.date}")


def build_completion_html(record: OneOnOneRecord) -> str:

    parts = [_engineer_row(record.engineer)]
    if record.email_subject:
        parts.append(f"<p><strong>Subject:</strong> {_e(record.email_subject)}</p>")
    if record.email_summary:
        body = _e(record.email_summary).replace("\n", "<br>")
        parts.append(f"<h2>Summary email</h2><p>{body}</p>")
    parts.append(_html_section("Action items", record.action_items))
    parts.append(_html_section("Highlights", record.highlights))
    parts.append(notice_block("Notices", record.warnings))
    return _html_doc(f"1:1 Summary — {record.engineer}", "".join(parts), subtitle=record.date)


def build_review_html(review: SixMonthReview) -> str:

    parts = [_engineer_row(review.engineer)]
    if review.overall:
        parts.append(f"<h2>Overall</h2><p>{_e(review.overall)}</p>")
    parts.append(_html_section("Strengths", review.strengths))
    parts.append(_html_section("Achievements", review.achievements))
    parts.append(_html_section("Areas for improvement", review.areas_for_improvement))
    parts.append(_html_section("Goals for next period", review.goals))
    if review.framework_used:
        parts.append(f"<p style='color:var(--text-muted);font-size:.85rem'>Framework: {_e(review.framework_used)}</p>")
    parts.append(notice_block("Notices", review.warnings))
    return _html_doc(
        f"6-Month Review — {review.engineer}",
        "".join(parts),
        subtitle=f"Period: {review.period_start} to {review.period_end}",
    )


# ---------------------------------------------------------------------------
# Write helper — dispatches on artifact type
# ---------------------------------------------------------------------------

_BUILDERS = {
    "prep": (build_prep_markdown, build_prep_html),
    "completion": (build_completion_markdown, build_completion_html),
    "review": (build_review_markdown, build_review_html),
}


def export_artifact(artifact, *, engineer: str, kind: str) -> dict[str, Path]:
    """Write a Performance artifact as Markdown + HTML under the engineer's export dir.

    ``kind`` is one of "prep" | "completion" | "review". Returns
    ``{"markdown": Path, "html": Path}``. One dated file per kind — a same-day re-run
    overwrites so the latest wins.
    """
    from yeaboi.paths import get_performance_export_dir

    builders = _BUILDERS.get(kind)
    if builders is None:
        raise ValueError(f"unknown performance artifact kind: {kind!r}")
    md_builder, html_builder = builders

    out_dir = get_performance_export_dir(_slug(engineer))
    on_date = getattr(artifact, "date", "") or getattr(artifact, "period_end", "") or "latest"
    stem = f"{kind}-{on_date}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(md_builder(artifact), encoding="utf-8")
    html_path.write_text(html_builder(artifact), encoding="utf-8")
    logger.info("Performance %s exported: %s , %s", kind, md_path, html_path)
    return {"markdown": md_path, "html": html_path}
