"""Export Performance artifacts to Markdown + self-contained HTML.

Mirrors standup/export.py: readable artifacts written under
``~/.scrum-agent/exports/performance/<engineer>/`` so a 1:1 prep, a 1:1 summary,
or a 6-month review persists as a shareable document, not just in the logs. The
HTML uses the shared design system (``html_theme``) for a consistent look.
Every engine run auto-exports; the TUI Export button re-writes on demand.

# See docs: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import logging
import re
from collections.abc import Sequence
from datetime import datetime
from pathlib import Path

from yeaboi.agent.state import OneOnOnePrep, OneOnOneRecord, SixMonthReview

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the per-engineer export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "engineer"


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def _md_section(title: str, items: tuple[str, ...], style: str = "bullets") -> list[str]:
    """A ``## title`` section; ``style`` picks bullets, ``numbered``, or ``tasks``.

    Numbered lists and checkbox task lists give published docs (Notion /
    Confluence) native variety — checkboxes become checkable task items.
    """
    if not items:
        return []
    if style == "numbered":
        body = [f"{i}. {it}" for i, it in enumerate(items, start=1)]
    elif style == "tasks":
        body = [f"- [ ] {it}" for it in items]
    else:
        body = [f"- {it}" for it in items]
    return [f"## {title}", ""] + body + [""]


def _md_footer() -> list[str]:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    return ["---", "", f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {ts}_", ""]


def build_prep_markdown(prep: OneOnOnePrep) -> str:
    lines = [f"# 1:1 Prep — {prep.engineer}", "", f"_Prepared {prep.date}_", ""]
    if prep.activity_summary:
        # Quoted per line so multi-line summaries stay one blockquote.
        lines += ["## Sprint work", "", *(f"> {ln}" for ln in prep.activity_summary.splitlines()), ""]
    lines += _md_section("Carried-over action items", prep.carried_action_items, style="tasks")
    lines += _md_section("Talking points", prep.talking_points, style="numbered")
    lines += _md_section("Feedback to give", prep.feedback)
    lines += _md_section("Goals to align on", prep.goals)
    lines += _md_section("Gaps observed", prep.gaps)
    lines += _md_section("Areas to improve", prep.improvements)
    lines += _md_section("⚠ Notices", prep.warnings)
    return "\n".join(lines + _md_footer())


def build_completion_markdown(record: OneOnOneRecord) -> str:
    lines = [f"# 1:1 Summary — {record.engineer}", "", f"_{record.date}_", ""]
    if record.email_subject:
        lines += [f"**Subject:** {record.email_subject}", ""]
    if record.email_summary:
        lines += ["## Summary email", "", record.email_summary, ""]
    lines += _md_section("Action items", record.action_items, style="tasks")
    lines += _md_section("Highlights", record.highlights)
    lines += _md_section("⚠ Notices", record.warnings)
    return "\n".join(lines + _md_footer())


def build_review_markdown(review: SixMonthReview) -> str:
    lines = [
        f"# 6-Month Performance Review — {review.engineer}",
        "",
        f"_Period: {review.period_start} to {review.period_end}_",
        "",
    ]
    if review.overall:
        # Quoted per line so multi-line assessments stay one blockquote.
        lines += ["## Overall", "", *(f"> {ln}" for ln in review.overall.splitlines()), ""]
    lines += _md_section("Strengths", review.strengths)
    lines += _md_section("Achievements", review.achievements)
    lines += _md_section("Areas for improvement", review.areas_for_improvement)
    lines += _md_section("Goals for next period", review.goals, style="numbered")
    if review.framework_used:
        lines += [f"_Framework: {review.framework_used}_", ""]
    lines += _md_section("⚠ Notices", review.warnings)
    return "\n".join(lines + _md_footer())


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def _perf_page(
    *,
    engineer: str,
    wordmark: str,
    title: str,
    subtitle: str,
    sections: Sequence[tuple[str, Sequence[str]]],
    lead: tuple[str, str] | None = None,
    footnote: str = "",
    warnings: Sequence[str] = (),
    markdown_name: str = "",
) -> str:
    """Render any one of the three performance artifacts.

    One function for all three, because all three *are* one shape: an engineer,
    at most one block of free prose, then a list of titled bullet runs. The
    previous ``build_prep_html`` / ``build_completion_html`` / ``build_review_html``
    differed only in which section titles they passed — three copies of the same
    assembly, each with a Markdown twin differing the same way. The Markdown
    builders above still differ (numbered lists and task checkboxes are real
    distinctions there, and they publish to Notion / Confluence as native
    blocks); the HTML side had no such reason.

    Empty sections are dropped here rather than in the renderer so the payload
    carries no rows that draw nothing.
    """
    from yeaboi.html_theme import export_page

    report: dict[str, object] = {
        "kind": "performance",
        "engineer": engineer,
        "sections": [{"title": name, "items": list(items)} for name, items in sections if items],
        "warnings": list(warnings),
    }
    if lead and lead[1]:
        report["lead"] = {"title": lead[0], "text": lead[1]}
    if footnote:
        report["footnote"] = footnote

    return export_page(
        mode="performance",
        title=title,
        wordmark=wordmark,
        subtitle=subtitle,
        # No ENGINEER eyebrow: the title says the name and the body opens with
        # the avatar row, and a header that says "Ada Lovelace" three times in
        # 100 vertical pixels is not emphasis, it is noise.
        report=report,
        footer=f"Generated by yeaboi.ai • {datetime.now().strftime('%Y-%m-%d')}",
        markdown_name=markdown_name,
    )


def build_prep_html(prep: OneOnOnePrep, *, markdown_name: str = "") -> str:
    return _perf_page(
        engineer=prep.engineer,
        wordmark="prep",
        title=f"1:1 Prep — {prep.engineer}",
        subtitle=f"Prepared {prep.date}",
        lead=("Sprint work", prep.activity_summary),
        sections=[
            ("Carried-over action items", prep.carried_action_items),
            ("Talking points", prep.talking_points),
            ("Feedback to give", prep.feedback),
            ("Goals to align on", prep.goals),
            ("Gaps observed", prep.gaps),
            ("Areas to improve", prep.improvements),
        ],
        warnings=prep.warnings,
        markdown_name=markdown_name,
    )


def build_completion_html(record: OneOnOneRecord, *, markdown_name: str = "") -> str:
    return _perf_page(
        engineer=record.engineer,
        wordmark="summary",
        title=f"1:1 Summary — {record.engineer}",
        subtitle=record.date,
        lead=("Summary email", record.email_summary),
        sections=[
            # The subject is one line and belongs with the email it titles, but
            # it is not a bullet run, so it rides as a one-item section rather
            # than growing a second free-prose slot used by one artifact.
            ("Subject", (record.email_subject,) if record.email_subject else ()),
            ("Action items", record.action_items),
            ("Highlights", record.highlights),
        ],
        warnings=record.warnings,
        markdown_name=markdown_name,
    )


def build_review_html(review: SixMonthReview, *, markdown_name: str = "") -> str:
    return _perf_page(
        engineer=review.engineer,
        wordmark="review",
        title=f"6-Month Review — {review.engineer}",
        subtitle=f"Period: {review.period_start} to {review.period_end}",
        lead=("Overall", review.overall),
        sections=[
            ("Strengths", review.strengths),
            ("Achievements", review.achievements),
            ("Areas for improvement", review.areas_for_improvement),
            ("Goals for next period", review.goals),
        ],
        footnote=f"Framework: {review.framework_used}" if review.framework_used else "",
        warnings=review.warnings,
        markdown_name=markdown_name,
    )


# ---------------------------------------------------------------------------
# Write helper — dispatches on artifact type
# ---------------------------------------------------------------------------

_BUILDERS = {
    "prep": (build_prep_markdown, build_prep_html),
    "completion": (build_completion_markdown, build_completion_html),
    "review": (build_review_markdown, build_review_html),
}


def export_artifact(artifact, *, engineer: str, kind: str) -> dict[str, Path]:
    """Write a Performance artifact as Markdown + HTML under the engineer's export dir.

    ``kind`` is one of "prep" | "completion" | "review". Returns
    ``{"markdown": Path, "html": Path}``. One dated file per kind — a same-day re-run
    overwrites so the latest wins.
    """
    from yeaboi.paths import get_performance_export_dir

    builders = _BUILDERS.get(kind)
    if builders is None:
        raise ValueError(f"unknown performance artifact kind: {kind!r}")
    md_builder, html_builder = builders

    out_dir = get_performance_export_dir(_slug(engineer))
    on_date = getattr(artifact, "date", "") or getattr(artifact, "period_end", "") or "latest"
    stem = f"{kind}-{on_date}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(md_builder(artifact), encoding="utf-8")
    html_path.write_text(html_builder(artifact, markdown_name=md_path.name), encoding="utf-8")
    logger.info("Performance %s exported: %s , %s", kind, md_path, html_path)
    return {"markdown": md_path, "html": html_path}
